<h3 align="center">Manage Sessionals</h3>
<div id="main_div">

	<div id="selection-div"class="ui-widget-content ui-corner-all" style="width:20em; height:5em; padding:4px">
		<label for="degree_id" accesskey="S" id="lbl_degree_id" style="padding: 0.4em; float: left;">
			Degree:</label>&nbsp;
		<select id="degree_select" tabindex="1" >
		</select>
		
		<br /><br />
		
		<label for="class_id" accesskey="S" id="lbl_class_id" style="padding: 0.4em; float: left;" >
			Class:</label>&nbsp;
		<select id="class_select" tabindex="1" ></select>
		
	</div> <!-- End sessional-select-div -->
	<br />
	
	<div id="sessional-schedule-div" style="display">
		<table id="tblgrid" class="scroll"></table>
		<div id="gridpager" class="scroll" style="text-align: center;"></div>
	</div><!-- End sessioanl-schedule-div -->

</div> <!-- End main_div -->


<script type="text/javascript" language="javascript">

$(function(){
    var gridTable = "#tblgrid";
    var gridPager = "#gridpager"; 
    var dep_id = 'CSE';
    
    var urlFillGrid = "<? echo $this->url(array(
												'controller' => 'sessional', 
												'action' => 'fillgrid'))?>";
												
    var urlCRUD = "<? echo $this->url(array('module' => $this->module, 
											'controller' => $this->controller, 
											'action' => 'crud'), 'default', true)?>";
											
	var urlDegreeCombo = "<?php echo 'http://' . CORE_SERVER . $this->url(array('controller' => 'semesterdegree', 
																				'action' => 'getslavedegree'), 
																				'default', true)?>";
																				
	var urlFetchActiveClasses = "<?php echo 'http://' . CORE_SERVER . $this->url(array('controller' => 'semesterdegree', 
																				'action' => 'getsemester'), 
																				'default', true)?>";
										    
	$.ajax({
        url : urlDegreeCombo,
        dataType : 'jsonp',
        data : {'masterDepartment': 'CSE','slaveDepartment' : 'CSE', 'format' : 'jsonp' },
        success: function(jDegree){
        	var selectOptionString = '<option value ="">Select one</option>';
			$.each(jDegree, function (index, degree) {
				selectOptionString += '<option value ="'+degree.degree_id+'">'+degree.degree_id+'</option>';
			});
            $('#degree_select').html(selectOptionString);
            },
            error: function(event) {
                alert(event.responseText);
                }
            });//End ajax call.
    
	$('#degree_select').change({
		
		var deg_id = $("#degree_select").val();
		
		$.ajax({
	        url : urlFetchActiveClasses,
	        dataType : 'jsonp',
	        data : {'degree_id' : deg_id ,'department_id' : dep_id, 'format' : 'jsonp'}, 
	        success: function(jClass){
	        	alert(jClass.responseText);
	            },
	            error: function(event) {
	                alert(event.responseText);
	            }
	    });//End ajax call.
        	
	});//End #degree_select change.

    
	$(gridTable).jqGrid({
		colNames:['Subject Code','Subject Name','Date of conduct','Time','Max Marks','Pass Marks','Optional'],
		colModel:[
			{
				name:'subject_code',
        	    index:'subject_code'
            },
            {
				name:'subject_name',
        	    index:'subject_name'
            },
            {
                name:'date_of_conduct',
                index:'date_of_conduct'
            },
            {
                name:'time', 
                index:'time'},
            {
                name:'max_marks',
                index:'max_marks',
                hidden: true},
            {
                name:'pass_marks', 
                index:'pass_marks',
                hidden: true},
            {
                name:'is optional', 
                index:'is_optional',
                hidden: true},
            ],
        caption: "Manage Sessional Schedule  " ,
        pager: gridPager,
        editurl:urlCRUD
		});

	$(gridTable).jqGrid('navGrid', gridPager, {
        add : false,
        del : false,
        edit : false,
        view : false,
        search : false,
        refresh : false
    }, // options
            {
                width : 400,
                savekey : [ true, 13 ],
                navkeys : [ true, 38, 40 ],
                jqModal : false,
                closeOnEscape : true
            }, // edit options
            {
                width : 400,
                savekey : [ true, 13 ],
                navkeys : [ true, 38, 40 ],
                jqModal : false,
                closeOnEscape : true,
                clearAfterAdd : true //Default is true, make false if needed
            }, // add options
            {
                reloadAfterSubmit : false,
                jqModal : false,
                closeOnEscape : true
            } // del options
         );
    
    addPager(gridTable, gridPager); 
    
	});
	
</script>