<div class="gridstyle">
<table id="prdlst" class="scroll" cellpadding="0" cellspacing="0"></table>
</div>
<script type="text/javascript">
$(function(){
var baseurl = "<?=$this->url ( array ('controller' => 'studentattendance', 'action' => 'fillperiodgrid' ), 'default', true )?>";
$("#prdlst").jqGrid({
		datatype: "local",
		colNames:['Subject Code' , 'Subject Mode','Weekday','Period','Department', 'Degree','Semester','Group'],
		colModel:[
					{name:'subject_code',
						index:'subject_code'},
					{name:'subject_mode_id',
						index:'subject_mode_id',
						width: 100,
						align: 'center'},
					{name:'weekday_number',
						index:'weekday_number',
						width: 100,
						align: 'center'},
					{name:'period_number',
						index:'period_number',
						width: 60,
						align: 'center',
						formatter:'number', 
						formatoptions:{decimalPlaces: 0}},
					{name:'department_id',
						index:'department_id',
						width: 80,
						align: 'center'},
					{name:'degree_id',
						index:'degree_id',
						width: 60,
						align: 'center'},
					{name:'semester_id',
						index:'semester_id',
						width: 70,
						align: 'center',
						formatter:'number', 
						formatoptions:{decimalPlaces: 0}},
					{name:'group_id',
						index:'group_id',
						width: 60,
						align: 'center'}
			  		],

		sortname: 'period_number',
	    altRows: true,
	    loadonce : true,
	    shrinkToFit : true,
	    forceFit : true,
	    hoverrows : false,
	    rowNum: 50,
	    prmNames: {page: null, rows: null, sort: null, order: null, search: null, nd: null},
		caption: "Timetable: <?php echo strtoupper($this->staff_id); ?>"
		}).jqGrid('gridResize');


var staff_id = '<?php echo $this->staff_id; ?>';
$.ajax({
	type: "GET",
	url: baseurl ,
	dataType : "json",
	async :  false,
	data: {staff_id : staff_id  },
	success: function(gridData) {
		for(var cnt = 0;cnt <  gridData.rows.length ;cnt++){
		var data = { subject_code : gridData.rows[cnt].cell['subject_name'], 
						subject_mode_id : gridData.rows[cnt].cell['subject_mode_name'],
						weekday_number : gridData.rows[cnt].cell['weekday_name'],
						period_number : gridData.rows[cnt].cell['period_number'],
						department_id : gridData.rows[cnt].cell['department_id'], 
						degree_id : gridData.rows[cnt].cell['degree_id'], 
						semester_id : gridData.rows[cnt].cell['semester_id'],
						group_id : gridData.rows[cnt].cell['group_id']						    						
						 };
			$("#prdlst").addRowData(gridData.rows[cnt].cell['period_number'],data);

			 $("#prdlst").setCell(gridData.rows[cnt].cell['period_number'], 
                     'period_number', 
                     "", 
                     "", 
                     {title: gridData.rows[cnt].cell['period_id']});
             
			$("#prdlst").setCell(gridData.rows[cnt].cell['period_number'], 
				                 'subject_code', 
				                 "", 
				                 "", 
				                 {title: gridData.rows[cnt].cell['subject_code'] });
			$("#prdlst").setCell(gridData.rows[cnt].cell['period_number'], 
				                 'subject_mode_id', 
				                 "",
				                 "",
				                 {title: gridData.rows[cnt].cell['subject_mode_id']  });
			 if(gridData.rows[cnt].cell['adjusted'] == 1)
             {
				$("#" +gridData.rows[cnt].cell['period_number']).addClass("adjusted");
             }

			 if(gridData.rows[cnt].cell['nonattendance'] == 1)
             {
				$("#" +gridData.rows[cnt].cell['period_number']).addClass("nonattendanceday");				
             }
             
			}

			
					
	},
	
	error: function(request,error) {
		alert("Bad Request: "+ request+ " " + error);
	}
		
});
});

</script>