<style type="text/css">
.auto-style1 {
	font-size: xx-small;
	font-family: "Lucida Sans", "Lucida Sans Regular", "Lucida Grande", "Lucida Sans Unicode", Geneva, Verdana, sans-serif;
	color: #808080;
}
</style>
<h3>Considerations</h3>
<ul>
	<li><a href="/dept">Department</a><ul>
		<li><a href="/degreedepartment">Department Courses</a></li>
	</ul>
	</li>
	<li><a href="/degree">Courses</a><ul>
		<li><a href="/groups">Groups</a></li>
	</ul>
	</li>
	<li><a href="/batch">Batches</a><ul>
		<li><a href="/batchsemester">Batch-Semester</a></li>
	</ul>
	</li>
	<li><a href="/block">Academic Blocks</a></li>
	<li><a href="javascript:void(0);">Staff</a>*</li>
	<li><a href="javascript:void(0);">Students</a>*</li>
	<li><a href="javascript:void(0);">Misc.</a><ul>
		<li><a href="/weekday">Weekday</a></li>
		<li><a href="javascript:void(0);">Session</a>*</li>
	</ul>
	</li>
</ul>
<p class="auto-style1">* Imported directly to db either using excel or direct entry 
via db gui editor.</p>
