<?php
    $department = $this->departments;
    $programme = $this->programmes;
?>
<form id="batch" class="uniForm" action="javascript:submit_batch()">
<h3>Add New Batch</h3>
<fieldset id="batch_info">
	<h5>Please fill this form and click on next to add a new batch.</h5>
	<div class="ctrlHolder">
		<label for="department_id"><em>*</em>Department</label>
		<select id="department_id" name="department_id" class="required">
		<option value="">Select the programme</option>
		<?php 
		    foreach ($department as $key => $value)
		    {
                echo '<option value="'.$key.'">'.$value.'</option>';
		    }
		?>
		</select>
		<p class="formHint">Select Department</p>
	</div>
					
	<div class="ctrlHolder">
		<label for="programme_id"><em>*</em>Programme</label>
		<select id="programme_id" name="programme_id" class="required">
			<option value="">Select the programme</option>
			<?php 
		    foreach ($programme as $key => $value)
		    {
                echo '<option value="'.$key.'">'.$value.'</option>';
		    }
		?>
		</select>
		<p class="formHint">Select the programme</p>
	</div>
	
	<div class="ctrlHolder">
		<label for="batch_start"><em>*</em>Batch Start</label>
		<select id="batch_start" name="batch_start" class="required">
			<option value="">Select the year</option>
			<?php
			    $current_year = intval(date('Y'));
			    for($i=2002;$i<=$current_year;$i++)
			    {
			        echo '<option value="'.$i.'">'.$i.'</option>';
			    }
			?>
		</select>
		<p class="formHint">Select the starting year of the batch</p>
	</div>
    
    <div class="ctrlHolder">
		<label for="semester"><em>*</em>Semester</label>
		<select id="semester" name="semester" class="required">
			<option value="">Select the semester</option>
			<?php
			    for($i=1;$i<=8;$i++)
			    {
			        echo '<option value="'.$i.'">'.$i.'</option>';
			    }
			?>
		</select>
		<p class="formHint">Select the Semster</p>
	</div>
	
	<div class="ctrlHolder" id="type">
		<label for="type"><em>*</em>Select how to you want to register students</label>
			Specify roll number(s) : <input type="radio" name="by_roll_no" value="by_roll_no" onchange="javascript:show_option('roll_no')"><br>
			Specify range : <input type="radio" name="by_roll_no" value="by_range" onchange="javascript:show_option('range')">
	</div>
	
	<div id="submitStatus" style="display:none;padding: 1em;" class="ui-state-highlight ui-corner-all" ></div> 
	<div class="buttonHolder">
		<button type="reset" class="secondaryAction">Reset</button>
		<button type="submit" class="primaryAction">Next</button>
	</div>
</fieldset>
</form>

<script>

$(function(){
	$('form.uniForm').uniform({
		prevent_submit : true
	});
});       

function submit_batch() {
	var urlSaveInfo = 'http://academic.aceambala.com/batch/getbatchids';
    $.ajax({
        url : urlSaveInfo,
        dataType : 'jsonp',
        data : {
            	myarray:getBatchValues(),
            	format : 'jsonp'
            },
        async : 'false',
        success: function(jStatus){
            batch_id = jStatus[0];
            submit_semester(batch_id);
        },
        error: function(response) {
          $('#errorBox').text(response.responseText).parent().show();
             console.log(response);
        }
    });
}

function getBatchValues() {
	var formData = {};
	formData['department_id'] = $('#department_id').val();
	formData['programme_id'] = $('#programme_id').val();
	formData['batch_start'] = $('#batch_start').val();
	
	return formData;
}

function submit_semester(batch_id) {
	var urlSaveInfo = 'http://academic.aceambala.com/class/getclassids';
    $.ajax({
        url : urlSaveInfo,
        dataType : 'jsonp',
        data : {
            	myarray: {
                	'batch_id' : batch_id,
                	'semester_id' : $('#semester_id').val()
                },
            	format : 'jsonp'
            },
        async : 'false',
        success: function(jStatus){
            class_id = jStatus[0];
            submit_roll_numbers(class_id);
        },
        error: function(response) {
          $('#errorBox').text(response.responseText).parent().show();
             console.log(response);
        }
    });
}

function submit_roll_numbers(class_id) {
	var urlSaveInfo = 'http://academic.aceambala.com/class/getclassids';
    $.ajax({
        url : urlSaveInfo,
        dataType : 'jsonp',
        data : {
            	myarray: {
                	'batch_id' : batch_id,
                	'semester_id' : $('#semester_id').val()
                },
            	format : 'jsonp'
            },
        async : 'false',
        success: function(jStatus){
            class_id = jStatus[0];
            submit_roll_numbers(class_id);
        },
        error: function(response) {
          $('#errorBox').text(response.responseText).parent().show();
             console.log(response);
        }
    });
}

function show_option(method)
{
	if(method == 'roll_no')
	{
		var html = '<div class="ctrlHolder" id="roll_numbers">'+
				'<label for="roll_numbers">Enter Roll Numbers</label>'+
				'<input name="roll_numbers" id="roll_numbers" value="" data-default-value="2308017,2308019,2308060" size="35" maxlength="100" type="text" class="textInput required"/>'+
				'<p class="formHint">Enter roll numbers sepreated by commas. Please double check the values before submitting.</p>'+
				'</div>';

		$('#type').after(html);
		$('#range').remove();
	}
	else
	{
		var html = '<div class="ctrlHolder noLabel" id="range">'+
		'<ul class="alternate">'+
           	'<li><label for="upper_range"><em>*</em>From</label>'+
         		'<input name="upper_range" id="upper_range" data-default-value="e.g. 2308001" value="" size="10" maxlength="50" type="text" class="textInput required"/></li>'+
           	'<li><label for="lower_range"> To</label>'+
         		'<input name="lower_range" id="lower_range" data-default-value="e.g. 2308060" value=""  size="10" maxlength="50" type="text" class="textInput required"/></li>'+
		'</ul>'+
		'<p class="formHint">Enter roll numbers range. Please double check the values before submitting.</p>'+
	'</div>';

		$('#type').after(html);
		$('#roll_numbers').remove();
	}
}
</script>

<style>
	.uniForm{
		background-color:white;
		padding:10px 10px 10px 25px;
		border:1px solid #b4c1da;
		margin:0 0 40px 0;
		box-shadow:#e4e4e4 0px 0px 1px 1px;
		width:auto;
	}
	h3{
    	color: #343434;
    	line-height: 1;
    	margin: 1.5em -28px;
    	padding: 14px 28px;
		background-color: #ECEFF4;
    	border: 1px solid #B4C1DA;
    	font-size: 17px;
    	font-weight: 100;
    	width: 57%;
	}
	h4{
		padding:3px 3px 3px 10px;
		background-color:#eceff4;
		border:1px solid #b4c1da;
		width:57%;
		font-size:17px;
		font-weight:100;
	}
	h5{
		font-size: 14px;
		font-weight:400;
		margin: 0 0 15px 0;
	}
</style>
<?php
$this->headScript()->appendFile('http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
    
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/smooth.uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/demos/css/demo.css');
?>