<!--[if lte ie 7]>
      <style type="text/css" media="screen">
        /* Move these to your IE6/7 specific stylesheet if possible */
        .uniForm, .uniForm fieldset, .uniForm .ctrlHolder, .uniForm .formHint, .uniForm .buttonHolder, .uniForm .ctrlHolder ul{ zoom:1; }
      </style>
<![endif]-->
<h2>Academic Information:</h2>
<form id="initial_div" action="javascript:show_div()">
	Please select from following to fill the details.<br>
	<span class="checkbox_name">Tenth : &nbsp;&nbsp;&nbsp;</span><input type="checkbox" value="tenth" name="tenth"/><br>
	<span class="checkbox_name">Twelfth : </span><input type="checkbox" value="twelfth" name="twelfth"/><br>
	<span class="checkbox_name">Diploma : </span><input type="checkbox" value="diploma" name="diploma"/><br>
	<span class="checkbox_name">B.Tech : &nbsp;&nbsp;</span><input type="checkbox" value="btech" name="btech"/><br><br>
	<input type="submit" value="Fill">
</form>

<form id="academic_form" action="javascript:submit();" class="uniForm">     

<fieldset id="tenth">
<h3>Matric Information</h3>
	<div class="ctrlHolder">
		<label for=""><em>*</em>Board</label>
		<input name="board" id="board" value="" data-default-value="e.g. CBSE" size="35" maxlength="50" type="text" class="textInput required"/>
		<p class="formHint">Education Board in 12th</p>
	</div>
            
    <div class="ctrlHolder">
		<label for=""><em>*</em> 10+2 Roll no.</label>
		<input name="board_roll_no" id="board_roll_no" value="" data-default-value="e.g. 2310654" size="35" maxlength="20" type="text" class="textInput"/>
		<p class="formHint">10+2 roll number of </p>
	</div>
				
	<div class="ctrlHolder">
		<label for=""><em>*</em>Marks Obtained</label>
		<input name="marks_obtained" id="marks_obtained" value="" data-default-value="e.g. 450" size="35" maxlength="50" type="text" class="textInput required validateInteger"/>
		<p class="formHint">Marks Obtained by <span class="cName" >Candidate</span></p>
	</div>
				  
	<div class="ctrlHolder">
		<label for=""><em>*</em>Total Marks</label>
		<input name="total_marks" id="total_marks" value="" data-default-value="e.g. 500" size="35" maxlength="50" type="text" class="textInput required validateInteger"/>
		<p class="formHint">Total Marks</p>
	</div>
			
	<div class="ctrlHolder">
		<label for=""><em>*</em>Percentage</label>
		<input name="percentage" id="percentage" value="" data-default-value="e.g. 90" size="35" maxlength="50" type="text" class="textInput required validateNumber  validateMax val-100"/>
		<p class="formHint">Percentage obtained by <span class="cName" >Candidate</span> in Physics, Chemistry, Math/Biology</p>
	</div>
				  
	<div class="ctrlHolder">
		<label for=""><em>*</em>Year of Passing</label>
		<input name="passing_year" id="passing_year" value="" data-default-value="e.g. 2007" size="35" maxlength="50" type="text" class="textInput required validateInteger validateMax val-<?php echo date('Y');?>"/>
		<p class="formHint">Year in which <span class="cName" >Candidate</span> passed the 12th</p>
	</div>
			
	<div class="ctrlHolder">
		<label for="">School Rank</label>
		<input name="school_rank" id="school_rank" value="" data-default-value="e.g. 1" size="35" maxlength="50" type="text" class="textInput validateInteger"/>
		<p class="formHint">School rank of  <span class="cName" >Candidate</span></p>
	</div>
				  
	<div class="ctrlHolder">
		<label for=""><em>*</em>Institution</label>
		<input name="institution" id="institution" value="" data-default-value="e.g. Saraswati Senior Secondary School" size="35" maxlength="50" type="text" class="textInput required"/>
		<p class="formHint">Institution in 12th</p>
	</div>
				
	<div class="ctrlHolder">
		<label for=""><em>*</em>City</label>
		<input name="city_name" id="city_name" value="" data-default-value="e.g. Ambala" size="35" maxlength="50" type="text" class="textInput required"/>
		<p class="formHint">City of Institution</p>
    </div>
				  
	<div class="ctrlHolder">
		<label for=""><em>*</em>State</label>
		<input name="state_name" id="state_name" value="" data-default-value="e.g. Haryana" size="35" maxlength="50" type="text" class="textInput required"/>
		<p class="formHint">State of Institution</p>
	</div>
</fieldset>

<fieldset id="leet">
<h3>LEET</h3>
				
	<div class="ctrlHolder">
		<label for=""><em>*</em>Roll Number</label>
		<input name="roll_no" id="roll_no" value="" data-default-value="e.g. 450" size="35" maxlength="50" type="text" class="textInput required validateInteger"/>
		<p class="formHint">All India Roll No. of <span class="cName" >Candidate</span></p>
	</div>
					
	<div class="ctrlHolder">
		<label for="doc"><em>*</em>Date of Conduct</label>
		<input name="doc" id="doc2" data-default-value="2011-04-04" value=""  size="35" maxlength="50" type="text" readonly="readonly" class="textInput required"/>
		<p class="formHint">1. Select year <br/>2. Select Month<br/>3. Click date of birthday</p>
	</div>
        
	<div class="ctrlHolder">
		<label for=""><em>*</em>All India Rank (AIR)</label>
		<input name="all_india_rank" id="all_india_rank" value="" data-default-value="e.g. 450" size="35" maxlength="50" type="text" class="textInput required validateInteger"/>
		<p class="formHint">All India Rank of <span class="cName" >Candidate</span></p>
	</div>
					
	<div class="ctrlHolder">
		<label for=""><em>*</em>LEET Marks</label>
		<input name="total_score" id="total_score" value="" data-default-value="e.g. 145" size="35" maxlength="50" type="text" class="textInput validateInteger"/>
		<p class="formHint">Marks of LEET Form</p>
	</div>
</fieldset>

<fieldset id="diploma">
	<h3>Diploma Marks</h3>
			
	<div class="ctrlHolder">
		<label for=""><em>*</em>Branch</label>
		<input name="discipline_name" id="discipline_name" value=""  data-default-value="e.g. Computer Science" size="35" maxlength="50" type="text" class="textInput required validatePhrase"/>
		<p class="formHint">Branch of  <span class="cName" >Candidate</span>(in full form only)</p>
	</div>
			
	<div class="ctrlHolder">
		<label for=""><em>*</em> Roll no.</label>
		<input name="board_roll_no" id="board_roll_no" value="" data-default-value="e.g. 2310654" size="35" maxlength="20" type="text" class="textInput"/>
		<p class="formHint">  </p>
	</div>
				
	<div class="ctrlHolder">
		<label for=""><em>*</em>Marks Obtained</label>
		<input name="marks_obtained" id="marks_obtained" value="" data-default-value="e.g. 450" size="35" maxlength="50" type="text" class="textInput required validateInteger"/>
		<p class="formHint">Marks Obtained by <span class="cName" >Candidate</span></p>
	</div>
			 	
	<div class="ctrlHolder">
		<label for=""><em>*</em>Total Marks</label>
		<input name="total_marks" id="total_marks" value="" data-default-value="e.g. 500" size="35" maxlength="50" type="text" class="textInput required validateInteger"/>
		<p class="formHint">Total Marks</p>
	</div>
				
	<div class="ctrlHolder">
		<label for=""><em>*</em>Percentage</label>
		<input name="percentage" id="percentage" value="" data-default-value="e.g. 90" size="35" maxlength="50" type="text" class="textInput required validateNumber  validateMax val-100"/>
		<p class="formHint">Percentage obtained by <span class="cName" >Candidate</span> in Physics, Chemistry, Math/Biology</p>
	</div>
				
	<div class="ctrlHolder">
		<label for=""><em>*</em>Year of Passing</label>
		<input name="passing_year" id="passing_year" value="" data-default-value="e.g. 2007" size="35" maxlength="50" type="text" class="textInput required validateInteger"/>
		<p class="formHint">Year in which <span class="cName" >Candidate</span> passed the Diploma</p>
	</div>
		        
	<div class="ctrlHolder">
		<label for=""><em>*</em>University</label>
		<input name="university" id="university" value="" data-default-value="e.g. Govt. Polytechnic" size="35" maxlength="50" type="text" class="textInput required"/>
		<p class="formHint">University in Diploma</p>
	</div>
		        
	<div class="ctrlHolder">
		<label for=""><em>*</em>Institution</label>
		<input name="institution" id="institution" value="" data-default-value="e.g. Govt. Polytechnic" size="35" maxlength="50" type="text" class="textInput required"/>
		<p class="formHint">Institution in Diploma</p>
	</div>
				
	<div class="ctrlHolder">
		<label for=""><em>*</em>Rank in DET</label>
		<input name="leet_rank" id="leet_rank" value="" data-default-value="e.g. 450" size="35" maxlength="50" type="text" class="textInput required validateInteger"/>
		<p class="formHint">Rank of <span class="cName" >Candidate</span></p>
	</div>
			
	<div class="ctrlHolder">
		<label for=""><em>*</em>City</label>
		<input name="institution_city" id="institution_city" value="" data-default-value="e.g. Ambala" size="35" maxlength="50" type="text" class="textInput required"/>
		<p class="formHint">City of Institution</p>
	</div>
          
	<div class="ctrlHolder">
		<label for=""><em>*</em>State</label>
		<input name="institution_state" id="institution_state" value="" data-default-value="e.g. Haryana" size="35" maxlength="50" type="text" class="textInput required"/>
		<p class="formHint">State of Institution</p>
	</div>
</fieldset>

<fieldset id="aieee">
	<h3>AIEEE</h3>
				
	<div class="ctrlHolder">
		<label for=""><em>*</em>Roll Number</label>
		<input name="roll_no" id="roll_no" value="" data-default-value="e.g. 450" size="35" maxlength="50" type="text" class="textInput required validateInteger"/>
		<p class="formHint">All India Roll No. of <span class="cName" >Candidate</span></p>
	</div>
					
	<div class="ctrlHolder">
		<label for="doc"><em>*</em>Date of Conduct</label>
		<input name="doc" id="doc1" data-default-value="2011-04-04" value=""  size="35" maxlength="50" type="text" readonly="readonly" class="textInput required"/>
		<p class="formHint">1. Select year <br/>2. Select Month<br/>3. Click date of birthday</p>
	</div>
        
					
	<div class="ctrlHolder">
		<label for=""><em>*</em>All India Rank (AIR)</label>
		<input name="all_india_rank" id="all_india_rank" value="" data-default-value="e.g. 450" size="35" maxlength="50" type="text" class="textInput required validateInteger"/>
		<p class="formHint">All India Rank of <span class="cName" >Candidate</span></p>
	</div>
					
	<div class="ctrlHolder">
		<label for=""><em>*</em>AIEEE Marks</label>
		<input name="total_score" id="total_score" value="" data-default-value="e.g. 145" size="35" maxlength="50" type="text" class="textInput validateInteger"/>
		<p class="formHint">Marks of AIEEE Form</p>
	</div>					
</fieldset>

<fieldset id="twelfth">
	<h3>Twelfth Marks</h3>

	<div class="ctrlHolder">
		<label for=""><em>*</em>Board</label>
		<input name="board" id="board" value="" data-default-value="e.g. CBSE" size="35" maxlength="50" type="text" class="textInput required"/>
		<p class="formHint">Education Board in 12th</p>
	</div>
            
	<div class="ctrlHolder">
		<label for=""><em>*</em> 10+2 Roll no.</label>
		<input name="board_roll_no" id="board_roll_no" value="" data-default-value="e.g. 2310654" size="35" maxlength="20" type="text" class="textInput"/>
		<p class="formHint">10+2 roll number of </p>
	</div>
				
	<div class="ctrlHolder">
		<label for=""><em>*</em>Marks Obtained</label>
		<input name="marks_obtained" id="marks_obtained" value="" data-default-value="e.g. 450" size="35" maxlength="50" type="text" class="textInput required validateInteger"/>
		<p class="formHint">Marks Obtained by <span class="cName" >Candidate</span></p>
	</div>
				  
	<div class="ctrlHolder">
		<label for=""><em>*</em>Total Marks</label>
		<input name="total_marks" id="total_marks" value="" data-default-value="e.g. 500" size="35" maxlength="50" type="text" class="textInput required validateInteger"/>
		<p class="formHint">Total Marks</p>
	</div>
				
	<div class="ctrlHolder">
		<label for=""><em>*</em>Percentage</label>
		<input name="percentage" id="percentage" value="" data-default-value="e.g. 90" size="35" maxlength="50" type="text" class="textInput required validateNumber  validateMax val-100"/>
		<p class="formHint">Percentage obtained by <span class="cName" >Candidate</span> in Physics, Chemistry, Math/Biology</p>
	</div>
				  
	<div class="ctrlHolder">
		<label for=""><em>*</em>PCM/PCB Percentage</label>
		<input name="pcm_percent" id="pcm_percent" value="" data-default-value="e.g. 90" size="35" maxlength="50" type="text" class="textInput required validateNumber  validateMax val-100"/>
		<p class="formHint">Percentage obtained by <span class="cName" >Candidate</span> in Physics, Chemistry, Math/Biology</p>
	</div>
							
	<div class="ctrlHolder">
		<label for=""><em>*</em>Year of Passing</label>
		<input name="passing_year" id="passing_year" value="" data-default-value="e.g. 2007" size="35" maxlength="50" type="text" class="textInput required validateInteger validateMax val-<?php echo date('Y');?>"/>
		<p class="formHint">Year in which <span class="cName" >Candidate</span> passed the 12th</p>
	</div>
				
	<div class="ctrlHolder">
		<label for="">School Rank</label>
		<input name="school_rank" id="school_rank" value="" data-default-value="e.g. 1" size="35" maxlength="50" type="text" class="textInput validateInteger"/>
		<p class="formHint">School rank of  <span class="cName" >Candidate</span></p>
	</div>
				  
	<div class="ctrlHolder">
		<label for=""><em>*</em>Institution</label>
		<input name="institution" id="institution" value="" data-default-value="e.g. Saraswati Senior Secondary School" size="35" maxlength="50" type="text" class="textInput required"/>
		<p class="formHint">Institution in 12th</p>
	</div>
				
	<div class="ctrlHolder">
		<label for=""><em>*</em>City</label>
		<input name="city_name" id="city_name" value="" data-default-value="e.g. Ambala" size="35" maxlength="50" type="text" class="textInput required"/>
		<p class="formHint">City of Institution</p>
    </div>
				  
	<div class="ctrlHolder">
		<label for=""><em>*</em>State</label>
		<input name="state_name" id="state_name" value="" data-default-value="e.g. Haryana" size="35" maxlength="50" type="text" class="textInput required"/>
		<p class="formHint">State of Institution</p>
	</div>
</fieldset>

<fieldset id="btech">
<h3>Btech</h3>
			
	<div class="ctrlHolder">
		<label for=""><em>*</em>Branch</label>
		<input name="discipline_name" id="discipline_name" value=""  data-default-value="e.g. Computer Science" size="35" maxlength="50" type="text" class="textInput required validatePhrase"/>
		<p class="formHint">Branch of  <span class="cName" >Candidate</span>(in full form only)</p>
	</div>
			
	<div class="ctrlHolder">
		<label for=""><em>*</em> Roll no.</label>
		<input name="board_roll_no" id="board_roll_no" value="" data-default-value="e.g. 2310654" size="35" maxlength="20" type="text" class="textInput"/>
		<p class="formHint">  </p>
	</div>
				
	<div class="ctrlHolder">
		<label for=""><em>*</em>Marks Obtained</label>
		<input name="marks_obtained" id="marks_obtained" value="" data-default-value="e.g. 450" size="35" maxlength="50" type="text" class="textInput required validateInteger"/>
		<p class="formHint">Marks Obtained by <span class="cName" >Candidate</span></p>
	</div>
			 	
	<div class="ctrlHolder">
		<label for=""><em>*</em>Total Marks</label>
		<input name="total_marks" id="total_marks" value="" data-default-value="e.g. 500" size="35" maxlength="50" type="text" class="textInput required validateInteger"/>
		<p class="formHint">Total Marks</p>
	</div>
				
	<div class="ctrlHolder">
		<label for=""><em>*</em>Percentage</label>
		<input name="percentage" id="percentage" value="" data-default-value="e.g. 90" size="35" maxlength="50" type="text" class="textInput required validateNumber  validateMax val-100"/>
		<p class="formHint">Percentage obtained by <span class="cName" >Candidate</span> in Physics, Chemistry, Math/Biology</p>
	</div>
				
	<div class="ctrlHolder">
		<label for=""><em>*</em>Year of Passing</label>
		<input name="passing_year" id="passing_year" value="" data-default-value="e.g. 2007" size="35" maxlength="50" type="text" class="textInput required validateInteger"/>
		<p class="formHint">Year in which <span class="cName" >Candidate</span> passed the Btech</p>
	</div>
		        
	<div class="ctrlHolder">
		<label for=""><em>*</em>Institution</label>
		<input name="istitution" id="istitution" value="" data-default-value="e.g. Govt. Polytechnic" size="35" maxlength="50" type="text" class="textInput required"/>
		<p class="formHint">Institution in Btech</p>
	</div>
		        
	<div class="ctrlHolder">
		<label for=""><em>*</em>University</label>
		<input name="university" id="university" value="" data-default-value="e.g. Govt. Polytechnic" size="35" maxlength="50" type="text" class="textInput required"/>
		<p class="formHint">University in Btech</p>
	</div>
		        			
	<div class="ctrlHolder">
		<label for=""><em>*</em>City</label>
		<input name="institution_city" id="institution_city" value="" data-default-value="e.g. Ambala" size="35" maxlength="50" type="text" class="textInput required"/>
		<p class="formHint">City of Institution</p>
	</div>
          
	<div class="ctrlHolder">
		<label for=""><em>*</em>State</label>
		<input name="institution_state" id="institution_state" value="" data-default-value="e.g. Haryana" size="35" maxlength="50" type="text" class="textInput required"/>
		<p class="formHint">State of Institution</p>
	</div>
</fieldset>
					  
<fieldset id="gate">
	<h3>GATE</h3>
	
	<div class="ctrlHolder">
		<label for=""><em>*</em>Roll Number</label>
		<input name="roll_no" id="roll_no" value="" data-default-value="e.g. 450" size="35" maxlength="50" type="text" class="textInput required validateInteger"/>
		<p class="formHint">All India Roll No. of <span class="cName" >Candidate</span></p>
	</div>
					
	<div class="ctrlHolder">
		<label for="doc"><em>*</em>Date of Conduct</label>
		<input name="doc" id="doc" data-default-value="2011-04-04" value=""  size="35" maxlength="50" type="text" readonly="readonly" class="textInput required"/>
		<p class="formHint">1. Select year <br/>2. Select Month<br/>3. Click date of birthday</p>
	</div>
        				
	<div class="ctrlHolder">
		<label for=""><em>*</em>All India Rank (AIR)</label>
		<input name="all_india_rank" id="all_india_rank" value="" data-default-value="e.g. 450" size="35" maxlength="50" type="text" class="textInput required validateInteger"/>
		<p class="formHint">All India Rank of <span class="cName" >Candidate</span></p>
	</div>
					
	<div class="ctrlHolder">
		<label for=""><em>*</em>Gate Score</label>
		<input name="total_score" id="total_score" value="" data-default-value="e.g. 145" size="35" maxlength="50" type="text" class="textInput validateInteger"/>
		<p class="formHint">Marks of gate Form</p>
	</div>
</fieldset>         

   	<div id="submitStatus" style="display:none;padding: 1em;" class="ui-state-highlight ui-corner-all" ></div> 
	<div class="buttonHolder">
		<button type="reset" class="secondaryAction">Reset</button>
		<button type="submit" class="primaryAction">Next</button>
	</div>
</form>

<script>
	var urlBasicInfo = "<?php echo $this->url(array('controller' => 'student', 'action' => 'saveprofile'))?>";
	var is_tenth_checked;
	var is_twelfth_checked;
	var is_diploma_checked;
	var is_btech_checked;
	
	var data = {};
	
	$('fieldset').each(function(){
		$('fieldset').hide();
	});
	$('.buttonHolder').hide();
    $(function(){
        $('form.uniForm').uniform({
          prevent_submit : true
        });
        serverDateObj = $.datepicker.parseDate('dd-mm-yy', $('#datetext').text());
        $("#doc").datepicker({
        	dateFormat: 'yy-mm-dd',
        	changeMonth: true,
			changeYear: true,
			yearRange: '-25:-15',
			onClose : function(dateText, inst) {
				this.focus();
				}
        });
        $("#doc1").datepicker({
        	dateFormat: 'yy-mm-dd',
        	changeMonth: true,
			changeYear: true,
			yearRange: '-25:-15',
			onClose : function(dateText, inst) {
				this.focus();
				}
        });
        $("#doc2").datepicker({
        	dateFormat: 'yy-mm-dd',
        	changeMonth: true,
			changeYear: true,
			yearRange: '-25:-15',
			onClose : function(dateText, inst) {
				this.focus();
				}
        });
    });
    
    function show_div(){
    	is_tenth_checked = $('input:checkbox[name=tenth]').attr('checked');
    	is_twelfth_checked = $('input:checkbox[name=twelfth]').attr('checked');
    	is_diploma_checked = $('input:checkbox[name=diploma]').attr('checked');
    	is_btech_checked = $('input:checkbox[name=btech]').attr('checked');
    	
    	$('#initial_div').hide();
		$('#academic_form').show();
    	if(is_tenth_checked){
        	$('#tenth').show();
    	}
    	if(is_twelfth_checked){
        	$('#twelfth').show();
        	$('#aieee').show();
    	}
    	if(is_diploma_checked){
    		$('#diploma').show();
    		$('#leet').show();
    	}
    	if(is_btech_checked){
    		$('#btech').show();
    		$('#gate').show();
    	}
    	$('.buttonHolder').show();
    	if(!is_tenth_checked & !is_twelfth_checked & !is_diploma_checked & !is_btech_checked){
			alert('Please check the columns');
			$('.buttonHolder').hide();
    	}
    	if(!is_tenth_checked){
			$('#tenth').html('');
    	}
    	if(!is_twelfth_checked){
    		$('#twelfth').html('');
    		$('#aieee').html('');
    	}
    	if(!is_diploma_checked){
    		$('#diploma').html('');
    		$('#leet').html('');
    	}
    	if(!is_btech_checked){
			$('#btech').html('');
			$('#gate').html('');
    	}
    }
    function submit(){
    	if(is_tenth_checked){
        	var tenthData = {};
        	tenthData['qualification_id'] = 1;
    		$('fieldset#tenth :input')
			.not('button,:input[value^="e.g."]')
			.each(function(){ 
				tenthData[this.name] = this.value;
			});
			data['tenth_data'] = tenthData;
    	}
    	if(is_twelfth_checked){
    		var twelfthData = {};
    		twelfthData['qualification_id'] = 2;
    		$('fieldset#twelfth :input')
			.not('button,:input[value^="e.g."]')
			.each(function(){ 
				twelfthData[this.name] = this.value;
			});
    		data['twelfth_data'] = twelfthData;

    		var aieeeData = {};
    		aieeeData['exam_id'] = 1;
    		$('fieldset#aieee :input')
			.not('button,:input[value^="e.g."]')
			.each(function(){ 
				aieeeData[this.name] = this.value;
			});
    		data['aieee_data'] = aieeeData;
    	}
    	if(is_diploma_checked){
    		var diplomaData = {};
    		diplomaData['qualification_id'] = 3;
    		$('fieldset#diploma :input')
			.not('button,:input[value^="e.g."]')
			.each(function(){ 
				diplomaData[this.name] = this.value;
			});
    		data['diploma_data'] = diplomaData;
    		
    		var leetData = {};
    		leetData['exam_id'] = 2;
    		$('fieldset#leet :input')
			.not('button,:input[value^="e.g."]')
			.each(function(){ 
				leetData[this.name] = this.value;
			});
    		data['leet_data'] = leetData;
    	}
    	if(is_btech_checked){
    		var btechData = {};
    		btechData['qualification_id'] = 4;
    		$('fieldset#btech :input')
			.not('button,:input[value^="e.g."]')
			.each(function(){ 
				btechData[this.name] = this.value;
			});
    		data['btech_data'] = btechData;
    		
    		var gateData = {};
    		gateData['exam_id'] = 3;
    		$('fieldset#gate :input')
			.not('button,:input[value^="e.g."]')
			.each(function(){ 
				gateData[this.name] = this.value;
			});
    		data['gate_data'] = gateData;
    	}
    	
		$.ajax({
			url : urlBasicInfo,
			data : {myarray:data},
			success: function(jStatus){
				alert('Your information has been sucessfully submitted...');
            },
            error: function(response) {
				$('#errorBox').text(response.responseText).parent().show();
					console.log(response);
				}
			});
    }
    </script>
    
    <style type="text/css">
    #initial_div{
    	padding:10px;
		background-color:white;
		box-shadow:#e4e4e4 0px 0px 1px 1px;
		width:300px;
	}
	.checkbox_name{
		font-size:14px;
		color:#333;
	}
}
    </style>
<?php
$this->headScript()->appendFile('http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
    
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/smooth.uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/demos/css/demo.css');
?>