<h2>AIEEE Information</h2>
<form id="aieee_form" class="uniForm" action="javascript:submit_aieee_info()">
<fieldset id="aieee">
				
	<div class="ctrlHolder">
		<label for="roll_no"><em>*</em>Roll Number</label>
		<input name="roll_no" id="roll_no" value="" data-default-value="e.g. 450" size="35" maxlength="50" type="text" class="textInput required validateInteger"/>
		<p class="formHint">All India Roll No. of Candidate</p>
	</div>
					
	<div class="ctrlHolder">
		<label for="date">Date of Conduct</label>
		<input name="date" id="date" data-default-value="2011-04-04" value=""  size="35" maxlength="50" type="text" readonly="readonly" class="textInput"/>
		<p class="formHint">1. Select year <br/>2. Select Month<br/>3. Click date of aiee exam</p>
	</div>
        
					
	<div class="ctrlHolder">
		<label for="all_india_rank"><em>*</em>All India Rank (AIR)</label>
		<input name="all_india_rank" id="all_india_rank" value="" data-default-value="e.g. 450" size="35" maxlength="50" type="text" class="textInput required validateInteger"/>
		<p class="formHint">All India Rank of Candidate</p>
	</div>
					
	<div class="ctrlHolder">
		<label for="total_score"><em>*</em>AIEEE Total Score</label>
		<input name="total_score" id="total_score" value="" data-default-value="e.g. 145" size="35" maxlength="50" type="text" class="textInput validateInteger"/>
		<p class="formHint">Marks of AIEEE Form</p>
	</div>
	
	<div id="submitStatus" style="display:none;padding: 1em;" class="ui-state-highlight ui-corner-all" ></div> 
	<div class="buttonHolder">
		<button type="reset" class="secondaryAction">Reset</button>
		<button type="submit" class="primaryAction">Next</button>
	</div>				
</fieldset>
</form>

<script type="text/javascript">
<?php
    if(isset($this->exam_data)){
        foreach ($this->exam_data as $key => $value){
            $divname = $key;
            echo '$("#'.$key.'").val("'.$value.'");';
        }
    }
?>

    $(function(){
    	$('form.uniForm').uniform({
    		prevent_submit : true
    	});

    	$('#topContent').hide();
    });
    serverDateObj = $.datepicker.parseDate('dd-mm-yy', $('#datetext').text());
    $("#date").datepicker({
    	dateFormat: 'yy-mm-dd',
    	changeMonth: true,
		changeYear: true,
		yearRange: '-5:+5',
		onClose : function(dateText, inst) {
			this.focus();
			}
    });

    function submit_aieee_info(){
    	var data = {};
    	var urlSaveAieeeInfo = "<?php echo $this->url(array('controller' => 'student', 'action' => 'saveaieeeinfo'))?>";
    	var qualificationData = {};
    	$('fieldset#aieee :input')
    	.not('button,:input[value^="e.g."]')
    	.each(function(){ 
    		qualificationData[this.name] = this.value;
    	});
    	data['exam_data'] = qualificationData;
    	$.ajax({
    		url : urlSaveAieeeInfo,
    		data : {myarray:data},
    		success: function(jStatus){
        		if(jStatus){
        			alert('Your information has been sucessfully submitted...');
        			window.location = '<?php echo $this->url(array('controller' => 'student', 'action' => 'viewaieeeinfo'))?>';
        		}
            },
            error: function(response) {
    			$('#errorBox').text(response.responseText).parent().show();
    				console.log(response);
    		}
    	});
    }
    	
</script>
<style>
	.uniForm{
		background-color:white;
		padding:10px 10px 10px 25px;
		border:1px solid #b4c1da;
		margin:-5px 0 40px 0;
		box-shadow:#e4e4e4 0px 0px 1px 1px;
		width:auto;
	}
	h2,h3{
		padding:3px 3px 3px 10px;
		background-color:#eceff4;
		border:1px solid #b4c1da;
		font-size:17px;
		font-weight:100;
		margin-top:2px;
	}
	#goback a{
		float:right;
		color:red;
		font-size:14px;
		text-decoration: none;
	}
</style>
<?php
$this->headScript()->appendFile('http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
    
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/smooth.uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/demos/css/demo.css');
?>