<link rel="stylesheet" href="<?php echo 'http://'. CDN_SERVER . '/css/admission.css';?>">

<div id="main">
	<div id="sidebar" style="float:left">
	<ul class="menu">
		<li class="item1">
			<a href="#">Matric</a>
			<ul>
				<li class="subitem1"><a href="/student/editmatricinfo" target="content_frame">Add/Edit</a></li>
				<li class="subitem1"><a href="/student/viewmatricinfo" target="content_frame">View</a></li>
			</ul>
		</li>
		
		<li class="item2">
			<a href="#">Twelfth</a>
			<ul>
				<li class="subitem1"><a href="/student/edittwelfthinfo" target="content_frame">Add/Edit</a></li>
				<li class="subitem1"><a href="/student/viewtwelfthinfo" target="content_frame">View</a></li>
			</ul>
		</li>
		
		<li class="item3">
			<a href="#">AIEEE</a>
			<ul>
				<li class="subitem1"><a href="/student/editaieeeinfo" target="content_frame">Add/Edit</a></li>
				<li class="subitem1"><a href="/student/viewaieeeinfo" target="content_frame">View </a></li>
			</ul>
		</li>
		
		<li class="item4">
			<a href="#">Diploma</a>
			<ul>
				<li class="subitem1"><a href="/student/editdiplomainfo" target="content_frame">Add/Edit</a></li>
				<li class="subitem1"><a href="/student/viewdiplomainfo" target="content_frame">View</a></li>
			</ul>
		</li>
		
		<li class="item5">
			<a href="#">LEET</a>
			<ul>
				<li class="subitem1"><a href="/student/editleetinfo" target="content_frame">Add/Edit</a></li>
				<li class="subitem1"><a href="/student/viewleetinfo" target="content_frame">View </a></li>
			</ul>
		</li>
		
		<li class="item6">
			<a href="#">Btech(Academic)</a>
			<ul>
				<li class="subitem1"><a href="/student/editbtechinfo" target="content_frame">Add/Edit</a></li>
				<li class="subitem1"><a href="/student/viewbtechinfo" target="content_frame">View</a></li>
			</ul>
		</li>
		
		<li class="item6">
			<a href="#">Gate</a>
			<ul>
				<li class="subitem1"><a href="/student/editgateinfo" target="content_frame">Add/Edit</a></li>
				<li class="subitem1"><a href="/student/viewgateinfo" target="content_frame">View</a></li>
			</ul>
		</li>

		<!--<li class="item7">
			<a href="#">Mtech</a>
			<ul>
				<li class="subitem1"><a href="/student/editmtechinfo" target="content_frame">Add/Edit</a></li>
				<li class="subitem1"><a href="/student/viewmtechinfo" target="content_frame">View</a></li>
			</ul>
		</li> -->

	</ul>
	</div>
	<div id="page_content">
		<iframe id="content_frame" name="content_frame" width="100%" height="900" frameborder="0" scrolling="auto" onload="hide_top()"></iframe>
	</div>
</div>

<script type="text/javascript">
	$(function() {
        var menu_ul = $('.menu > li > ul'),
		menu_a  = $('.menu > li > a');

        menu_ul.hide();
    
        menu_a.click(function(e) {
			e.preventDefault();
            if(!$(this).hasClass('active')) {
                menu_a.removeClass('active');
                menu_ul.filter(':visible').slideUp('normal');
                $(this).addClass('active').next().stop(true,true).slideDown('normal');
            } else {
                $(this).removeClass('active');
                $(this).next().stop(true,true).slideUp('normal');
            }
        });
    });
	function hide_top()
	{
		$('iframe#content_frame').contents().find('div#topContent').hide();
	}
</script>

<style type="text/css">
	#page_content{
    	float:left;
		width:65%;
    }
</style>