<?php
    $matric = $this->matric;
    
    if(Zend_Auth::getInstance()->hasIdentity()){
		$authInfo = Zend_Auth::getInstance()->getStorage()->read();
		$usertype=$authInfo['userType'];
	}
?>
<div  class="ui-state-hover"><center><H3>Matric Details</H3></center></div>
<div id="Matric Details">
    <table id="corner" cellspacing="10" cellpadding="10">
    <?php
        if($matric == null){ 
            echo '<h4>No information has been added yet.</h4>';
        }
        else
        {
            echo '<tr><td>Roll Number</td><td>'.$matric['board_roll_no'].'</td></tr>';
            echo '<tr><td>Marks Obtained</td><td>'.$matric['marks_obtained'].'</td></tr>';
            echo '<tr><td>Total Marks</td><td>'.$matric['total_marks'].'</td></tr>';
            echo '<tr><td>Percentage</td><td>'.$matric['percentage'].'</td></tr>';
            echo '<tr><td>Passing Year</td><td>'.$matric['passing_year'].'</td></tr>';
            echo '<tr><td>Board</td><td>'.$matric['board'].'</td></tr>';
            echo '<tr><td>Institute/School Name</td><td>'.$matric['institution'].'</td></tr>';
            echo '<tr><td>City</td><td>'.$matric['city_name'].'</td></tr>';
            echo '<tr><td>State</td><td>'.$matric['state_name'].'</td></tr>';
            echo '<tr><td>School Rank</td><td>'.$matric['school_rank'].'</td></tr>';
        }
    ?>
        	
	</table>
</div>

<?php if($usertype == 'STU'){?>
<input type="button" class="ui-button" value="Edit Information" onclick="window.location.replace('/student/editmatricinfo');">
<?php }?>

<script type="text/javascript">
	$(function(){
		$('div#topContent').hide();
	});
</script>

<style type="text/css">
	table {
      	border-color: #c20f2e;
		width:97%;
	}
	tr{
		border-bottom:1px dashed #999;
	}
	#corner
	{
		font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
		font-size: 14px;
		margin: 15px;
		text-align: left;
		border-collapse: collapse;
	}
	#edit_btn {
		width:48%;
		float:left;
	}
	#goback_btn { 
		width:48%;
		float:right;
	}
</style>