<?php 
    $subData = $this->response['subject_data'];
    $dmcData = $this->response['dmc_data'];
    $dmcInfoData = $this->response['dmc_info_data'];
    $dmc_info_id =array_keys($dmcInfoData);
    
    if(Zend_Auth::getInstance()->hasIdentity()){
		$authInfo = Zend_Auth::getInstance()->getStorage()->read();
		$usertype=$authInfo['userType'];
	}
	
	$result_type = array(
	    1 => 'Regular Pass',
	    2 => 'Regular Fail',
	    3 => 'Reevaluation Pass',
	    4 => 'Reevaluation Fail',
	    5 => 'Reappear Pass',
	    6 => 'Reappear Fail'
	)
?>

<div class="ui-state-hover"><center><H3>DMC Details</H3></center></div>

<ul id="dmc_info" class="ui-widget-content ui-corner-all">
	
    <li><span class="dmc_info_index">Serial Number : </span>
    <span class="dmc_info_value"><?php echo $dmcInfoData['dmc_id'] ?></span></li>

    <!--<span class="dmc_info_index">Class id : </span>
    <span class="dmc_info_value"><?php echo $dmcInfoData['class_id'] ?></span>
    <br>
    --><li><span class="dmc_info_index">Result Type : </span>
    <span class="dmc_info_value"><?php echo $result_type[$dmcInfoData['result_type_id']] ?></span></li>

    <li><span class="dmc_info_index">Is considered : </span>
    <span class="dmc_info_value"><?php echo $dmcInfoData['is_considered']?'Yes':'No' ?></span></li>

    <li><span class="dmc_info_index">Examination : </span>
    <span class="dmc_info_value"><?php echo $dmcInfoData['examination'] ?></span></li>

    <li><span class="dmc_info_index">Custody date : </span>
    <span class="dmc_info_value"><?php echo $dmcInfoData['custody_date'] ?></span></li>

    <li><span class="dmc_info_index">Is granted : </span>
    <span class="dmc_info_value"><?php echo $dmcInfoData['is_granted']?'Yes':'No' ?></span></li>

    <li><span class="dmc_info_index">Grant date : </span>
    <span class="dmc_info_value"><?php echo $dmcInfoData['grant_date']?'Yes':'No' ?></span></li>

    <li><span class="dmc_info_index">Is copied : </span>
    <span class="dmc_info_value"><?php echo $dmcInfoData['is_copied']?'Yes':'No' ?></span></li>

    <li><span class="dmc_info_index">Dispatch date : </span>
    <span class="dmc_info_value"><?php echo $dmcInfoData['dispatch_date'] ?></span></li>

    <li><span class="dmc_info_index">Marks obtained : </span>
    <span class="dmc_info_value"><?php echo $dmcInfoData['marks_obtained'] ?></span></li>

    <li><span class="dmc_info_index">Total marks : </span>
    <span class="dmc_info_value"><?php echo $dmcInfoData['total_marks'] ?></span></li>

    <li><span class="dmc_info_index">Scaled marks : </span>
    <span class="dmc_info_value"><?php echo $dmcInfoData['scaled_marks'] ?></span></li>

    <li><span class="dmc_info_index">Percentage : </span>
    <span class="dmc_info_value"><?php echo $dmcInfoData['percentage'] ?></span></li>
</ul>
<?php 
/*        foreach ($dmcInfoData as $dmc_property => $val){
            if($dmc_property != 'result_type_id'){
                $dmc_property_modified = ucfirst(str_replace('_',' ',$dmc_property));
                echo '<span class="dmc_info_index">'.$dmc_property_modified.'</span> <span class="dmc_info_value">'.$val.'</span><br>';
            }
            else {
                switch ($val){
                    case '1':
                        echo '<span class="dmc_info_index">Result Type</span> <span class="dmc_info_value">Regular Pass</span><br>';
                        break;
                    case '2':
                        echo '<span class="dmc_info_index">Result Type</span> <span class="dmc_info_value">Regular Fail</span><br>';
                        break;
                    case '3':
                        echo '<span class="dmc_info_index">Result Type</span> <span class="dmc_info_value">Re-evaluation Pass</span><br>';
                        break;
                    case '4':
                        echo '<span class="dmc_info_index">Result Type</span> <span class="dmc_info_value">Re-evaluation Fail</span><br>';
                        break;
                    case '5':
                        echo '<span class="dmc_info_index">Result Type</span> <span class="dmc_info_value">Re-appear Pass</span><br>';
                        break;
                    case '6':
                        echo '<span class="dmc_info_index">Result Type</span> <span class="dmc_info_value">Re-appear Fail</span><br>';
                        break;
                    default:
                        echo '<span class="dmc_info_index">Result Type</span> <span class="dmc_info_value">Regular Pass</span><br>';
                }
            }
        }*/
?>


<table id="table-design" cellpadding="3" cellspacing="3">
<?php 
    $i = 1;
    $j = 1;
    echo '<tr>';
    foreach ($subData as $subject_id => $subject_data){
        foreach ($subject_data as $subject_property => $value){
            if($i == 1){
                echo '<th>'.ucfirst($subject_property).'</th>';
            }
        }
        $i = 0;
        if(isset($dmcData[$subject_id])){
            foreach ($dmcData[$subject_id] as $subject_property_name => $val){
                if($j == 1){
                    echo '<th>'.ucfirst($subject_property_name).'</th>';
                }
            }
        }
        $j = 0;
    }
    echo '</tr>';
?>
<?php
    foreach ($subData as $subject_id => $subject_data){
        echo '<tr>';
        foreach ($subject_data as $subject_property => $value){
            echo '<td>'.$value.'</td>';
        }
        if(isset($dmcData[$subject_id])){
            foreach ($dmcData[$subject_id] as $subject_property_name => $val){
                echo '<td>'.$val.'</td>';
            }
            echo '</tr>';
        }
    }
?>
</table>

<?php if($usertype == 'STU'){?>
<input type="button" class="ui-button" value="Edit Information" onclick="window.location.replace('/student/editdmc?dmc_info_id=<?php echo $_GET['dmc_info_id'];?>');">
<?php }?>

<script type="text/javascript">
	$(function(){
		$('div#topContent').hide();
	});
</script>

<style>
    #table-design {
    	border: 1px solid #DFDFDF;
    	background-color: #F9F9F9;
    	-moz-border-radius: 3px;
    	-webkit-border-radius: 3px;
    	border-radius: 3px;
    	font-family: Arial,"Bitstream Vera Sans",Helvetica,Verdana,sans-serif;
    	color: #333;
		float:left;
		margin: 20px 0 0 0;
    }
    #table-design td, #table-design th {
    	border-top-color: white;
    	border-bottom: 1px solid #DFDFDF;
    	color: #313131;
    }
    #table-design th {
    	text-shadow: rgba(255, 255, 255, 0.796875) 0px 1px 0px;
    	font-family: Georgia,"Times New Roman","Bitstream Charter",Times,serif;
    	font-weight: normal;
    	padding: 7px 7px 8px;
    	text-align: left;
    	line-height: 1.3em;
    	font-size: 14px;
    	background-color:#D2D2D2;
    }
    #table-design td {
    	font-size: 12px;
    	padding: 4px 7px 2px;
    }

	ul{
		margin:20px 0 0 0;
		padding:5px 10px 5px 10px;
		background: none;
		list-style: none;
	}
	
	.dmc_info_index{
		font-size: 14px;
		color:red;
	}
	.dmc_info_value{
		font-size: 14px;
	}
	input{
		margin-top:10px;
	}
</style>