<form action="javascript:submit();" class="uniForm">
<h2>Sign Up  </h2>
        
        <fieldset>
                  
        <div class="ctrlHolder">
            <label for="login_id"><em>*</em>Desired Login Id</label>
            <input name="login_id" id="login_id" value="" data-default-value="amit_kumar" size="35" maxlength="50" type="text" class="textInput required"/>
            <p class="formHint">Enter the desired login id</p>
          </div>
        <div class="ctrlHolder">
            <label for="sec_passwd"><em>*</em>Password</label>
            <input name="sec_passwd" id="sec_passwd" value=""  size="35" maxlength="50" type="password" class="textInput required validateAlphaNum"/>
            <p class="formHint">Enter the password not less than six characters in length </p>
          </div>
          <div class="ctrlHolder">
				<label for="sec_passwd_confirm">Confirm Password</label>
				<input name="sec_passwd_confirm" id="sec_passwd_confirm" data-default-value="" value=""  size="35" maxlength="50" type="password" class="required textInput validateSameAs sec_passwd"/>
				<p class="formHint"></p>
		  </div>
          
          <div class="ctrlHolder">
            <label for=""><em>*</em>User Type</label>
             <select id="user_type_id" name="user_type_id" class="selectInput required">
          		 <option value="STU">Student</option>
          		<option value="STAFF">Staff</option>
          	  </select>
            <p class="formHint">Select the type of user</p>
          </div>
          
          <div class="ctrlHolder">
            <label for=""><em>*</em>Deaprtment</label>
             <select id="department_id" name="department_id" class="selectInput required">
          		<option value="CSE">Computer Science and Engineeing</option>
          		<option value="BT">Biotechnology</option>
          		<option value="ECE">Electronics and Communication Engineering</option>
          		<option value="ME">Mechanical Engineering</option>
          		<option value="MGMT">Management</option>
          	 </select>
            <p class="formHint">Select the department</p>
          </div>
          
          
      </fieldset>
      <div id="submitStatus" style="display:none;padding: 1em;" class="ui-state-highlight ui-corner-all" ></div>
      
      	<div class="buttonHolder">
            <button type="reset" class="secondaryAction">Reset</button>
            <button type="submit" class="primaryAction">Next</button>
    	</div>
</form>
<script>	
var urlSaveRegistrationInfo = "<?php echo $this->url(array('controller' => 'authenticate', 'action' => 'saveregistrationinfo'))?>";
$(function(){
    $('form.uniForm').uniform({
      prevent_submit : true
    });
  });

function submit() {
    $.ajax({
        url : urlSaveRegistrationInfo,
        data : getValues(),
        success: function(jStatus){
            
        },
            error: function(response) {
				$('#errorBox').text(response.responseText).parent().show();
				console.log(response);
			}
		});
  }
function getValues(){
	var formData = {};
	$('fieldset :input')
	.not('button,#sec_passwd_confirm,:input[value^="e.g."]')
	.each(function(){ 
		formData[this.name] = this.value;
	});
	return formData;
}
 </script>
 <?php
$this->headScript()->appendFile('http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
    
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/smooth.uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/demos/css/demo.css');
?>