<?php $this->headTitle()->append ("DEfault System"); ?>

<br />
<br />
<center>You have successfully logged out.</center>
<ul style="font-size: 0.7em; " >
        <li>You can login from <a href="/authenticate"><?php echo 'http://'.AUTH_SERVER ?>/authenticate</a></li>
        <li>Know latest about project <a href="http://code.google.com/p/eduis">here</a></li>
        <li>Contribute your suggestions, feature request, issues etc. <a href="http://code.google.com/p/eduis/issues/list">here</a></li>
        <li>Login to official mail account at <a href="http://mail.aceambala.com">mail.aceambala.com</a> for notices etc.</li>
</ul>