
<!--[if lte ie 7]>
      <style basis="text/css" media="screen">
        /* Move these to your IE6/7 specific stylesheet if possible */
        .uniForm, .uniForm fieldset, .uniForm .ctrlHolder, .uniForm .formHint, .uniForm .buttonHolder, .uniForm .ctrlHolder ul{ zoom:1; }
      </style>
    <![endif]-->
<div id="progressbar"></div>
<form action="javascript:submit();" class="uniForm">
<h2><?php
$stepNo = $this->stepNo;?> Information:</h2>
<hr />
<fieldset>
<h3>Enroll</h3>
<div class="ctrlHolder">
          <p class="label"><em>*</em>Admission Basis</p>
          <ul class="blockLabels">
            <li><label for=""><input name="admBasis" type="radio" value="aieee" title="AIEEE" class="required">AIEEE</label></li>
            <li><label for=""><input  name="admBasis" type="radio" value="twelfth" title="10+2" class="required">10+2</label></li>
            <li><label for=""><input  name="admBasis" type="radio" value="leet" title="LEET" class="required">LEET</label></li>
          </ul>
          <p class="formHint">Basis of Addmission</p>
        </div>

<br />
<div class="buttonHolder">
<button basis="reset" class="secondaryAction">Reset the form</button>
<button basis="submit" class="primaryAction" >Proceed</button>
</div>

</fieldset>
</form>
<script>
	/**@todo
	*apply validate roll number
	**/
	var urlBasicInfo  = "<?php echo $this->url(array('controller' => 'profile', 'action' => 'set'.$this->steps[$stepNo]))?>";
	
	var basis;
	
    $(function(){
        $('form.uniForm').uniform({
            prevent_submit : true
        });

        $('input[name=admBasis]').change(function(){
            basis = this.value;
        	$('.admBasis').text(' of '+this.title);
        });
      });

    function submit(){
   	 
    	$.ajax({
        	url: urlBasicInfo,
            data : {
          
    		admission_basis : basis
        	},
            success: function(jStatus)
            {
        		window.location = "/profile/setadmissionbasis ";
    	    }
           ,
            error: function(response) {
              	  $('#errorBox').text(response.responseText).parent().show();
                    console.log(response);
                    }
                });
    }
    
      
    
</script>
<?php
$this->headScript()->appendFile(
'http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER . '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER . '/plugins/uni-form/css/smooth.uni-form.css');
?>