<div class="gridstyle">
<table id="tblgrid" class="scroll"></table>
<div id="gridpager" class="scroll" style="text-align: center;"></div>
</div>
<div id="errorBox"><b>ErrorResponse:</b><span id="rsperror"
	style="color: red"></span></div>
<div id="formDiv"></div>
<script type="text/javascript">

$(function(){
    var gridTable = "#tblgrid";
    var gridPager = "#gridpager";
    var urlFillGrid = "<?=$this->url(array('module' => $this->module, 'controller' => $this->controller, 'action' => 'fillgrid'), 'default', true)?>";
    var urlCRUD = "<?=$this->url(array('module' => $this->module, 'controller' => $this->controller, 'action' => 'crud'), 'default', true)?>";
    $(gridTable).jqGrid(
            {
                url : urlFillGrid,
                colNames:['Weekday Number','Weekday Name'], 
                colModel:[  {name:'weekday_number',
                                index:'weekday_number',
                                editable:true,
                                edittype: 'select', 
                                editoptions:{
                                    value : {'':'Select One', 
                                             '1' : '1',
                                             '2' : '2',
                                             '3' : '3',
                                             '4' : '4',
                                             '5' : '5',
                                             '6' : '6',
                                             '7' : '7'}                   
                                },
                                editrules:{required:true} 
                            },
                            {name:'weekday_name',
                                index:'weekday_name',
                                editable:true,
                                edittype: 'select', 
                                editoptions:{
                                    value : {'':'Select One', 
                                             'Monday' : 'Monday',
                                             'Tuesday' : 'Tuesday',
                                             'Wednesday' : 'Wednesday',
                                             'Thursday' : 'Thursday',
                                             'Friday' : 'Friday',
                                             'Saturday' : 'Saturday',
                                             'Sunday' : 'Sunday'}                   
                                }
                            }
                        ], 
                caption: 'Weekdays',
                sortname: 'weekday_number',
                pager: gridPager, 
                editurl:urlCRUD
        });

    $(gridTable).jqGrid('navGrid', gridPager, {
        add : true,
        edit : true,
        view : false,
        search : false,
        refresh : false
    }, // options
            {
                width : 400,
                savekey : [ true, 13 ],
                navkeys : [ true, 38, 40 ],
                jqModal : false,
                closeOnEscape : true
            }, // edit options
            {
                width : 400,
                savekey : [ true, 13 ],
                navkeys : [ true, 38, 40 ],
                jqModal : false,
                closeOnEscape : true
            }, // add options
            {
                reloadAfterSubmit : false,
                jqModal : false,
                closeOnEscape : true
            } // del options
         );

    addPager(gridTable, gridPager); 
});
</script>