<script type="text/javascript">
$(function(){
	$("#tblgrid").jqGrid(
			{
			url : "<?=$this->url ( array ('controller' => 'room', 'action' => 'fillroomgrid' ), 'default', true )?>",
			datatype: "json", height: 130, 
			colNames:['Block', 'Room','Room type', 'Capacity', 'Remark'],
			colModel:[ {name:'block', index:'block asc, room'},
					   {name:'room', index:'room'},
			           {name:'roomtype', index:'roomtype'},
			           {name:'capacity', index:'capacity'},
			           {name:'remark', index:'remark'}
					   ],
			multiselect: false,
			caption: "Room Information",
			pager: jQuery('#pager'),
			viewrecords: true, 
			autowidth: true
					 }).navGrid('#pager',{edit:false,add:false,del:false});
	

	var baseurl="<?=$this->url ( array ('controller' => 'room', 'action' => 'fillblock' ), 'default', true )?>";
	$.get(baseurl,function(data){
		$('#cmbblock').html(data);		
		});


	
	var baseurl="<?=$this->url ( array ('controller' => 'room', 'action' => 'fillroomtype' ), 'default', true )?>";
	$.get(baseurl,function(data){
		$('#cmbroomtype').html(data);		
		});
	
	
	/////////////

	
	$('#btnadd').click(function(){
		var block = $('#cmbblock').val();
		var room = $('#txtroom').val();
		var roomtype = $('#cmbroomtype').val();
		var capacity = $('#txtcapacity').val();
		var remark = $('#txtremark').val();
		
		
		var baseurl= "<?=$this->url ( array ('controller' => 'room', 'action' => 'insertroom' ), 'default', true )?>";

		$.get(baseurl,
				{block : block, room : room , roomtype : roomtype, capacity : capacity, remark : remark},
				function(data){
					var datarow = {block : block, room : room , roomtype : roomtype, capacity : capacity, remark : remark};
					var su = $("#tblgrid").addRowData(block,datarow);
					if(su) alert("Room added Successfully");
					else alert(data);
				});
	
	});

	
});

</script>
<form id="myform" action="">
<table id="tblcmponents" id="tblcmponents" cellpadding="6" border="0">
	<tr>
		<td><?=$this->formLabel ( 'cmbblock', 'Block' )?></td>
		<td><?=$this->formSelect ( 'cmbblock' )?></td>
	</tr>
	<tr>
		<td><?=$this->formLabel ( 'txtroom', 'Room Number' )?></td>
		<td><?=$this->formText ( 'txtroom' )?></td>
	</tr>
	<tr>
		<td><?=$this->formLabel ( 'cmbroomtype', 'Room Type' )?></td>
		<td><?=$this->formSelect ( 'cmbroomtype' )?></td>
	</tr>
	<tr>
		<td><?=$this->formLabel ( 'txtcapacity', 'Capacity' )?></td>
		<td><?=$this->formText ( 'txtcapacity' )?></td>
	</tr>
	<tr>
		<td><?=$this->formLabel ( 'txtremark', 'Remark' )?></td>
		<td><?=$this->formText ( 'txtremark' )?></td>
	</tr>

	<tr>
		<td><?=$this->formButton ( 'btnadd', 'Add' )?></td>
		<td><?=$this->formReset ( 'btnreset', 'Reset' )?></td>
	</tr>
</table>
</form>
<div class="gridstyle">
<table id="tblgrid" class="scroll"></table>
<div id="pager" class="scroll" style="text-align: center;"></div>
</div>
