<tr>
	<td>18</td>
</tr>
<tr>
	<td><span id="heading">TEST SECTION ID</span><span id="content">18</span></td>
</tr>
<tr>
	<td><span id="heading">SECTION MARKS</span><span id="content">89</span></td>
</tr>
<tr>
	<td><span id="heading">SECTION PERCENTILE</span><span id="content">89</span></td>
</tr>
<tr>
	<td><span id="heading">TEST SECTION NAME</span><span id="content">verbal</span></td>
</tr>
<tr>
	<td>19</td>
</tr>
<tr>
	<td><span id="heading">TEST SECTION ID</span><span id="content">19</span></td>
</tr>
<tr>
	<td><span id="heading">SECTION MARKS</span><span id="content">78</span></td>
</tr>
<tr>
	<td><span id="heading">SECTION PERCENTILE</span><span id="content">78</span></td>
</tr>
<tr>
	<td><span id="heading">TEST SECTION NAME</span><span id="content">reasoning</span></td>
</tr>
<tr>
	<td>20</td>
</tr>
<tr>
	<td><span id="heading">TEST SECTION ID</span><span id="content">20</span></td>
</tr>
<tr>
	<td><span id="heading">SECTION MARKS</span><span id="content">66</span></td>
</tr>
<tr>
	<td><span id="heading">SECTION PERCENTILE</span><span id="content">66</span></td>
</tr>
<tr>
	<td><span id="heading">TEST SECTION NAME</span><span id="content">quantitative</span></td>
</tr>
<tr>
	<td>21</td>
</tr>
<tr>
	<td><span id="heading">TEST SECTION ID</span><span id="content">21</span></td>
</tr>
<tr>
	<td><span id="heading">SECTION MARKS</span><span id="content">67</span></td>
</tr>
<tr>
	<td><span id="heading">SECTION PERCENTILE</span><span id="content">67</span></td>
</tr>
<tr>
	<td><span id="heading">TEST SECTION NAME</span><span id="content">verbal</span></td>
</tr>