<h2>Student Placement Record</h2>
<form id="student_placement" class="uniForm" action="javascript:check_values()">
	<fieldset id="placement_record">
		
		<div class="ctrlHolder">
			<label for="company_id"><em>*</em>Company Name</label>
			<select id="company_id" name="company_id" class="selectInput required">
			
			</select>
			<p class="formHint">Name of the company conducting the recruitment</p>
		</div>
				
		<div class="ctrlHolder">
			<label for="company_job_id"><em>*</em>Job</label>
			<select id="company_job_id" name="company_job_id" class="selectInput required">
			
			</select>
			<p class="formHint">Select the job</p>
		</div>
		
		<div class="ctrlHolder">
			<label for="package"><em>*</em>Package offered for the job</label>
			<input name="package" id="package" value="" data-default-value="e.g. 300000" size="35" maxlength="50" type="text" class="textInput required validateInteger"/>
			<p class="formHint">Package offered for the job</p>
		</div>
		
		<div class="ctrlHolder">
			<label for="drive_location"><em>*</em>Location of the Placement drive</label>
			<input name="drive_location" id="drive_location" value="" data-default-value="e.g. MM University, Mullana" size="35" maxlength="50" type="text" class="textInput required"/>
			<p class="formHint">Place where the company visited</p>
		</div>
		
		<div class="ctrlHolder">
			<label for="date_of_selection"><em>*</em>Date of Selection</label>
			<input name="date_of_selection" id="date_of_selection" data-default-value="2011-04-04" value=""  size="35" maxlength="50" type="text" readonly="readonly" class="textInput required"/>
			<p class="formHint">1. Select year <br/>2. Select Month<br/>3. Click date of start</p>
		</div>
		
		<div class="ctrlHolder">
			<label for="method"><em>*</em>Select</label>
			<select id="method" name="method" class="selectInput required">
				<option value="appeared">Appeared</option>
				<option value="selected">Selected</option>
				<option value="registered">Registered</option>
			</select>
			<p class="formHint">Select</p>
		</div>
		</fieldset>
		
		<fieldset>
		
		<div class="ctrlHolder" id="type">
			<p class="label"><em>*</em>Select how to you want to enter students</p>
			<ul class="blockLabels alternate">
				<li><label for="gender"><input name="type" type="radio" value="by_roll_no" title="Roll Numbers" onchange="javascript:show_option('roll_no')">Specify roll number(s) </label></li>
				<li><label for=""><input name="type" type="radio" value="by_range" title="range" onchange="javascript:show_option('range')">Specify range </label></li>
			</ul>
			<p class="formHint">Select how you want to enter the roll numbers of students</p>
        </div>
		
		<div id="submitStatus" style="display:none;padding: 1em;" class="ui-state-highlight ui-corner-all" ></div> 
		<div class="buttonHolder">
			<button type="reset" class="secondaryAction">Reset</button>
			<button type="submit" class="primaryAction">Next</button>
		</div>				
	</fieldset>
</form>

<script type="text/javascript">

    $(function(){
    	$('#topContent').hide();

    	var urlfetchcompanies = "<?php echo $this->url(array('controller' => 'career', 'action' => 'fetchcompanies'))?>";
    	$.ajax({
        	url : urlfetchcompanies,
        	dataType : 'json',
        	async : false,
        	data : {format : 'json'},
        	success : function(jStatus){
				if(jStatus == false)
				{
					
				}
				else
				{
					var html = '<option value="">Please select company</option>';
					
					$.each(jStatus,function(company_id,company_name){
						html += '<option value='+company_id+'>'+company_name+'</option>';
					});
					
					$('select#company_id').html(html);
				}
        	},
        	error : function(response){

        	}
        });
        
    	$('form.uniForm').uniform({
    		prevent_submit : true
    	});

    	$('select#company_id').change(function(){
			if($('select#company_id').val() != '')
			{
				var urlfetchjobs = "<?php echo $this->url(array('controller' => 'career', 'action' => 'fetchcompanyjobs'))?>";
		    	$.ajax({
		        	url : urlfetchjobs,
		        	dataType : 'json',
		        	async : false,
		        	data : {
						company_id : $('select#company_id').val(),
			        	format : 'json'
					},
		        	success : function(jStatus){
						if(jStatus == false)
						{
							alert("No job has been registered with this company. Click on Add Job option in the sidebar");
						}
						else
						{
							var html = '<option value="">Please select job</option>';
							
							$.each(jStatus,function(job_id,job_details){
								html += '<option value='+job_id+'>'+job_details['job']+' ('+job_details['date_of_announcement']+')'+'</option>';
							});
							
							$('select#company_job_id').html(html);
						}
		        	},
		        	error : function(response){

		        	}
		        });
			}
			else
			{
			}
    	});
    });
    
    serverDateObj = $.datepicker.parseDate('dd-mm-yy', $('#datetext').text());
    $("#date_of_selection").datepicker({
    	dateFormat: 'yy-mm-dd',
    	changeMonth: true,
		changeYear: true,
		yearRange: '-5:+5',
		onClose : function(dateText, inst) {
			this.focus();
			}
    });

    function submit_placement_record(data){
        var final_data = {};
    	var student_job_info = {};
    	var urlSaveCompanyInfo = "<?php echo $this->url(array('controller' => 'career', 'action' => 'saverecord'))?>";

		$('#placement_record :input')
		.not('button,#method,#company_id')
		.each(function(){
			student_job_info[this.name] = this.value;
		});
		student_job_info['appeared'] = 0;
		student_job_info['registered'] = 0;
		student_job_info['selected'] = 0;

		if($('#method').val() == 'appeared')
			student_job_info['appeared'] = 1;
		if($('#method').val() == 'registered')
			student_job_info['registered'] = 1;
		if($('#method').val() == 'selected')
			student_job_info['selected'] = 1;
		
    	final_data['student_job_info'] = student_job_info;
    	final_data['member_ids'] = data;
    	
    	$.ajax({
    		url : urlSaveCompanyInfo,
    		data : {myarray:final_data},
    		success: function(jStatus){
        		if(jStatus){
            		alert(jStatus);
        		}
            },
            error: function(response) {
    			$('#errorBox').text(response.responseText).parent().show();
    				console.log(response);
    		}
    	});
    }

    function check_values() {
    	var data = {};
    	//data['myarray'] = {};
    	if($('input[value="by_roll_no"]').is(':checked'))
    	{
    		var roll_no_string = $('#roll_numbers').val();
    		data['roll_numbers'] = roll_no_string.replace(/ /g,"").split(',');
    		data['range_specified'] = false;
    		data['format'] = 'jsonp';
    		fetchmemberids(data);
    	}
    	else if($('input[value="by_range"]').is(':checked'))
    	{
    		var upper = $('#upper_range').val();
    		var lower = $('#lower_range').val();

    		if(upper < lower)
    			alert("The value in the 'To' field should be greater than the value in 'From' field.");
    		else
    		{
    			var excluded_string = $('#excluded').val();
    			if($('#excluded').val() != '')
    				data['excluded'] = excluded_string.replace(/ /g,"").split(',');
    			
    			data['roll_numbers'] = {'upper' : upper, 'lower' : lower};
    			data['range_specified'] = true;
    			fetchmemberids(data);
    		}
    	}
    	else
    		alert("Please fill all the columns");
    }

	function fetchmemberids(data)
	{
		var urlfetchmemberids = "http://core.aceambala.com/search/fetchmemberid";
		$.ajax({
			url : urlfetchmemberids,
			dataType : 'jsonp',
			data : {myarray:data,format:'jsonp'},
			async : false,
			success : function(jStatus){
				if(jStatus != false)
				{
					var member_ids = new Array();
					$.each(jStatus,function(roll_number,member_id){
						member_ids.push(member_id);
					});
					submit_placement_record(member_ids);
				}
			},
			error : function(response){

			}
		});
	}
    
    function show_option(method)
    {
    	if(method == 'roll_no')
    	{
    		var html = '<div class="ctrlHolder" id="roll_numbers_div">'+
    				'<label for="roll_numbers">Enter Roll Numbers</label>'+
    				'<input name="roll_numbers" id="roll_numbers" value="" data-default-value="2308017,2308019,2308060" size="35" maxlength="100" type="text" class="textInput required"/>'+
    				'<p class="formHint">Enter roll numbers sepreated by commas without any space. Please double check the values before submitting.</p>'+
    				'</div>';

    		$('#type').after(html);
    		$('#range_div,#excluded_div').remove();
    	}
    	else
    	{
    		var html = '<div class="ctrlHolder noLabel" id="range_div">'+
    		'<ul class="alternate">'+
               	'<li><label for="upper_range"><em>*</em>From</label>'+
             		'<input name="lower_range" id="lower_range" data-default-value="e.g. 2308001" value="" size="10" maxlength="50" type="text" class="textInput required validateNumber"/></li>'+
               	'<li><label for="lower_range"> To</label>'+
    				'<input name="upper_range" id="upper_range" data-default-value="e.g. 2308060" value=""  size="10" maxlength="50" type="text" class="textInput required validateNumber"/></li>'+
    		'</ul>'+
    		'<p class="formHint">Enter roll numbers range. Please double check the values before submitting.</p>'+
    	'</div>'+

    	'<div class="ctrlHolder" id="excluded_div">'+
    		'<label for="excluded">Enter Excluded Roll Numbers</label>'+
    		'<input name="excluded" id="excluded" value="" data-default-value="2308017,2308019,2308060" size="35" maxlength="100" type="text" class="textInput"/>'+
    		'<p class="formHint">Enter roll numbers to be excluded sepreated by commas without any space. Please double check the values before submitting.</p>'+
    	'</div>';

    		$('#type').after(html);
    		$('#roll_numbers_div').remove();
    	}
    }
    	
</script>
<style>
	.uniForm{
		background-color:white;
		padding:10px 10px 10px 25px;
		border:1px solid #b4c1da;
		margin:-5px 0 40px 0;
		box-shadow:#e4e4e4 0px 0px 1px 1px;
		width:auto;
	}
	h2,h3{
		padding:3px 3px 3px 10px;
		background-color:#eceff4;
		border:1px solid #b4c1da;
		font-size:17px;
		font-weight:100;
		margin-top:2px;
	}
	#goback a{
		float:right;
		color:red;
		font-size:14px;
		text-decoration: none;
	}
</style>
<?php
$this->headScript()->appendFile('http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
    
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/smooth.uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/demos/css/demo.css');
?>