<?php 
	$company_info = $this->company_info;
?>

<h2>Student Placement Record</h2>
<form id="student_placement" class="uniForm" action="javascript:submit_company_info()">
<fieldset id="company_info">

	<div class="ctrlHolder">
		<label for="company_name"><em>*</em>Company Name</label>
		<input name="company_name" id="company_name" value="<?php echo $company_info['company_name']?>" data-default-value="e.g. Infosys Ltd." size="35" maxlength="50" type="text" class="textInput required"/>
		<p class="formHint">Name of the company</p>
	</div>
	
	<div class="ctrlHolder">
		<label for="field"><em>*</em>Company Field</label>
		<select id="field" name="field" class="selectInput required">
			<option value="">Select the field</option>
			<option value="1">Accounting/Finance</option>
			<option value="2">Advertising/PR/MR/Events</option>
			<option value="3">Agriculture/Dairy</option>
			<option value="4">Animation</option>
			<option value="5">Architecture/Interior Designing</option>
			<option value="6">Auto/Auto Ancillary</option>
			<option value="7">Aviation / Aerospace Firms</option>
			<option value="8">Banking/Financial Services/Broking</option>
			<option value="9">BPO/ITES</option>
			<option value="10">Brewery / Distillery</option>
			<option value="11">Ceramics /Sanitary ware</option>
			<option value="12">Chemicals/PetroChemical/Plastic/Rubber</option>
			<option value="13">Construction/Engineering/Cement/Metals</option>
			<option value="14">Consumer Durables</option>
			<option value="15">Courier/Transportation/Freight</option>
			<option value="16">Defence/Government</option>
			<option value="17">Education/Teaching/Training</option>
			<option value="18">Electricals / Switchgears</option>
			<option value="19">Export/Import</option>
			<option value="20">Facility Management</option>
			<option value="21">Fertilizers/Pesticides</option>
			<option value="22">FMCG/Foods/Beverage</option>
			<option value="23">Food Processing</option>
			<option value="24">Fresher/Trainee</option>
			<option value="25">Gems and Jewellery</option>
			<option value="26">Glass</option>
			<option value="27">Heat Ventilation Air Conditioning</option>
			<option value="28">Hotels/Restaurants/Airlines/Travel</option>
			<option value="29">Industrial Products/Heavy Machinery</option>
			<option value="30">Insurance</option>
			<option value="31">IT-Hardware and Networking</option>
			<option value="32">IT-Software/Software Services</option>
			<option value="33">KPO / Research /Analytics</option>
			<option value="34">Legal</option>
			<option value="35">Media/Dotcom/Entertainment</option>
			<option value="36">Medical/Healthcare/Hospital</option>
			<option value="37">Mining</option>
			<option value="38">NGO/Social Services</option>
			<option value="39">Office Equipment/Automation</option>
			<option value="40">Oil and Gas/Power/Infrastructure/Energy</option>
			<option value="41">Paper</option>
			<option value="42">Pharma/Biotech/Clinical Research</option>
			<option value="43">Printing/Packaging</option>
			<option value="44">Publishing</option>
			<option value="45">Real Estate/Property</option>
			<option value="46">Recruitment</option>
			<option value="47">Retail</option>
			<option value="48">Security/Law Enforcement</option>
			<option value="49">Semiconductors/Electronics</option>
			<option value="50">Shipping/Marine</option>
			<option value="51">Steel</option>
			<option value="52">Strategy /Management Consulting Firms</option>
			<option value="53">Telcom/ISP</option>
			<option value="54">Textiles/Garments/Accessories</option>
			<option value="55">Tyres</option>
			<option value="56">Water Treatment / Waste Management</option>
			<option value="57">Wellness/Fitness/Sports</option>
			<option value="58">Other</option>
		</select>
		<p class="formHint">Field of the company</p>
	</div>

	<div class="ctrlHolder">
		<label for="description"><em>*</em>Description</label>
		<textarea rows="2" cols="20" name="description" id="description" data-default-value="e.g. CMMI Level 5 Company with more than 80,000 employees." class="textInput"><?php echo $company_info['description']?></textarea>
		<p class="formHint">Details of the company</p>
	</div>
					
	<div class="ctrlHolder">
		<label for="verified">Is Verified</label>
		<input type="checkbox" name="verified" id="verified"><br>
		<p class="formHint">Select if the company is verified</p>
	</div>
	
	<div id="submitStatus" style="display:none;padding: 1em;" class="ui-state-highlight ui-corner-all" ></div> 
	<div class="buttonHolder">
		<button type="reset" class="secondaryAction">Reset</button>
		<button type="submit" class="primaryAction">Next</button>
	</div>				
</fieldset>
</form>

<script type="text/javascript">

    $(function(){
    	$('#topContent').hide();

    	$('form.uniForm').uniform({
    		prevent_submit : false
    	});
    });

	$('#field').val('<?php echo $company_info['field']?>');
	
	<?php 
		if($company_info['verified'] == '1'){
	        echo "$('#verified').attr('checked',true);";
	    }
	?>
    
    function submit_company_info(){
        var data = {};
    	var company_info = {};
    	var urlSaveCompanyInfo = "<?php echo $this->url(array('controller' => 'career', 'action' => 'addcompany'))?>";

		$('#student_placement :input')
		.not('button')
		.each(function(){
			company_info[this.name] = this.value;
		});
		
		if($('input[name="verified"]').is(':checked'))
			company_info['verified'] = 1;
		else
			company_info['verified'] = 0;
    	
    	data['company_info'] = company_info;
    	$.ajax({
    		url : urlSaveCompanyInfo,
    		data : {myarray:data},
    		success: function(jStatus){
        		if(jStatus){
            		alert(jStatus)
        		}
            },
            error: function(response) {
    			$('#errorBox').text(response.responseText).parent().show();
    				console.log(response);
    		}
    	});
    }
    	
</script>
<style>
	.uniForm{
		background-color:white;
		padding:10px 10px 10px 25px;
		border:1px solid #b4c1da;
		margin:-5px 0 40px 0;
		box-shadow:#e4e4e4 0px 0px 1px 1px;
		width:auto;
	}
	h2,h3{
		padding:3px 3px 3px 10px;
		background-color:#eceff4;
		border:1px solid #b4c1da;
		font-size:17px;
		font-weight:100;
		margin-top:2px;
	}
	#goback a{
		float:right;
		color:red;
		font-size:14px;
		text-decoration: none;
	}
</style>
<?php
$this->headScript()->appendFile('http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
    
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/smooth.uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/demos/css/demo.css');
?>