<h3 align="center">Manage Sessionals</h3>
<div id="main_div">

	<div id="selection-div"class="ui-widget-content ui-corner-all" style="width:20em; height:5em; padding:4px">
	
		<label for="degree_id" accesskey="S" id="lbl_degree_id" style="padding: 0.4em; float: left;">
			Degree:</label>&nbsp;
		<select id="degree_select" tabindex="1" >
		</select>
		
		<br /><br />
		
		<?php
		    if(count($this->slaveDepartment)>1){
		    ?>    	    
		        <label for="slave_dept" accesskey="S" id="lbl_class_id" style="padding: 0.4em; float: left;" >
			    Choose Department:</label>&nbsp;
	
				<select id="slave_dept_select" tabindex="1" disabled="disabled">
					<option>Select department</option>
				</select>
		<?php
		    }
		    else{ 
		?>
			<label for="class_id" accesskey="S" id="lbl_class_id" style="padding: 0.4em; float: left;" >
				Class:</label>&nbsp;
			<select id="class_select" tabindex="1" disabled="disabled">
				<option>Select one</option>
			</select>
		<?php
		    } 
		?>
		
	</div> <!-- End selection-div -->
	<br />
	
	<div id="sessional-schedule-div" style="display">
	
		<table id="tblgrid" class="scroll"></table>
		<div id="gridpager" class="scroll" style="text-align: center;"></div>
		
	</div><!-- End sessioanl-schedule-div -->

</div> <!-- End main_div -->


<script type="text/javascript" language="javascript">
var slaveDepartment = 'CSE';
$(function(){
    var gridTable = "#tblgrid";
    var gridPager = "#gridpager"; 
    var dep_id = "<?php echo $this->masterDepartment?>";
    
    var urlFillGrid = "<? echo $this->url(array(
												'controller' => 'sessional', 
												'action' => 'fillgrid'))?>";
												
    var urlCRUD = "<? echo $this->url(array('module' => $this->module, 
											'controller' => $this->controller, 
											'action' => 'crud'), 'default', true)?>";
										
	var urlDegreeCombo = "<?php echo 'http://' . CORE_SERVER . $this->url(array('controller' => 'semesterdegree', 
																				'action' => 'getslavedegree'), 
																				'default', true)?>";
																				
	var urlFetchActiveClasses = "<?php echo 'http://' . CORE_SERVER . $this->url(array('controller' => 'semesterdegree', 
																				'action' => 'getsessionsemester'), 
																				'default', true)?>";
										    
	$.ajax({
        url : urlDegreeCombo,
        dataType : 'jsonp',
        data : {'masterDepartment': dep_id,'slaveDepartment' : dep_id, 'format' : 'jsonp' },
        success: function(jDegree){
        	var selectOptionString = '<option value ="">Select one</option>';
			$.each(jDegree, function (index, degree) {
				selectOptionString += '<option value ="'+degree.degree_id+'">'+degree.degree_id+'</option>';
			});
            $('#degree_select').html(selectOptionString);
       },
       error: function(event) {
            alert(event.responseText);
       }
    });//End ajax call.
    
	$('#degree_select').change(function(){
		
		var deg_id = $("#degree_select").val();
		
		$.ajax({
	        url : urlFetchActiveClasses,
	        dataType : 'jsonp',
	        data : {'degree_id' : deg_id ,'department_id' : dep_id, 'format' : 'jsonp'}, 
	        success: function(jClass){
	        	var selectOptionString = '<option value ="">Select one</option>';
				$.each(jClass, function (index, jclass) {
					selectOptionString += '<option  value ="'+jclass.semester_id+'" >'+jclass.semester_id+'</option>';
				});
	            $('#class_select').html(selectOptionString);
	            $('#class_select').attr('disabled',null);
	        },
	        error: function(event) {
	            alert(event.responseText);
	        }
	    });//End ajax call.
        	
	});//End #degree_select change.

	$('#class_select').change(function(){
		
		var deg_id = $("#degree_select").val();
		var sem = $("#class_select").val();
		var dep = slaveDepartment;

		$(gridTable).jqGrid('setGridParam',
				            {
             					postData:{
                 					       'department_id':dep,
                 					       'degree_id':deg_id,
                 					       'semester_id':sem,
                 					       'test_id':1
                 					     },
                 			    url: urlFillGrid
                            }
                            ).trigger("reloadGrid");
		
	});//End #degree_select change.
	
	$(gridTable).jqGrid({
		colNames:['Subject Code','Subject Name','Date of conduct','Time','Max Marks','Pass Marks'],
		colModel:[
			{
				name:'subject_code',
        	    index:'subject_code'
            },
            {
				name:'subject_name',
        	    index:'subject_name'
            },
            {
                name:'date_of_conduct',
                index:'date_of_conduct',
                editable: true
            },
            {
                name:'time', 
                index:'time',
                editable: true
            },
            {
                name:'max_marks',
                index:'max_marks',
                editable: true
            },
            {
                name:'pass_marks', 
                index:'pass_marks',
                editable: true
            },            
            ],
        caption: "Manage Sessional Schedule  " ,
        pager: gridPager,
        onSelectRow: function(id){
            if(id && id!==lastSel){ 
               jQuery('#grid_id').restoreRow(lastSel); 
               lastSel=id; 
            }
            jQuery('#grid_id').editRow(id, true); 
          },
        editurl:urlCRUD
		});

	$(gridTable).jqGrid('navGrid', 
						gridPager, 
						{
        					add : false,
        					del : false,
        					edit : false,
       						view : false,
        					search : false,
        					refresh : false
    					}, // options
    					
            			{
                			width : 400,
                			savekey : [ true, 13 ],
                			navkeys : [ true, 38, 40 ],
                			jqModal : false,
                			closeOnEscape : true
            			}, // edit options
            			
            			{
            			    width : 400,
                			savekey : [ true, 13 ],
                			navkeys : [ true, 38, 40 ],
                			jqModal : false,
                			closeOnEscape : true,
                			clearAfterAdd : true //Default is true, make false if needed
            			}, // add options
            			
            			{
                			reloadAfterSubmit : false,
                			jqModal : false,
                			closeOnEscape : true
            			} // del options
 	);
    
    addPager(gridTable, gridPager); 
    
	});
	
</script>