<!--[if lte ie 7]>
	<style type="text/css" media="screen">
		/* Move these to your IE6/7 specific stylesheet if possible */
		.uniForm, .uniForm fieldset, .uniForm .ctrlHolder, .uniForm .formHint, .uniForm .buttonHolder, .uniForm .ctrlHolder ul{ zoom:1; }
	</style>
<![endif]-->

<div id="tpo_navigation">
	<img alt="TPO" id="tpo_img" src="http://site.cdn.aceambala.com/images/tpo/tpo.jpg" width="40" height="46">
	<ul id="list">
		<li id="index"><a href="/admin/index">Home</a></li>
		<li id="filterstudents"><a href="/admin/filterstudent">Filter Students</a></li>
		<li id="viewstudentprofile"><a href="/admin/viewstudentprofile">View Student Profile</a></li>
		<li id="notifications"><a href="">Notifications</a></li>
	</ul>
</div>
<br>

<form action="javascipt:void(0)" id="search_criteria" style="width:60%;float:left;">
<div class="main_div">
	<div class="heading">
		<h4>Personal Information</h4>
	</div>
	<fieldset id="personal" class="search_field_div">
		<label for="gender">Gender</label>
		<select name="gender" id="gender">
			<option value="Any">ANY</option>
			<option value="MALE">MALE</option>
			<option value="FEMALE">FEMALE</option>
		</select>&nbsp;
		
		<label for="cast_id">Cast</label>
		<select id="cast_id" name="cast_id">
			<option value="Any">ANY</option>
       		<option value="1">GEN</option>
       		<option value="2">BC</option>
       		<option value="3">SC</option>
       		<option value="4">ST</option>
		</select>&nbsp;
		
		<label for="religion_id">Religion</label>
		<select id="religion_id" name="religion_id" class="selectInput required">
			<option value="Any">ANY</option>
       		<option value="1">Hindu</option>
       		<option value="2">Muslim</option>
       		<option value="3">Sikh</option>
       		<option value="4">Christian</option>
		</select>&nbsp;<br>
		
		<label for="dob_from">Date of Birth from</label>
		<input name="dob_from" id="dob_from" size="18" maxlength="50" type="text" readonly="readonly"/>
		
		<label for="dob_to">To</label>
		<input name="dob_to" id="dob_to" size="18" maxlength="50" type="text" readonly="readonly"/>&nbsp;<br>
		
		<label for="annual_income_from">Annual Income From</label>
		<input name="annual_income_from" id="annual_income_from" size="18" maxlength="50" type="text"/>
		
		<label for="annual_income_to">To</label>
		<input name="annual_income_to" id="annual_income_to" size="18" maxlength="50" type="text"/>
	</fieldset>
</div>

<br>

<div id="academic" class="main_div">
	<div class="heading">
		<h4>Academic Information</h4>
	</div>
	<div class="search_field_div">
	
		<fieldset id="btech_info">

			<label for="discipline_id">Discipline</label>
			<select id="discipline_id" name="discipline_id" class="selectInput required">
				<option value="Any">ANY</option>
				<option value="CSE">Computer Science</option>
				<option value="ECE">Electronics And Communication</option>
				<option value="MECH">Mechanical</option>
				<option value="BT">Biotechnology</option>
			</select>&nbsp;
			
			<label for="passing_year">B.Tech Batch</label>
			<select name="passing_year" id="passing_year">
				<option value="Any">ANY</option>
				<?php
			    	$current_year = intval(date('Y'));
			    	for($i=2002+4;$i<=$current_year+4;$i++)
			    	{
			    	    echo '<option value="'.$i.'">'.$i.' - '.($i+4).'</option>';
			    	}
				?>
			</select><br>
		</fieldset>
		
		<div class="ctrlHolder">
			<label for="btech_filter">&nbsp;&nbsp;Is Btech Required</label>
			<input name="btech_filter" id="btech_filter" onclick="javascript:show_fieldset('btech')" size="35" maxlength="50" type="checkbox" class="checkbox"/>
		</div>
		
		<fieldset id="btech">
			
			<label for="percentage">B.Tech Percentage</label>
			<input type="text" id="percentage" readonly="readonly" style="border:0; color:#f6931f; font-weight:bold;" />
			<div id="btech_slider-range"></div>
			
			<label for="backlogs">Backlogs in B.Tech</label>
			<select name="backlogs" id="backlogs">
				<option value="never">Never</option>
				<?php 
					for($i=0;$i<=10;$i++)
						echo '<option value="'.$i.'">'.$i.'</option>';
				?>
				<option value="any">Any</option>
			</select>
		
		</fieldset>
		
		<div class="ctrlHolder">
			<label for="twelfth_filter">&nbsp;&nbsp;Is Twelfth Required</label>
			<input name="twelfth_filter" id="twelfth_filter" onclick="javascript:show_fieldset('twelfth')" size="35" maxlength="50" type="checkbox" class="checkbox"/>
		</div>
	
		<fieldset id="twelfth">
			<label for="percentage">10+2 Percentage</label>
			<input type="text" id="percentage" readonly="readonly" style="border:0; color:#f6931f; font-weight:bold;" />
			<div id="twelfth_slider-range"></div>
			
			<label for="passing_year">10+2 Passing Year</label>
			<select name="passing_year" id="passing_year">
				<option value="Any">ANY</option>
				<?php
			    	$current_year = intval(date('Y'));
			    	for($i=2002;$i<=$current_year;$i++)
			    	{
			    	    echo '<option value="'.$i.'">'.$i.'</option>';
			    	}
				?>
			</select>
		</fieldset>
		
		<div class="ctrlHolder">
			<label for="diploma_filter">&nbsp;&nbsp;Is Diploma Required</label>
			<input name="diploma_filter" id="diploma_filter" onclick="javascript:show_fieldset('diploma')" size="35" maxlength="50" type="checkbox" class="checkbox"/>
		</div>
		
		<fieldset id="diploma">
			<label for="percentage">Diploma Percentage</label>
			<input type="text" id="percentage" readonly="readonly" style="border:0; color:#f6931f; font-weight:bold;" />
			<div id="diploma_slider-range"></div>
			
			<label for="passing_year">Diploma Passing Year</label>
			<select name="passing_year" id="passing_year">
				<option value="Any">ANY</option>
				<?php
			    	$current_year = intval(date('Y'));
			    	for($i=2002;$i<=$current_year;$i++)
			    	{
			    	    echo '<option value="'.$i.'">'.$i.'</option>';
			    	}
				?>
			</select>
		</fieldset>
		
		<div class="ctrlHolder">
			<label for="tenth_filter">&nbsp;&nbsp;Is Tenth Required</label>
			<input name="tenth_filter" id="tenth_filter" onclick="javascript:show_fieldset('tenth')" size="35" maxlength="50" type="checkbox" class="checkbox"/>
		</div>
		
		<fieldset id="tenth">
			<label for="percentage">Tenth Percentage</label>
			<input type="text" id="percentage" readonly="readonly" style="border:0; color:#f6931f; font-weight:bold;" />
			<div id="tenth_slider-range"></div>
			
			<label for="passing_year">Tenth Passing Year</label>
			<select name="passing_year" id="passing_year">
				<option value="Any">ANY</option>
				<?php
			    	$current_year = intval(date('Y'));
			    	for($i=2002;$i<=$current_year;$i++)
			    	{
			    	    echo '<option value="'.$i.'">'.$i.'</option>';
			    	}
				?>
			</select>
		</fieldset>
		
	</div>
</div>

<br>

<!-- <div id="career" class="main_div">
	<div class="heading">
		<h4>Career Information</h4>
  	</div>
</div>
 -->
<br>

<input type="button" value="Search" onclick="javascript:submit_personal_values()"/>
</form>

<div id="search_result" style="width:35%;float:right;padding:5px;" class="main_div">
	<div class="heading">
		<h4>Search Results</h4>
	</div>
	<div class="student_data" style="padding:5px;">
	</div>
	<input type="submit" value="Export to Excel" onclick="javascript:collect_core_data()">
	<input type="submit" value="Send Mail" onclick="javascript:show_dialog_box()">
</div>

<div id="dialog" title="Send Mail">

	<label for="subject">Subject</label>
	<input name="subject" id="subject" size="40" maxlength="150" type="text" /><br><br>
	
	<label for="message">Message</label>
	<textarea name="message" id="message" rows="7" cols="40"></textarea><br>
	
	<input type="button" value="Send" id="send_button" onclick="javascript:send_mail()">
</div>

<script type="text/javascript">
	$(function(){
		$('#topnav').hide();
		$('fieldset#tenth').hide();
		$('fieldset#twelfth').hide();
		$('fieldset#diploma').hide();
		$('fieldset#btech').hide();
		
		$('#filterstudents').css('background-color','#b3cdd6');
		$('#filterstudents').css('border','1px solid black');
		$('#filterstudents').css('padding','5px 6px');
	});

	var personal_result = new Array();
	var academic_result = new Array();

	$('#search_result').hide();
	$('#dialog').hide();
	
	serverDateObj = $.datepicker.parseDate('dd-mm-yy', $('#datetext').text());
	$("#dob_from").datepicker({
		dateFormat: 'yy-mm-dd',
		changeMonth: true,
		changeYear: true,
		yearRange: '-25:-15',
		onClose : function(dateText, inst) {
			this.focus();
			}
	});
	
	serverDateObj = $.datepicker.parseDate('dd-mm-yy', $('#datetext').text());
	$("#dob_to").datepicker({
		dateFormat: 'yy-mm-dd',
		changeMonth: true,
		changeYear: true,
		yearRange: '-25:-15',
		onClose : function(dateText, inst) {
			this.focus();
			}
	});
	$( "#tenth_slider-range" ).slider({
		range: true,
		min: 0,
		max: 100,
		values: [ 0, 100 ],
		slide: function( event, ui ) {
			$("fieldset#tenth > #percentage").val( ui.values[ 0 ] + "-" + ui.values[ 1 ] );
		}
	});
	$( "fieldset#tenth > #percentage" ).val( $( "#tenth_slider-range" ).slider( "values", 0 ) +
		"-" + $( "#tenth_slider-range" ).slider( "values", 1 ) );

	$( "#twelfth_slider-range" ).slider({
		range: true,
		min: 0,
		max: 100,
		values: [ 0, 100 ],
		slide: function( event, ui ) {
			$( "fieldset#twelfth > #percentage" ).val( ui.values[ 0 ] + "-" + ui.values[ 1 ] );
		}
	});
	$( "fieldset#twelfth > #percentage" ).val( $( "#twelfth_slider-range" ).slider( "values", 0 ) +
		"-" + $( "#twelfth_slider-range" ).slider( "values", 1 ) );

	$( "#btech_slider-range" ).slider({
		range: true,
		min: 0,
		max: 100,
		values: [ 0, 100 ],
		slide: function( event, ui ) {
			$( "fieldset#btech > #percentage" ).val( ui.values[ 0 ] + "-" + ui.values[ 1 ] );
		}
	});
	$( "fieldset#btech > #percentage" ).val( $( "#btech_slider-range" ).slider( "values", 0 ) +
		"-" + $( "#btech_slider-range" ).slider( "values", 1 ) );

	$( "#diploma_slider-range" ).slider({
		range: true,
		min: 0,
		max: 100,
		values: [ 0, 100 ],
		slide: function( event, ui ) {
			$( "fieldset#diploma > #percentage" ).val( ui.values[ 0 ] + "-" + ui.values[ 1 ] );
		}
	});
	$( "fieldset#diploma > #percentage" ).val( $( "#diploma_slider-range" ).slider( "values", 0 ) +
		"-" + $( "#diploma_slider-range" ).slider( "values", 1 ) );

	function show_fieldset(fieldset_id)
	{
		if($(':input[name="'+fieldset_id+'_filter"]').is(':checked'))
		{
			$('fieldset#'+fieldset_id).show();
		}
		else
		{
			$('fieldset#'+fieldset_id).hide();
		}
	}
	
	function isEmpty(ob){
		for(var i in ob){ return false;}
			return true;
	}
	
	function submit_personal_values()
	{
		var personal_values={};
		var dob = {};
		var annual_income = {};
		
		if($('#gender').val()!='Any')
			personal_values['0gender'] = $('#gender').val();
		if($('#cast_id').val()!='Any')
			personal_values['0cast_id'] = $('#cast_id').val();
		if($('#religion_id').val()!='Any')
			personal_values['0religion_id'] = $('#religion_id').val();
		if($("#dob_from").val()!='')
			dob['from'] = $("#dob_from").val();
		if($("#dob_to").val()!='')
			dob['to'] = $("#dob_to").val();
		if(dob['from']!=null || dob['to']!=null)
			personal_values['0dob'] = dob;
		
		if($("#annual_income_from").val()!='')
			annual_income['from'] = $("#annual_income_from").val();
		if($("#annual_income_to").val()!='')
			annual_income['to'] = $("#annual_income_to").val();
		if(annual_income['from']!=null || annual_income['to']!=null)
			personal_values['1annual_income'] = annual_income;

		if($('fieldset#btech_info > #discipline_id').val() != 'Any')
			personal_values['discipline_id'] = $('fieldset#btech_info > #discipline_id').val();

		if($('fieldset#btech_info > #passing_year').val() != 'Any')
			personal_values['batch_start'] = $('fieldset#btech_info > #passing_year').val();

		personal_values['programme_id'] = 'BTECH';
		var urlsubmitpersonal = "http://core.aceambala.com/search/search";
		$.ajax({
    		url : urlsubmitpersonal,
    		dataType : 'jsonp',
    		async : false,
    		data : {
        			myarray:personal_values,
					format:'jsonp'
        			},
    		success: function(jStatus){
    			if(jStatus != 'false')
				{
    				var i=0;
    				$.each(jStatus,function(index,value){
						personal_result[i] = value;
						i++;
        			});
        			//alert(personal_result);
				}
    			submit_academic_values();
    		},
            error: function(response) {
				//$('#errorBox').text(response.responseText).parent().show();
    			//console.log(response);
    		}
		});
	}

	function submit_academic_values()
	{
		var academic_values = {};

		if($(':input[name="tenth_filter"]').is(':checked'))
		{
			if($('fieldset#tenth > #passing_year').val() != 'Any')
				academic_values['0passing_year'] = $('fieldset#tenth > #passing_year').val();
			
			var tenth_percentage = $('fieldset#tenth > #percentage').val();
			var tenth_l = tenth_percentage.substring(0,tenth_percentage.search('-'));
			var tenth_u = tenth_percentage.substring(tenth_percentage.search('-')+1,tenth_percentage.length);
	
			academic_values['0percentage'] = {'from':tenth_l, 'to':tenth_u};
		}

		if($(':input[name="twelfth_filter"]').is(':checked'))
		{
			if($('fieldset#twelfth > #passing_year').val() != 'Any')
				academic_values['1passing_year'] = $('fieldset#twelfth > #passing_year').val();
			
			var twelfth_percentage = $('fieldset#twelfth > #percentage').val();
			var twelfth_l = twelfth_percentage.substring(0,twelfth_percentage.search('-'));
			var twelfth_u = twelfth_percentage.substring(twelfth_percentage.search('-')+1,twelfth_percentage.length);
	
			academic_values['1percentage'] = {'from':twelfth_l, 'to':twelfth_u};
		}

		if($(':input[name="diploma_filter"]').is(':checked'))
		{
			if($('fieldset#diploma > #passing_year').val() != 'Any')
				academic_values['2passing_year'] = $('fieldset#diploma > #passing_year').val();
			
			var diploma_percentage = $('fieldset#diploma > #percentage').val();
			var diploma_l = diploma_percentage.substring(0,diploma_percentage.search('-'));
			var diploma_u = diploma_percentage.substring(diploma_percentage.search('-')+1,diploma_percentage.length);
	
			academic_values['2percentage'] = {'from':diploma_l, 'to':diploma_u};
		}

		if($(':input[name="btech_filter"]').is(':checked'))
		{
			var btech_percentage = $('fieldset#btech > #percentage').val();
			var btech_l = btech_percentage.substring(0,btech_percentage.search('-'));
			var btech_u = btech_percentage.substring(btech_percentage.search('-')+1,btech_percentage.length);
	
			academic_values['3percentage'] = {'from':btech_l, 'to':btech_u};
	
			academic_values['backlogs'] = $('#backlogs').val();
		}

		if(!isEmpty(academic_values))
		{
			var urlsubmitacademic = "http://academic.aceambala.com/search/search";
			$.ajax({
	    		url : urlsubmitacademic,
	    		dataType : 'jsonp',
	    		async : 'false',
	    		data : {
	        			myarray : academic_values,
						format : 'jsonp'
	        			},
	    		success: function(jStatus){
					if(jStatus != 'false')
					{
						var i=0;
	    				$.each(jStatus,function(index,value){
							academic_result[i] = value;
							i++;
	        			});
					}
					intersect_arrays();
	    		},
	            error: function(response) {
					//$('#errorBox').text(response.responseText).parent().show();
	    			//console.log(response);
	    		}
			});
		}
	}

	function intersect_arrays()
	{
		var urlsubmitacademic = "http://academic.aceambala.com/utility/intersect",finalArray;
		$.ajax({
    		url : urlsubmitacademic,
    		dataType : 'jsonp',
    		async : 'false',
    		data : {
        			myarray : {arrayOne:personal_result,arrayTwo:academic_result},
					format : 'jsonp'
        			},
    		success: function(response){       		
        		proceed(response);    		
    		},
            error: function(response) {
				//$('#errorBox').text(response.responseText).parent().show();
    			//console.log(response);
    		}
		});
		
	}

	function proceed(flag){
		
		if(flag == 'none')
		{
			alert('No students satisfy your criteria..Please try with some other options..');
		}
		else {
			var urlGetRollNo = "http://core.aceambala.com/search/fetchrollnumbers"; //fetchRollNumbers
			$.ajax({
	    		url : urlGetRollNo,
	    		dataType : 'jsonp',
	    		data : {
	        			myarray : flag,
						format : 'jsonp'
	        			},
	    		success: function(jStatus){
	    			var html = '';
					if(jStatus != 'false')
					{
						$.each(jStatus,function(member_id,roll_no){
							html += '<div id="'+member_id+'" class="student_info">Roll Number '+roll_no+'</div>';
						});
						$('.student_data').html(html);
						$('#search_result').show();
					}
	    		},
	            error: function(response) {
					//$('#erorBox').text(response.responseText).parent().show();
	    			//console.log(response);
	    		}
			});

		}
	}
	function show_dialog_box()
	{
		$("#dialog").dialog();
		$('#dialog').show();
	}

	function collect_member_ids()
	{
		var member_id_array = new Array();
		$('.student_data > .student_info').each(function(){
			member_id_array.push($(this).attr('id'));
		});

		return member_id_array;
	}
	
	function send_mail()
	{
		$('#dialog').append('<center><img id="loading" src = "http://site.cdn.aceambala.com/images/loading.gif" width="100" height="100"></center>');
		$('#send_button').hide();
		var member_id_array = new Array();
		$('.student_data > .student_info').each(function(){
			member_id_array.push($(this).attr('id'));
		});

		var urlfetchemailids = "http://core.aceambala.com/student/fetchemailids";
		$.ajax({
			url : urlfetchemailids,
			dataType : 'jsonp',
			data : {
				member_ids : member_id_array,
				format : 'jsonp'
			},
			success : function(jStatus){
				var email_id_array = new Array();
				$.each(jStatus,function(member_id,email_id){
					email_id_array.push(email_id);
				});
				
				var urlsendmail = "http://core.aceambala.com/student/sendemail";
				$.ajax({
					url : urlsendmail,
					dataType : 'jsonp',
					data : { myarray : 
							{'email_ids' : email_id_array,
							'subject' : $('#subject').val(),
							'message' : $('#message').val()},

							format : 'jsonp'
					},
					success : function(jStatus){
						if(jStatus == 'true')
						{
							$('#send_button').show();
							$('#loading').hide();
							$('#dialog').dialog('close');
						}
					},
					error : function(response){
						
					}
				});	
			},
			error : function(response){
				
			}
		});
	}
	
	function collect_core_data()
	{
		var core_data = {};
		
		var urlsendmail = "http://core.aceambala.com/student/collectexportabledata";
		$.ajax({
			url : urlsendmail,
			dataType : 'jsonp',
			data : { myarray :{
				member_ids : collect_member_ids() },
				format : 'jsonp'
			},
			success : function(jStatus){
				core_data = jStatus;
				collect_academic_data(core_data);
			},
			error : function(response){
				
			}
		});
	}

	function collect_academic_data(core_data)
	{
		var academic_data = {};
		var urlsendmail = "http://academic.aceambala.com/student/collectexportabledata";
		$.ajax({
			url : urlsendmail,
			dataType : 'jsonp',
			data : { myarray :{
				member_ids : collect_member_ids() },
				format : 'jsonp'
			},
			success : function(jStatus){
				academic_data = jStatus;
				export_data(core_data,academic_data);
			},
			error : function(response){
				
			}
		});
	}

	function export_data(core_data,academic_data)
	{
		var urlsendmail = "http://tnp.aceambala.com/student/exportexcel";
		$.ajax({
			type: 'POST',
			url : urlsendmail,
			dataType : 'jsonp',
			data : { myarray :{
					'core_data' : core_data,
					'academic_data' : academic_data 
					},
					format : 'jsonp'
			},
			success : function(jStatus){
				window.location.replace('http://tnp.aceambala.com/student/saveexcelonclient?file_id='+jStatus);
			},
			error : function (xhr, ajaxOptions, thrownError) {
		        alert(xhr.responseText);
		        alert(thrownError);
				
			}
		});

		
	}

</script>

<style type="text/css">
	.main_div{
		background-color: #F9F9F9;
		border: 0.1em solid #D1D1D1;
		border-radius:4px;	
	}
	.heading {
		background-color:#E1E1E1;
	}
	.heading > h4{
		font-size: 1.1em;
		margin-top:0px;
		margin-bottom:10px;
		padding:2px 0 2px 10px;
	}
	.search_field_div{
		padding:2px;
	}
	fieldset{
		padding:5px 20px 5px 5px;
		line-height: 2.6em;
		border:0.1em solid #F9F9F9;
	}
	.student_info {
		padding:2px 0 2px 5px;
		background-color: white;
		border-radius:3px;
		border:0.1em solid grey;
	}
	div#tpo_navigation{
		background-color:#d6ebf2;
		border:0.1em solid #97afb7;
		border-radius:2px;
		margin:10px 0;
		padding:11px;
	}
	ul#list{
		padding:5px 5px 5px 5px;
		list-style: none outside none;
    	margin: 0;
	}
	ul#list>li{
		display:inline;
		padding:5px 6px 5px 6px;
	}
	ul#list>li:hover{
		display:inline;
		padding:5px 5px 5px 5px;
		background-color:#b3cdd6;
		border: 1px solid black;
	}
	ul#list>li>a{
		text-decoration:none;
		color:black;
	}
	#tpo_img{
		float:left;
		border:1px solid grey;
		border-radius:2px;
		margin: -5px 10px 0 -3px;
	}
</style>