<div id="welcome_div">
	<img alt="TPO" id="tpo_img" src="http://site.cdn.aceambala.com/images/tpo/tpo.jpg" width="100" height="116">
	<h3>Welcome Mr. Chander Shekhar !</h3>
</div>

<div id="menubar">
	<ul id="list">
		<li><a href="/admin/filterstudent">Filter Students</a></li>
		<li><a href="/admin/viewstudentprofile">View Student Profile</a></li>
		<li><a href="">Notifications</a></li>
	</ul>
</div>

<style type="text/css">
	#tpo_img{
		border:1px solid grey;
		border-radius:2px;
		float:left;
		margin: 0 20px 0 0;
		padding: 2px;
	}
	#list{
		list-style-position: inside;
		list-style-image: url("http://site.cdn.aceambala.com/images/activity/arrow_green.png");
	}
	#list > li > a{
		text-decoration: none;
		color:black;
		font-size:1.2em;
		line-height: 1.4em;
		margin:1px;
	}
	#list > li > a:hover{
		color:grey;
		margin:1px;
	}
</style>