
<!--[if lte ie 7]>
      <style type="text/css" media="screen">
        /* Move these to your IE6/7 specific stylesheet if possible */
        .uniForm, .uniForm fieldset, .uniForm .ctrlHolder, .uniForm .formHint, .uniForm .buttonHolder, .uniForm .ctrlHolder ul{ zoom:1; }
      </style>
    <![endif]-->
    <style>
	#sortable { list-style-type: none; margin: 0; padding: 0; }
	#sortable li { margin: 0 3px 3px 3px; padding: 0.4em; padding-left: 1.5em; }
	#sortable li span { position: absolute; margin-left: -1.3em; }
	</style>
<div id="progressbar"></div>

<form action="javascript:submit();" class="uniForm">
<h2><?php $stepNo = $this->stepNo;
        echo 'Step '.($stepNo+1).'/'.count($this->steps).': '.ucfirst($this->steps[$stepNo]);?>:</h2>
        <hr/>
<?php 
      $basis = strtolower($this->applicant->application_basis);
      if ('twelfth' == $basis) { ?>
        <fieldset><h3>BRANCHES:</h3>
        <p class="formHint">Sort the branches in order of preference</p>
        <ul id="sortable" >
        	<li id="BT" class="ui-state-default ui-corner-all"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span>Bio-Technology</li>
        	<li id="CSE" class="ui-state-default ui-corner-all"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span>Computer Science and Engineering</li>
        	<li id="ECE" class="ui-state-default ui-corner-all"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span>Electronics and Communication Engineering</li>
        	<li id="ME" class="ui-state-default ui-corner-all"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span>Mechanical Engineering</li>
        </ul>
        <script type="text/javascript">
  		$( "#sortable" ).sortable().disableSelection();
        </script>
        <?php } else { ?>
            <fieldset><h3>Councelling Allotment:</h3>
        <div class="ctrlHolder">
          <label for="">Allotted Branch</label>
          <select id="allotted_branch" name="allotted_branch" class="selectInput">
          		<option value="BT">Bio-Technology</option>
          		<option value="CSE">Computer Science and Engineering</option>
          		<option value="ECE">Electronics and Communication Engineering</option>
          		<option value="ME">Mechanical Engineering</option>
      	  </select>
          <p class="formHint">Branch allotted in councelling.</p>
        </div>
        <?php  } ?>

        <div class="ctrlHolder">
          <label for="">Alloted Category</label>
          <select id="allotted_category" name="allotted_category" class="selectInput required">
 
 				<option value="">Select category</option>
 				         
          		<optgroup label="AIC"></optgroup>
          		<option value="AIC,OPEN">AIC,OPEN</option>
          		<option value="AIC,FEMALE">AIC,FEMALE</option>
          		
          		<optgroup label="HOGC"></optgroup>
          		<option value="HOGC,OPEN">HOGC,OPEN</option>
          		<option value="HOGC,FEMALE">HOGC,FEMALE</option>
          		<option value="HOGC,EX-SERVICEMEN,OPEN">HOGC,EX-SERVICEMEN,OPEN</option>
          		<option value="HOGC,EX-SERVICEMEN,FEMALE">HOGC,EX-SERVICEMEN,FEMALE</option>
          		<option value="HOGC,FREEDOM FIGHTER,OPEN">HOGC,FREEDOM FIGHTER,OPEN</option>
          		<option value="HOGC,FREEDOM FIGHTER,FEMALE">HOGC,FREEDOM FIGHTER,FEMALE</option>
          		
          		<optgroup label="SC"></optgroup>
          		<option value="SC,OPEN">SC,OPEN</option>
          		<option value="SC,FEMALE">SC,FEMALE</option>
          		<option value="SC,EX-SERVICEMEN,OPEN">SC,EX-SERVICEMEN,OPEN</option>
          		<option value="SC,EX-SERVICEMEN,FEMALE">SC,EX-SERVICEMEN,FEMALE</option>
          		<option value="SC,FREEDOM FIGHTER,OPEN">SC,FREEDOM FIGHTER,OPEN</option>
          		<option value="SC,FREEDOM FIGHTER,FEMALE">SC,FREEDOM FIGHTER,FEMALE</option>
	
				<optgroup label="BCA"></optgroup>
          		<option value="BCA,OPEN">BCA,OPEN</option>
          		<option value="BCA,FEMALE">BCA,FEMALE</option>
          		<option value="BCA,EX-SERVICEMEN,OPEN">BCA,EX-SERVICEMEN,OPEN</option>
          		<option value="BCA,EX-SERVICEMEN,FEMALE">BCA,EX-SERVICEMEN,FEMALE</option>
          		<option value="BCA,FREEDOM FIGHTER,OPEN">BCA,FREEDOM FIGHTER,OPEN</option>
          		<option value="BCA,FREEDOM FIGHTER,FEMALE">BCA,FREEDOM FIGHTER,FEMALE</option>
          		
          		<optgroup label="BCB"></optgroup>
          		<option value="BCB,OPEN">BCB,OPEN</option>
          		<option value="BCB,FEMALE">BCB,FEMALE</option>
          		<option value="BCB,EX-SERVICEMEN,OPEN">BCB,EX-SERVICEMEN,OPEN</option>
          		<option value="BCB,EX-SERVICEMEN,FEMALE">BCB,EX-SERVICEMEN,FEMALE</option>
          		<option value="BCB,FREEDOM FIGHTER,OPEN">BCB,FREEDOM FIGHTER,OPEN</option>
          		<option value="BCB,FREEDOM FIGHTER,FEMALE">BCB,FREEDOM FIGHTER,FEMALE</option>
				
				<!-- <optgroup label="BC"></optgroup>
				<option value="BC,OPEN">BC,OPEN</option>
          		<option value="BC,FEMALE">BC,FEMALE</option>
          		<option value="BC,EX-SERVICEMEN,OPEN">BC,EX-SERVICEMEN,OPEN</option>
          		<option value="BC,EX-SERVICEMEN,FEMALE">BC,EX-SERVICEMEN,FEMALE</option>
          		<option value="BC,FREEDOM FIGHTER,OPEN">BC,FREEDOM FIGHTER,OPEN</option>
          		<option value="BC,FREEDOM FIGHTER,FEMALE">BC,FREEDOM FIGHTER,FEMALE</option> -->
          		
          		<optgroup label="PHYSICALLY HANDICAPPED (PH)"></optgroup>
          		<option value="PHYSICALLY HANDICAPPED,OPEN">PHYSICALLY HANDICAPPED,OPEN</option>
          		<option value="PHYSICALLY HANDICAPPED,FEMALE">PHYSICALLY HANDICAPPED,FEMALE</option>
          		
          		<optgroup label="HARYANA GOVERNMENT SCHOOL TOPPER (HOGC)"></optgroup>
          		<option value="HARYANA GOVERNMENT SCHOOL TOPPER,OPEN">HARYANA GOVERNMENT SCHOOL TOPPER,OPEN</option>
          		<option value="HARYANA GOVERNMENT SCHOOL TOPPER,FEMALE">HARYANA GOVERNMENT SCHOOL TOPPER,FEMALE</option>
          		
          		<optgroup label="KASHMIRI MIGRANT (KM)"></optgroup>
          		<option value="KASHMIRI MIGRANT,OPEN">KASHMIRI MIGRANT,OPEN</option>
          		<option value="KASHMIRI MIGRANT,FEMALE">KASHMIRI MIGRANT,FEMALE</option>
          		
          		<optgroup label="TUTION FEE WAIVER (TFW)"></optgroup>
          		<option value="TUTION FEE WAIVER,OPEN">TUTION FEE WAIVER,OPEN</option>
          		<option value="TUTION FEE WAIVER,FEMALE">TUTION FEE WAIVER,FEMALE</option>
          		
      	  </select>
          <p class="formHint">Category allotted in councelling.</p>
        </div>
        
        </fieldset>
            <fieldset><h3>Councelling Info:</h3>
        <div class="ctrlHolder">
          <label for="councelling_fees"><em>*</em>Councelling Fees Paid</label>
          <input name="councelling_fees" id="councelling_fees" value="500" disabled="disabled"  size="35" maxlength="3" type="text" readonly="readonly" class="textInput required validateInteger"/>
          <p class="formHint">Amount paid as councelling fees</p>
        </div>
        
        <div class="ctrlHolder">
          <label for="councelling_bank">Councelling fees Bank</label>
          <select id="councelling_bank" name="councelling_bank" class="selectInput">
          		<option value="PNB">PNB</option>
          		<option value="AXIS">AXIS</option>
      	  </select>
          <p class="formHint">Bank in which councelling fees is submitted.</p>
        </div>
        
        
        <div class="ctrlHolder">
          <label for="">Councelling Number</label>
          <select id="councelling_no" name="councelling_no" class="selectInput" disabled="disabled" >
          		<option value="1">One</option>
          		<!--<option value="2">Two</option>
          		<option value="1">One</option>
          		<option value="3">Three</option>
          		<option value="4">Four</option> -->
      	  </select>
          <p class="formHint">Applying for councelling number.</p>
        </div>
        <div class="ctrlHolder">
          <label for="councelling_type">Councelling Type</label>
          <select id="councelling_type" name="councelling_type" class="selectInput" disabled="disabled">
          		<option value="EXTERNAL">EXTERNAL</option>
          		<!-- <option value="INTERNAL">INTERNAL</option> -->
      	  </select>
          <p class="formHint"></p>
        </div>
        </fieldset>
 		<div id="submitStatus" style="display:none;padding: 1em;" class="ui-state-highlight ui-corner-all" ></div>
        
      <div class="buttonHolder">
        <button type="reset" class="secondaryAction">Reset</button>
        <button type="submit" class="primaryAction">Submit</button>
      </div>

</form>

<script>
	var urlCouncellingInfo = "<?php echo $this->url(array('controller' => 'applicationform', 'action' => 'set'.$this->steps[$stepNo]))?>";
      $(function(){
        $('form.uniForm').uniform({
          prevent_submit : true
        });

        $(function() {
    		$( "#progressbar" ).progressbar({
    			value: <?php echo (100/count($this->steps))*($stepNo+1); ?>
    		});
    	});
      });

      function submit() {
          $.ajax({
              url : urlCouncellingInfo,
              data : getValues(),
              success: function(jStatus){
                  $( "#submitStatus" ).html(jStatus).slideDown('slow', function(){
                    	setTimeout(function(){
                    		window.location = "/applicationform/<?php echo $this->steps[$stepNo+1];?>";
                        	},10000);
                    }).append('<br/><a href="/applicationform/<?php echo $this->steps[$stepNo-1];?>" >&lt;&lt;PREV</a>:<a href="/applicationform/<?php echo $this->steps[$stepNo+1];?>" >NEXT&gt;&gt;</a>');

              },
                  error: function(response) {
                	  $('#errorBox').text(response.responseText).parent().show();
                      console.log(response);
                      }
                  });
      }
      function getValues() {
          var formData = {}; 
          $('form.uniForm :input')
          		.not('button,:input[value^="e.g."]')
          		.each(function(){ 
          			formData[this.name] = this.value; 
              });
          <?php if ('twelfth' == $basis) { ?>
          var choices = $('#sortable').sortable('toArray');
          formData.choices = choices; 
          <?php }?>
		return formData;
	}
    </script>
<?php
$this->headScript()->appendFile('http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
    
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/smooth.uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/demos/css/demo.css');
?>