
<!--[if lte ie 7]>
      <style type="text/css" media="screen">
        /* Move these to your IE6/7 specific stylesheet if possible */
        .uniForm, .uniForm fieldset, .uniForm .ctrlHolder, .uniForm .formHint, .uniForm .buttonHolder, .uniForm .ctrlHolder ul{ zoom:1; }
      </style>
    <![endif]-->
<div id="progressbar"></div>
<form action="javascript:submit();" class="uniForm">
<h2><?php echo ucfirst($this->steps[$this->stepNo]);?>:</h2>
<hr />

        <div class="ctrlHolder noLabel">
          <ul>
            <li><label><input name="hostel" id="hostel" value="<?php echo (('true' === $this->applicant->hostel)?'true':'false');?>"  <?php echo (('true' === $this->applicant->hostel)?'checked="checked"':'');?> type="checkbox"/> Apply for Hostel .</label></li>
          </ul>
          <p class="formHint"><?php if ($this->applicant->hostel) {
              echo 'NOTE: Previously, you opted for hostel.';
          } else {echo 'Click to opt for hostel.';}  ?>  </p>
        </div>
        
        <div id="hostelDiv" <?php if (isset($this->applicant->hostel)) {
                echo (($this->applicant->hostel)?'':'style="display:none;"');
            } else {echo 'style="display:none;"';} ?> class="ctrlHolder">
        Terms and condition...........
        </div>
        
        <div class="ctrlHolder noLabel">
          <ul>
            <li><label><input name="bus" id="bus" value="<?php echo (('true' == $this->applicant->bus)?'true':'false');?>" <?php echo (('true' === $this->applicant->bus)?'checked="checked"':'');?> type="checkbox"/> Apply for Bus facility.</label></li>
          </ul>
          <p class="formHint"><?php if ($this->applicant->bus) {
              echo 'NOTE: Previously, you opted for bus facility.';
          } else {echo 'Click to opt for Bus facility.';}  ?>  </p>
        </div>
        
        <div id="busDiv" <?php if (('true' === $this->applicant->bus)) {
                echo (('true' === $this->applicant->bus)?'':'style="display:none;"');
            } else {echo 'style="display:none;"';} ?> class="ctrlHolder">
          <p class="label">Boarding Station:</p>
          <ul class="blockLabels">
            <li><label><input name="boarding_station" type="radio" value="a_city" <?php if (isset($this->applicant->boarding_station)) {
                echo ('a_city' == strtolower($this->applicant->boarding_station)?'checked="checked"':'');
            } else {echo 'checked="checked"';} ?> title="Ambala City">Ambala City</label></li>
            <li><label><input name="boarding_station" type="radio" value="a_cant" <?php echo ('a_cant' == strtolower($this->applicant->boarding_station)?'checked="checked"':'');?> title="Ambala Cantt"> Ambala Cantt</label></li>
            <li><label><input name="boarding_station" type="radio" value="shabad" <?php echo ('shabad' == strtolower($this->applicant->boarding_station)?'checked="checked"':'');?> title="Shahabad"> Shahabad</label></li>
            <li><label><input name="boarding_station" type="radio" value="saha" <?php echo ('saha' == strtolower($this->applicant->boarding_station)?'checked="checked"':'');?> title="Saha/Mithapur"> Saha/Mithapur</label></li>
            <li><label><input name="boarding_station" type="radio" value="kkr" <?php echo ('kkr' == strtolower($this->applicant->boarding_station)?'checked="checked"':'');?> title="Kurukshetra"> Kurukshetra</label></li>
          </ul>
          <p class="formHint">Bus Facility</p>
        </div>
        
        <div id="submitStatus" style="display:none; padding: 1em;" class="ui-state-highlight ui-corner-all" ></div>
      
      	<div class="buttonHolder">
            <button type="submit" class="secondaryAction">Cancel and go back</button>
            <button type="submit" class="primaryAction">Submit</button>
    	</div>
</form>

	<script>
	var urlAddressInfo = "<?php echo $this->url(array('controller' => 'applicationform', 'action' => 'set'.$this->steps[$this->stepNo]))?>";
      $(function(){
        $('form.uniForm').uniform({
          prevent_submit : true
        });

        $("#c_state").autocomplete({
            source: '/location/getstates'
        });



        $("#hostel").click(function(){
            if ($(this).is(':checked')) {
            	$(this).val(true);
                $( "#hostelDiv").slideDown();
			} else {
				$(this).val(false);
                $( "#hostelDiv" ).slideUp('slow');
			}
		});

        $("#bus").click(function(){
            if ($(this).is(':checked')) {
            	$(this).val(true);
                $( "#busDiv" ).slideDown();
            	
			} else {
				$(this).val(false);
                $( "#busDiv" ).slideUp('slow');
			}
            
		});
		
        $(function() {
    		$( "#progressbar" ).progressbar({
    			value: <?php echo (100/count($this->steps))*($this->stepNo+1); ?>
    		});
    	});



    	
      });


      function submit() {
          $.ajax({
              url : urlAddressInfo,
              data : getValues(),
              success: function(jStatus){
                  $( "#submitStatus" ).html(jStatus).slideDown('slow', function(){
                    	setTimeout(function(){
                    		window.location = "/applicationform/<?php echo $this->steps[$this->stepNo+1];?> ";
                        	},10000);
                  }).append('<br/><a href="/applicationform/<?php echo $this->steps[$this->stepNo-1];?>" >&lt;&lt;PREV</a>:<a href="/applicationform/<?php echo $this->steps[$this->stepNo+1];?>" >NEXT&gt;&gt;</a>');

              },
                  error: function(response) {
                	  $('#errorBox').text(response.responseText).parent().show();
                      console.log(response);
                      }
                  });
      }
      
      function getValues() {
          var formData = {}; 
          $('form.uniForm :input')
          		.not('button,input:radio')
          		.each(function(){ 
          			formData[this.name] = this.value; 
              });

          if ('true' == $('#bus').val()) {
        	  var boarding_station = $('input:radio[name=boarding_station]:checked').val();
              formData.boarding_station = boarding_station;
          } else {
              formData.boarding_station = null;
          }
          
		return formData;
	}
    </script>
<?php
$this->headScript()->appendFile('http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
    
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/smooth.uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/demos/css/demo.css');
?>