   
    <!--[if lte ie 7]>
      <style type="text/css" media="screen">
        /* Move these to your IE6/7 specific stylesheet if possible */
        .uniForm, .uniForm fieldset, .uniForm .ctrlHolder, .uniForm .formHint, .uniForm .buttonHolder, .uniForm .ctrlHolder ul{ zoom:1; }
      </style>
    <![endif]-->
<div id="progressbar"></div>

    <form action="javascript:submit();" class="uniForm">
        <h2><?php $stepNo = 0;
        echo ucfirst($this->steps[$stepNo]);?> Information:</h2>
        <hr/>
        <div class="ctrlHolder noLabel">
          <ul class="alternate">
            <li><label for=""><em>*</em> First Name</label>
          <input name="first_name" id="first_name" data-default-value="e.g. Ravi" value="<?php echo $this->applicant->first_name ?>" size="10" maxlength="50" type="text" class="textInput required"/></li>
            <li><label for=""> Middle Name</label>
          <input name="middle_name" id="middle_name" data-default-value="e.g. Kumar" value="<?php echo $this->applicant->middle_name ?>"  size="10" maxlength="50" type="text" class="textInput"/></li>
            <li><label for=""> <em>*</em>Last Name</label>
          <input name="last_name" id="last_name" data-default-value="e.g. Gupta" value="<?php echo $this->applicant->last_name ?>"  size="10" maxlength="50" type="text" class="textInput required"/></li>
          </ul>
          <p class="formHint">Full Name of candidate</p>
        </div>
        
        <div class="ctrlHolder">
          <label for=""><em>*</em>Date of Birth</label>
          <input name="dob" id="dob" data-default-value="1990-12-31" value="<?php echo $this->applicant->dob ?>"  size="35" maxlength="50" type="text" readonly="readonly" class="textInput required"/>
          <p class="formHint">Birthday of <span class="cName" >Candidate</span></p>
        </div>
        
        <div class="ctrlHolder">
          <p class="label">Gender</p>
          <ul class="blockLabels alternate">
            <li><label for=""><input name="gender" type="radio" value="M" <?php if (isset($this->applicant->gender)) {
                echo ('m' == strtolower($this->applicant->gender)?'checked="checked"':'');
            } else {echo 'checked="checked"';} ?> title="Male">Male</label></li>
            <li><label for=""><input  name="gender" type="radio" value="F" <?php echo ('f' == strtolower($this->applicant->gender)?'checked="checked"':'');?> title="Female">Female</label></li>
          </ul>
          <p class="formHint">Gender</p>
        </div>
      
        <div class="ctrlHolder">
          <label for="">Nationality</label>
          <select id="nationality_id" name="nationality_id" class="selectInput">
          		<option value="1" <?php echo (1 == $this->applicant->nationality_id?'selected="selected"':'');?> >INDIAN</option>
          		<option value="2" <?php echo (2 == $this->applicant->nationality_id?'selected="selected"':'');?> >NRI</option>
  		  </select>
          <p class="formHint">Nationality</p>
        </div>
        
      
        <div class="ctrlHolder">
          <label for="">Blood Group</label>
          <select id="blood_group_id" name="blood_group_id" class="selectInput">
          		<option value="A+" <?php echo ("a+" == strtolower($this->applicant->blood_group_id)?'selected="selected"':'');?> >A+</option>
          		<option value="A-" <?php echo ("a-" == strtolower($this->applicant->blood_group_id)?'selected="selected"':'');?> >A-</option>
          		<option value="B+" <?php echo ("b+" == strtolower($this->applicant->blood_group_id)?'selected="selected"':'');?> >B+</option>
          		<option value="B-" <?php echo ("b+" == strtolower($this->applicant->blood_group_id)?'selected="selected"':'');?> >B-</option>
          		<option value="AB+" <?php echo ("ab+" == strtolower($this->applicant->blood_group_id)?'selected="selected"':'');?> >AB+</option>
          		<option value="AB-" <?php echo ("ab-" == strtolower($this->applicant->blood_group_id)?'selected="selected"':'');?> >AB-</option>
          		<option value="O+" <?php echo ("o+" == strtolower($this->applicant->blood_group_id)?'selected="selected"':'');?> >O+</option>
          		<option value="O-" <?php echo ("o-" == strtolower($this->applicant->blood_group_id)?'selected="selected"':'');?> >O-</option>
      	  </select>
          <p class="formHint">Blood group of <span class="cName" >Candidate</span></p>
        </div>
        
        
        <div class="ctrlHolder">
          <label for="">Religion</label>
          <select id="religion_id" name="religion_id" class="selectInput required">
          		<option value="1" <?php echo (1 == $this->applicant->religion_id?'selected="selected"':'');?> >Hindu</option>
          		<option value="2" <?php echo (2 == $this->applicant->religion_id?'selected="selected"':'');?> >Muslim</option>
          		<option value="3" <?php echo (3 == $this->applicant->religion_id?'selected="selected"':'');?> >Sikh</option>
          		<option value="4" <?php echo (4 == $this->applicant->religion_id?'selected="selected"':'');?> >Christian</option>
      	  </select>
          <p class="formHint">Religion of <span class="cName" >Candidate</span></p>
        </div>
        
        <div class="ctrlHolder">
          <label for="">Email address</label>
          <input name="e_mail" id="e_mail" value="<?php echo $this->applicant->e_mail ?>" data-default-value="e.g. ravigupta@gmail.com"  size="35" maxlength="50" type="text" class="textInput validateEmail"/>
          <p class="formHint">A valid email address</p>
        </div>
      
        <div class="ctrlHolder">
          <label for="">Email confirm</label>
          <input name="e_mail_confirm" id="e_mail_confirm" data-default-value="i.e. same as above" value="<?php echo $this->applicant->e_mail ?>"  size="35" maxlength="50" type="text" class="textInput validateSameAs e_mail"/>
          <p class="formHint"></p>
        </div>
        
        <fieldset>
        <h3>Parent/Guardian Information</h3>
        <div class="ctrlHolder">
          <label for=""><em>*</em> Landline No.</label>
          <input name="landline_no" id="landline_no" value="<?php echo $this->applicant->landline_no ?>"  data-default-value="e.g. 017226544331" size="35" maxlength="12" type="text" class="textInput validateInteger"/>
          <p class="formHint">Landline number, if available.</p>
        </div>
        <div class="ctrlHolder">
          <label for=""><em>*</em> Father's name</label>
          <input name="father_name" id="father_name" data-default-value="e.g. Sh. Madan Kumar" value="<?php echo $this->applicant->father_name ?>"  size="35" maxlength="50" type="text" class="textInput required"/>
          <p class="formHint">Father's name of <span class="cName" >Candidate</span></p>
        </div>
        
        <div class="ctrlHolder">
          <label for="">Father's occupation</label>
          <input name="father_occupation" id="father_occupation" value="<?php echo $this->applicant->father_occupation ?>" data-default-value="e.g. Civil Engineer (Govt.)" size="35" maxlength="50" type="text" class="textInput"/>
          <p class="formHint">Father's occupation</p>
        </div>
        
        <div class="ctrlHolder">
          <label for=""><em>*</em> Father's contact</label>
          <input name="father_contact" id="father_contact" value="<?php echo $this->applicant->father_contact ?>"  data-default-value="e.g. 9416123494" size="35" maxlength="12" type="text" class="textInput validateInteger"/>
          <p class="formHint">Father's contact number, it should be a mobile number.</p>
        </div>
        
        <div class="ctrlHolder">
          <label for="">Father's Office Address</label>
          <textarea name="father_office_add" id="father_office_add" data-default-value="e.g. PWD B and R Office, Near SDM office, Narnaul"  class="validatePhrase"  rows="25" cols="25"><?php echo $this->applicant->father_office_add ?></textarea>
          <p class="formHint">Father's Office Address</p>
        </div>
        <div class="ctrlHolder">
          <label for=""><em>*</em> Mother's name</label>
          <input name="mother_name" id="mother_name" value="<?php echo $this->applicant->mother_name ?>"  data-default-value="e.g. Smt. Sita Devi" size="35" maxlength="50" type="text" class="textInput required"/>
          <p class="formHint">Mother's name of <span class="cName" >Candidate</span></p>
        </div>
        
        <div class="ctrlHolder">
          <label for="">Mother's occupation</label>
          <input name="mother_occupation" id="mother_occupation" value="<?php echo $this->applicant->mother_occupation ?>" data-default-value="e.g. Housewife" size="35" maxlength="50" type="text" class="textInput"/>
          <p class="formHint">Mother's occupation</p>
        </div>
        
        <div class="ctrlHolder">
          <label for="">Mother's Office Address</label>
          <textarea name="mother_office_add" id="mother_office_add" data-default-value="e.g. H.no. 3, PWD B and R Colony, Near Old court"  class="validatePhrase"  rows="25" cols="25"><?php echo $this->applicant->mother_office_add ?></textarea>
          <p class="formHint">Mother's Office Address (if applicable)</p>
        </div>
        <div class="ctrlHolder">
          <label for="">Guardian's name (if any)</label>
          <input name="guardian_name" id="guardian_name" value="<?php echo $this->applicant->guardian_name ?>" data-default-value="e.g. Sh. Ravi Dutt" size="35" maxlength="50" type="text" class="textInput"/>
          <p class="formHint">Guardian's name, if <span class="cName" >Candidate</span> is not with parents.</p>
        </div>
        
        <div class="ctrlHolder">
          <label for="">Guardian's relation</label>
          <input name="guardian_relation" id="guardian_relation" value="<?php echo $this->applicant->guardian_relation ?>" data-default-value="e.g. Uncle" size="35" maxlength="50" type="text" class="textInput validatePhrase"/>
          <p class="formHint">Guardian's relationship with <span class="cName" >Candidate</span></p>
        </div>
        
        <div class="ctrlHolder">
          <label for="">Guardian's contact number</label>
          <input name="guardian_contact" id="guardian_contact" value="<?php echo $this->applicant->guardian_contact ?>" data-default-value="e.g. +919799123132" size="35" maxlength="50" type="text" class="textInput"/>
          <p class="formHint">Guardian's contact number, it should be a mobile number.</p>
        </div>
        
        <div class="ctrlHolder">
          <label for=""><em>*</em>Annual Income</label>
          <input name="annual_income" id="annual_income" value="<?php echo $this->applicant->annual_income ?>" data-default-value="e.g. 456000" size="35" maxlength="50" type="text" class="textInput required validateInteger"/>
          <p class="formHint">Annual Income of father or guardian.(in Rupees only, no comma or units etc.)</p>
        </div>
        
        </fieldset>
        
        <div id="submitStatus" style="display:none;padding: 1em;" class="ui-state-highlight ui-corner-all" ></div>
        
        <div class="buttonHolder">
        	<button type="submit" class="secondaryAction">Cancel and go back</button>
        	<button type="submit" class="primaryAction">Submit</button>
    	</div>

    </form>
	<script>
	var urlBasicInfo = "<?php 
	echo $this->url(array('controller' => 'applicationform', 'action' => 'set'.$this->steps[$stepNo]))?>";
      $(function(){
        $('form.uniForm').uniform({
          prevent_submit : true
        });

        serverDateObj = $.datepicker.parseDate('dd-mm-yy', $('#datetext').text());
        $("#dob").datepicker({
        	dateFormat: 'yy-mm-dd',
        	changeMonth: true,
			changeYear: true,
			yearRange: '-25:-15',
			onClose : function(dateText, inst) {
				this.focus();
				}
        });

        $('#first_name').change(function(){
            var cName = this.value;
        	$('.cName').text(cName);
        });
        $(function() {
    		$( "#progressbar" ).progressbar({
    			value: <?php echo (100/count($this->steps))*($stepNo+1); ?>
    		});
    	});
      });

      function submit() {
          $.ajax({
              url : urlBasicInfo,
              data : getValues(),
              success: function(jStatus){
                  $( "#submitStatus" ).html(jStatus).slideDown('slow', function(){
                    	setTimeout(function(){
                    		window.location = "/applicationform/<?php echo $this->steps[$stepNo+1]?>";
                        	},10000);
                    }).append('<br/><a href="/applicationform/<?php echo $this->steps[$stepNo+1];?>" >NEXT&gt;&gt;</a>');
              },
                  error: function(response) {
                	  $('#errorBox').text(response.responseText).parent().show();
                      console.log(response);
                      }
                  });
      }

        function getValues() {
            var formData = {}; 
            $('form.uniForm :input')
            		.not('button,#e_mail_confirm,:input[value^="e.g."]')
            		.each(function(){ 
            			formData[this.name] = this.value; 
                });
        var gender = $('input:radio[name=gender]:checked').val();
        formData.gender = gender; 
  		return formData;
  	}
    </script>
<?php
$this->headScript()->appendFile('http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
    
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/smooth.uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/demos/css/demo.css');
?>