
<!--[if lte ie 7]>
      <style type="text/css" media="screen">
        /* Move these to your IE6/7 specific stylesheet if possible */
        .uniForm, .uniForm fieldset, .uniForm .ctrlHolder, .uniForm .formHint, .uniForm .buttonHolder, .uniForm .ctrlHolder ul{ zoom:1; }
      </style>
    <![endif]-->

<link rel="stylesheet" type="text/css" href="<?php echo 'http://' . CDN_SERVER . '/plugins/photobooth/assets/css/styles.css'?>" />
<link rel="stylesheet" type="text/css" href="<?php echo 'http://' . CDN_SERVER . '/plugins/photobooth/assets/fancybox/jquery.fancybox-1.3.4.css'?>" />

<div id="progressbar"></div>
<form action="javascript:submit();" class="uniForm">
<h2><?php $stepNo = $this->stepNo;
 echo 'Step '.($stepNo+1).'/'.count($this->steps).': '.ucfirst($this->steps[$this->stepNo]);?>:</h2>
<hr />
</form>

<input id="rollno" type="hidden" value="<?php echo $this->applicant->roll_no ?>"> 

<div id="photos"></div>

<div id="camera">
	<span class="tooltip"></span>
	<span class="camTop"></span>
    
    <div id="screen"></div>
    <div id="buttons">
    	<div class="buttonPane">
        	<a id="shootButton" href="" class="blueButton">Shoot!</a>
        </div>
        <div class="buttonPane hidden">
        	<a id="cancelButton" href="" class="blueButton">Cancel</a> <a id="uploadButton" href="" class="greenButton">Upload!</a>
        </div>
    </div>
    
    <span class="settings"></span>
</div>

<form id="next_button" action="javascript:submit();">
	<input type="submit" value="Next">
</form>

<script type="text/javascript">
function submit() {
	var urlAcadmicInfo = "<?php echo $this->url(array('controller' => 'applicationform', 'action' => 'set'.$this->steps[$stepNo]))?>";
    $.ajax({
        url : urlAcadmicInfo,
        success: function(jStatus){
            /*$( "#submitStatus" ).html(jStatus).slideDown('slow', function(){
              	setTimeout(function(){
              		window.location = "/applicationform/<?php echo $this->steps[$stepNo+1];?> ";
                  	},10000);
            }).append('<br/><a href="/applicationform/<?php echo $this->steps[$stepNo-1];?>" >&lt;&lt;PREV</a>:<a href="/applicationform/<?php echo $this->steps[$stepNo+1];?>" >NEXT&gt;&gt;</a>');
			*/
			var image_name = $("#photos>a").attr("id");
			alert(image_name);

			//window.location = "/applicationform/renameimage?image_name="+image_name;
			window.location = "/applicationform/<?php echo $this->steps[$stepNo+1]?>"+"?image_name=<?php echo $this->applicant->roll_no ?>";
        	
        	
        },
            error: function(response) {
          	  $('#errorBox').text(response.responseText).parent().show();
                console.log(response);
                }
            });
	}
</script>

<script src="<?php echo 'http://' . CDN_SERVER . '/plugins/photobooth/assets/fancybox/jquery.easing-1.3.pack.js'?>"></script>
<script src="<?php echo 'http://' . CDN_SERVER . '/plugins/photobooth/assets/fancybox/jquery.fancybox-1.3.4.pack.js'?>"></script>
<script src="<?php echo 'http://' . CDN_SERVER . '/plugins/photobooth/assets/webcam/webcam.js'?>"></script>
<script src="<?php echo 'http://' . CDN_SERVER . '/plugins/photobooth/assets/js/script.js'?>"></script>



<?php
$this->headScript()->appendFile('http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
    
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/smooth.uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/demos/css/demo.css');
?>