<div id="selection-div"class="ui-widget-content ui-corner-all" style="float:inherit; width:1000px; height:125px; padding:4px" >
<h3>
<label for="degree_select" accesskey="S" id="lbl_degree_id" style="padding: 0.4em; ">
Personal information
</label>
</h3><p><span style="float:left; ">Name:<?php echo $this->name;?></span>
<span style="float:right;  ">Degree:<?php echo $this->degree;?>
<br><br>Department:<?php echo $this->deptt;?><br><br>
Semester:<?php echo $this->sem;?></span>
<br><br><br><span style="float:left; ">Roll Number:<?php echo $this->rollno;?></span>
</p>
</div>