<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>:)</title>
  <style>
body {
    font-family: Arial,Helvetica,sans-serif;
    font-size: 14px;
    text-align: center;
}
.logout_page {
    margin: auto;
    width: 600px;
}
.logout_page h1 {
	margin: 0;
}
</style>
</head>
<body>
<div class="logout_page">
    <h1 >You have successfully logged out.</h1>
    <img src="http://<?php echo CDN_SERVER?>/images/activity/logout/1.jpg" alt="Smile">
    <p><ul style="font-size: 0.7em; " >
        <li>You can login from <a href="<?php echo 'http://'.AUTH_SERVER ?>/authenticate"><?php echo 'http://'.AUTH_SERVER ?>/authenticate</a></li>
        <li>Know latest about project <a href="http://code.google.com/p/eduis">here</a></li>
        <li>Contribute your suggestions, feature request, issues etc. <a href="http://code.google.com/p/eduis/issues/list">here</a></li>
        <li>Login to official mail account at <a href="http://mail.aceambala.com">mail.aceambala.com</a> for notices etc.</li>
</ul></p>
    <p><a href="<?php echo 'http://'.ACADEMIC_SERVER ?>">Return to the homepage</a></p>
</div>
</body>
</html>