<?php
    $department_id = $this->department_id;
    $CSE = array('A1','A2','A3');
    $ECE = array('B1','B2','B3');
    $BT = array('C1','C2','C3');
    $MECH = array('D1','D2','D3');
?>

<h2>Class Information:</h2>

<form action="javascript:getclass_id()" class="uniForm" id="class_info">
    <fieldset>

	<div class="ctrlHolder">
		<label for="department_id"><em>*</em>Department</label>
		<input name="department_id" id="department_id" value="<?php echo $department_id?>" readonly="readonly" size="35" disabled="disabled" maxlength="50" type="text" class="textInput required" />
		<p class="formHint">Your Trade</p>
	</div>

	<div class="ctrlHolder">
		<label for="programme_id"><em>*</em>Programme</label>
		<select id="programme_id" name="programme_id" class="required">
			<option value="">Select the programme</option>
		</select>
		<p class="formHint">Select the programme</p>
	</div>

	<div class="ctrlHolder">
		<label for="batch_start"><em>*</em>Batch Start</label>
		<select id="batch_start" name="batch_start" class="required">
			<option value="">Select the year</option>
			<?php
			    $current_year = intval(date('Y'));
			    for($i=2002;$i<=$current_year;$i++)
			    {
			        echo '<option value="'.$i.'">'.$i.'</option>';
			    }
			?>
		</select>
		<p class="formHint">Select the starting year of the batch</p>
	</div>

	<div class="ctrlHolder">
		<label for="semester_id"><em>*</em>Semester</label>
		<select id="semester_id" name="semester_id" class="required">
		<option value="">Select the semester</option>
		<?php 
		    for($i=1;$i<=8;$i++)
            {
                echo '<option value="'.$i.'">'.$i.'</option>';
            }
		?>
		</select>
		<p class="formHint">Select Department</p>
	</div>

	<div class="buttonHolder">
		<button type="reset" class="secondaryAction">Reset</button>
		<button type="submit" class="primaryAction">Next</button>
	</div>
	</fieldset>
</form>

<form action="javascript:submit_other_info()" class="uniForm" id="other_info">
	<fieldset>
	<div class="ctrlHolder">
		<label for="group_id"><em>*</em>Group</label>
		<select id="group_id" name="group_id" class="selectInput required">
			<?php 
			    foreach ($$department_id as $value) {
			        echo '<option value="'.$value.'">'.$value.'</option>';
			    }
			?>
		</select>
		<p class="formHint">Select Your Group</p>
	</div>

	<div class="ctrlHolder"><label for="roll_no"><em>*</em>Roll number</label>
		<input name="roll_no" id="roll_no" data-default-value="e.g. 2308015" size="35" maxlength="50" type="text" class="textInput required validateInteger" />
		<p class="formHint">Enter your University Roll Number</p>
	</div>
	</fieldset>

	<div id="submitStatus" style="display:none;padding: 1em;" class="ui-state-highlight ui-corner-all" ></div> 
	<div class="buttonHolder">
		<button type="reset" class="secondaryAction">Reset</button>
		<button type="submit" class="primaryAction">Next</button>
	</div>
</form>

<script>
	$('form#other_info').hide();
	var params = {};
	var class_id;
	$(function(){
		$('form.uniForm').uniform({
			prevent_submit : true
		});

	    var urlgetProgrammes = "http://core.aceambala.com/class/fetchprogrammes";
	    $.ajax({
    		url : urlgetProgrammes,
    		dataType : 'jsonp',
            data : {format:'jsonp'},
    		success: function(jStatus){
    			$.each(jStatus['programmes'],function(programme_id,programme_name){
					//alert(index +'   '+ semester);
					html_text = '<option value="'+programme_id+'">'+programme_name+'</option>';
					$('#programme_id').append(html_text);
    			});
            },
            error: function(response) {
				$('#errorBox').text(response.responseText).parent().show();
    			console.log(response);
    		}
		});
	});

	function getclass_info_params(){
		$('form#class_info :input').each(function(){
			params[this.name] = this.value;
		});
	}
	
    function get_batch_params(){
        var formData = {};
        var batch_params = {};
    
        batch_params['programme_id'] = params['programme_id'];
        batch_params['department_id'] = params['department_id'];
        batch_params['batch_start'] = params['batch_start'];
    	
    	formData['batch_params'] = batch_params; 
    	return formData;
    }

    function get_class_params(batch_id){
        var formData = {};
        var class_finder = {};
    
        class_finder['semester_id'] = params['semester_id'];
        class_finder['batch_id'] = batch_id;
    	
    	formData['class_finder'] = class_finder; 
    	return formData;
    }

    function getclass_id(){
        getclass_info_params();
    	var urlGetBatchIdsInfo = "<?php echo $this->url(array('controller' => 'batch', 'action' => 'getbatchids'))?>";
    	$.ajax({
    		url : urlGetBatchIdsInfo,
    		dataType : 'json',
    		data : {
        			myarray:get_batch_params(),
        			format : 'json'
            		},
    		success: function(jStatus){
					var batch_id = parseInt(jStatus);
					var urlGetClassIdsInfo = "<?php echo $this->url(array('controller' => 'class', 'action' => 'getclassids'))?>";
					$.ajax({
			    		url : urlGetClassIdsInfo,
			    		dataType : 'json',
			    		data : {
			        			myarray:get_class_params(batch_id),
			        			format : 'json'
			            		},
			    		success: function(jStatus){
								class_id = parseInt(jStatus);
								submit_class_info();
			        		},
			            error: function(response) {
							$('#errorBox').text(response.responseText).parent().show();
			    				console.log(response);
			    		}
					});
        		},
            error: function(response) {
				$('#errorBox').text(response.responseText).parent().show();
    				console.log(response);
    		}
		});

    }

    function get_class_values(){
        var formData = {};
        var class_info = {};
    
        class_info['semester_id'] = params['semester_id'];
        class_info['class_id'] = class_id;
    	
    	formData['class_info'] = class_info; 
    	return formData;
    }
    
    function submit_class_info() {
    	var urlSaveInfo = '<?php echo $this->url(array('controller' => 'student', 'action' => 'fetchclassinfo'))?>';
        $.ajax({
            url : urlSaveInfo,
            data : {
                	myarray : get_class_values(),
					format : 'json'
                	},
            success: function(jStatus){
                $('form#class_info').hide();
                $('form#other_info').show();
                $.each(jStatus,function(key,value){
                    var field = '#'+key; 
					$(field).val(value);
                });
            },
    		error: function(response) {
    			$('#errorBox').text(response.responseText).parent().show();
    			console.log(response);
    		}
    	});
    }

	function get_other_params()
	{
		formData = {};
		class_info = {};
		$('form#other_info :input')
		.not('button')
		.each(function(){
			class_info[this.name] = this.value;
		});
		class_info['class_id'] = class_id;

		formData['class_info'] = class_info;
		return formData;
	}
    
    function submit_other_info()
    {
        var data = get_other_params();
    	var urlSaveInfo = '<?php echo $this->url(array('controller' => 'student', 'action' => 'saveclassinfo'))?>';
        $.ajax({
            url : urlSaveInfo,
            async : false,
            data : {
                	myarray : data,
					format : 'json'
                	},
            success: function(jStatus){
                submit_in_acad(data);
            },
    		error: function(response) {
    			$('#errorBox').text(response.responseText).parent().show();
    			console.log(response);
    		}
    	});
    }

    function submit_in_acad(data)
    {
    	var urlSaveInfo = 'http://academic.aceambala.com/student/saveclassinfo';
        $.ajax({
            url : urlSaveInfo,
            async : false,
            dataType : 'jsonp',
            data : {
                	myarray : data,
					format : 'jsonp'
                	},
            success: function(jStatus){
                submit_in_tnp(data);
            },
    		error: function(response) {
    			$('#errorBox').text(response.responseText).parent().show();
    			console.log(response);
    		}
    	});
    }

    function submit_in_tnp(data)
    {
    	var urlSaveInfo = 'http://tnp.aceambala.com/student/saveclassinfo';
        $.ajax({
            url : urlSaveInfo,
            async : false,
            dataType : 'jsonp',
            data : {
                	myarray : data,
					format : 'jsonp'
                	},
            success: function(jStatus){
				window.location.replace('/student/viewclassinfo');
            },
    		error: function(response) {
    			$('#errorBox').text(response.responseText).parent().show();
    			console.log(response);
    		}
    	});
    }
    
</script>

<style type="text/css">
.uniForm{
	background-color:white;
	padding:10px 10px 10px 25px;
	border:1px solid #b4c1da;
	margin:-5px 0 40px 0;
	box-shadow:#e4e4e4 0px 0px 1px 1px;
	width:auto;
}
h2{
	padding:3px 3px 3px 10px;
	background-color:#eceff4;
	border:1px solid #b4c1da;
	font-size:17px;
	font-weight:100;
	margin-top:2px;	
}
span{
	float:right;
	font-size:14px;
	font-weight:100;	
}
</style>
    
    
<?php
$this->headScript()->appendFile('http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
    
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/smooth.uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/demos/css/demo.css');
?>