<?php 
    $class_info = $this->class_info;
    
    $CSE = array('A1','A2','A3');
    $ECE = array('B1','B2','B3');
    $BT = array('C1','C2','C3');
    $MECH = array('D1','D2','D3');
    
    if(Zend_Auth::getInstance()->hasIdentity()){
		$authInfo = Zend_Auth::getInstance()->getStorage()->read();
		$usertype=$authInfo['userType'];
	}
?>

<h2>Class Information:</h2>

<form action="javascript:submit_info_in_core()" class="uniForm">
    <fieldset id="class_info">

	<div class="ctrlHolder">
		<label for="department_id"><em>*</em>Department</label>
		<input name="department_id" id="department_id" value="<?php echo $class_info['department_id']?>" readonly="readonly" size="35" disabled="disabled" maxlength="50" type="text" class="textInput required" />
		<p class="formHint">Your Trade</p>
	</div>

	<div class="ctrlHolder">
		<label for="programme_id"><em>*</em>Programme</label>
		<input name="programme_id" id="programme_id" value="<?php echo $class_info['programme_id']?>" readonly="readonly" size="35" disabled="disabled" maxlength="50" type="text" class="textInput required" />
		<p class="formHint">Select the programme</p>
	</div>
	
	<div class="ctrlHolder">
		<label for="batch_start"><em>*</em>Batch Start</label>
		<input name="batch_start" id="batch_start" value="<?php echo $class_info['batch_start']?>" readonly="readonly" size="35" disabled="disabled" maxlength="50" type="text" class="textInput required" />
		<p class="formHint">Select the starting year of the batch</p>
	</div>
	
	<?php
	    if($usertype == 'STU')
	    {
	        echo '<h4>Please check the semester in which you are enrolled</h4>';
	        echo '<h4>Note : Please donot select the semesters in which you are not enrolled. This information cannot be edited at later stage. If you make any mistake you have to contact your respective HOD.</h4>';
	    }
	    else
	    {
	        echo '<h4>Please check the semester in which you are enrolled</h4>';
	        echo '<h4>Note : Please be carefull while filling this form. Deselecting on a semster in which a student is already enrolled may delete all of his information.</h4>';
	    }
	    for($i=1;$i<=8;$i++)
        {
            echo '<div class="ctrlHolder">';
		    echo '<label for="sem_'.$i.'"></label>';
		    echo 'Semester '.$i.'<input name="sem_'.$i.'" id="sem_'.$i.'" size="35" maxlength="50" type="checkbox" class="checkbox"/>';
		    echo '<p class="formHint">Click if you are enrolled in semester '.$i.'</p>';
            echo '</div>';
        }
    ?><br>
	

	<div class="ctrlHolder">
		<label for="group_id"><em>*</em>Group</label>
		<select id="group_id" name="group_id" class="selectInput required">
			<?php 
			    foreach ($$class_info['department_id'] as $value) {
			        echo '<option value="'.$value.'">'.$value.'</option>';
			    }
			?>
		</select>
		<p class="formHint">Select Your Group</p>
	</div>

	<div class="ctrlHolder"><label for="roll_no"><em>*</em>Roll number</label>
		<input name="roll_no" id="roll_no" value="<?php echo $class_info['roll_number'];?>" data-default-value="e.g. 2308015" size="35" maxlength="50" type="text" class="textInput required validateInteger" />
		<p class="formHint">Enter your University Roll Number</p>
	</div>
	</fieldset>

	<div id="submitStatus" style="display:none;padding: 1em;" class="ui-state-highlight ui-corner-all" ></div> 
	<div class="buttonHolder">
		<button type="reset" class="secondaryAction">Reset</button>
		<button type="submit" class="primaryAction">Next</button>
	</div>
</form>

<script>
	$(function(){
		$('form.uniForm').uniform({
			prevent_submit : true
		});

	    var urlgetProgrammes = "http://core.aceambala.com/class/fetchprogrammes";
	    $.ajax({
    		url : urlgetProgrammes,
    		dataType : 'jsonp',
            data : {format:'jsonp'},
    		success: function(jStatus){
    			$.each(jStatus['programmes'],function(programme_id,programme_name){
					html_text = '<option value="'+programme_id+'">'+programme_name+'</option>';
					
					$('#programme_id').append(html_text);
    			});
            },
            error: function(response) {
				$('#errorBox').text(response.responseText).parent().show();
    			console.log(response);
    		}
		});

		$('#group_id').val('<?php echo $class_info['group_id']?>');

		<?php 
		    foreach ($class_info['semsters_added'] as $i)
		    {
                echo "$('#sem_".$i."').attr('checked',true);";   
		    }
		    
		    if($usertype == 'STU')
    	    {
    	        echo "$('#sem_".$i."').attr('readonly','readonly');";
    	    }
		?>
	});
	
	function get_params()
	{
		var class_info = {};
		$('fieldset#class_info :input')
    	.not('button,:input[value^="e.g."]')
    	.not(':input[type="checkbox"]')
    	.each(function(){ 
    		class_info[this.name] = this.value;
    	});
    	
    	var semesters_added = new Array();

    	for(var i=1; i<=8; i++)
    	{
    		if($('#sem_'+i).is(':checked'))
        		semesters_added.push(i);
    	}
    	class_info['semesters_added'] = semesters_added;

    	<?php 
    	if($usertype == 'STU')
	    {
	        echo "class_info['semesters_deleted'] = false;";
	    }
	    else
	    {
	        foreach ($class_info['semesters_added'] as $value)
	        {
                echo "if(!$('sem_".$value."').is(':checked'))";
                echo '{';
                    echo 'var semesters_deleted = new Array();';
                    echo 'semesters_deleted.push('.$value.');';
                echo '}';
                
                echo "class_info['semesters_deleted'] = semesters_deleted;";
	        }
	    }
	    ?>
    	
		
    	return class_info;
	}
    
    function submit_info_in_core()
    {
        var data = get_params();
    	var urlSaveInfo = '<?php echo $this->url(array('controller' => 'student', 'action' => 'saveclassinfo'))?>';
        $.ajax({
            url : urlSaveInfo,
            async : false,
            data : {
                myarray : {class_info : data},
				format : 'json'
			},
            success: function(class_info){
                submit_in_acad(class_info);
            },
    		error: function(response) {
    			$('#errorBox').text(response.responseText).parent().show();
    			console.log(response);
    		}
    	});
    }

    function submit_in_acad(class_info)
    {
    	var urlSaveInfo = 'http://academic.aceambala.com/student/saveclassinfo';
        $.ajax({
            url : urlSaveInfo,
            async : false,
            dataType : 'jsonp',
            data : {
                	class_info : class_info,
					format : 'jsonp'
                	},
            success: function(jStatus){
                if(jStatus == true)
                	submit_in_tnp(class_info);
            },
    		error: function(response) {
    			$('#errorBox').text(response.responseText).parent().show();
    			console.log(response);
    		}
    	});
    }

    function submit_in_tnp(class_info)
    {
    	var urlSaveInfo = 'http://tnp.aceambala.com/student/saveclassinfo';
        $.ajax({
            url : urlSaveInfo,
            async : false,
            dataType : 'jsonp',
            data : {
            		class_info : class_info,
					format : 'jsonp'
                	},
            success: function(jStatus){
				window.parent.location.replace('/student/');
            },
    		error: function(response) {
    			$('#errorBox').text(response.responseText).parent().show();
    			console.log(response);
    		}
    	});
    }
    
</script>

<style type="text/css">
.uniForm{
	background-color:white;
	padding:10px 10px 10px 25px;
	border:1px solid #b4c1da;
	margin:-5px 0 40px 0;
	box-shadow:#e4e4e4 0px 0px 1px 1px;
	width:auto;
}
h2{
	padding:3px 3px 3px 10px;
	background-color:#eceff4;
	border:1px solid #b4c1da;
	font-size:17px;
	font-weight:100;
	margin-top:2px;	
}
span{
	float:right;
	font-size:14px;
	font-weight:100;	
}
</style>
    
    
<?php
$this->headScript()->appendFile('http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
    
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/smooth.uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/demos/css/demo.css');
?>