<?php
    $departments = array('BT' => 'Biotechnology', 'CSE' => 'Computer Science', 'MECH' => 'Mechanical', 'ECE' => 'Electronics and Communication');
    $department_id = $this->department_id;
    $student_class_info = $this->student_class_info;
    $batch_class=$this->batch_class;
?>

<div class="ui-state-hover"><center><H3>Class Information</H3></center></div>
<div class="info" id="class_info">
	<table id="info_table" style="width: 100%" cellspacing="6" cellpadding="6">
		<tr>
			<td><span id="heading">Department</span><span id="content"><?php echo $departments[$department_id]?></span></td>
		</tr>
		<?php
		    if($student_class_info != false)
		    {
                foreach ($student_class_info as $key => $value) {
                    echo '<tr>';
                        echo '<td>';
                        echo '<span id="heading">Batch Year</span><span id="content">'.$key.'</span><br><span id="heading">Roll Number</span><span id="content">'.$value.'</span><br>';
                        echo '<input type="button" value="Edit" onclick = "window.location.replace('."'".'/student/editclassinfo?batch_start='.$key."'".')"> ';
                        echo ' <input type="button" value="Delete" onclick = "window.location.replace('."'".'/student/deleteclassinfo?class_id='.$batch_class[$key]."'".')">';
                        echo '</td>';
                    echo '</tr>';
                }
		    }
        ?>
	</table>
</div>

<script>

	$(function(){
    	$('#topContent').hide();
	    var urlgetProgrammes = "http://core.aceambala.com/class/fetchprogrammes";
	    $.ajax({
    		url : urlgetProgrammes,
    		dataType : 'jsonp',
            data : {format:'jsonp'},
    		success: function(jStatus){
    			if((jStatus == null) || (jStatus == false)|| (jStatus == undefined))
    			{
    				$('#info_table').append('No information has been added yet.');
    			}
    			else
    			{
        			$.each(jStatus['programmes'],function(programme_id,programme_name){
    					html_text = '<option value="'+programme_id+'">'+programme_name+'</option>';
    					$('#programme_id').append(html_text);
        			});
    			}
            },
            error: function(response) {
				$('#errorBox').text(response.responseText).parent().show();
    			console.log(response);
    		}
		});
	});
    
</script>

<style type="text/css">
	.info
	{
		font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
		font-size: 14px;
		margin: 15px;
		text-align: left;
		border-collapse: collapse;
	}
	td span#heading{
		color:red;
		font-size:0.9em;
	}
	td span#content{
		float:right;
		font-size:0.9em;
	}
	table {
      	border-color: #c20f2e;
		width:97%;
	}
	td{
		border-bottom:1px dashed #999;
	}
	tr.heading{
		color:black;
		font-size: 1.3em;
		background-color: #F7F7F7;
		border:1px solid black;
	}
	tr.heading td{
		border:none;
	}
}
</style>