<div class="ui-state-hover"><center><H3>Relatives Information</H3></center></div>
<div class="info" id="relative_info">
	<table id="info_table" style="width: 100%" cellspacing="5" cellpadding="5">
		
	</table>
</div>

<script type="text/javascript">

    var relations = { 1:'Father', 2:'Mother', 3: 'Guardian'};
    $(function(){
    	$('#topContent').hide();
        var urlgetinfo = "<?php echo $this->url(array('controller' => 'student', 'action' => 'fetchrelativesinfo'))?>";
        $.ajax({
    		url : urlgetinfo,
    		dataType : 'json',
            data : {format:'json'},
            success: function(jStatus){
            	if((jStatus == null) || (jStatus == false)|| (jStatus == undefined))
    			{
    				$('#info_table').append('No information has been added yet.');
    			}
                else
                {
        			var html = '';
        			$.each(jStatus,function(relation_type,data){
            			html += '<tr class="heading"><td>'+relations[relation_type]+'</td></tr>';
            			html += '<tr class="row"><td><span id="heading">Name</span><span id="content">'+data['name']+'</span></td></tr>';
            			html += '<tr class="row"><td><span id="heading">Contact Number</span><span id="content">'+data['contact']+'</span></td></tr>';
            			html += '<tr class="row"><td><span id="heading">Occupation</span><span id="content">'+data['occupation']+'</span></td></tr>';
            			if(data['designation'] != undefined)
            				html += '<tr class="row"><td><span id="heading">Designation</span><span id="content">'+data['designation']+'</span></td></tr>';
            			html += '<tr class="row"><td><span id="heading">Office Address</span><span id="content">'+data['office_add']+'</span></td></tr>';
            			html += '<tr class="row"><td><span id="heading">Landline Number</span><span id="content">'+data['landline_no']+'</span></td></tr>';
        			});
        			$('#info_table').append(html);
                }
            },
            error: function(response) {
    			$('#errorBox').text(response.responseText).parent().show();
    			console.log(response);
    		}
    	});
    });
</script>

<style type="text/css">
	.info
	{
		font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
		font-size: 14px;
		margin: 15px;
		text-align: left;
		border-collapse: collapse;
	}
	td span#heading{
		color:red;
		font-size:0.9em;
	}
	td span#content{
		float:right;
		font-size:0.9em;
	}
	table {
      	border-color: #c20f2e;
		width:97%;
	}
	td{
		border-bottom:1px dashed #999;
	}
	tr.heading{
		color:black;
		font-size: 1.3em;
		background-color: #F7F7F7;
		border:1px solid black;
	}
	tr.heading td{
		border:none;
	}
}
</style>