<style type="text/css">
#personal_details label {
	padding: 0.1em;
}

span {
	color: #444444;
	font-weight: normal;
}</style>
<script>
	$(function() {
		$( "#tabs" ).tabs();
	});
	</script>


<center><h1>Personal Profile</h1></center>
<div id="tabs">
	<ul>
		<li><a href="#tabs-1">Basic Information</a></li>
		<li><a class="relative_data" href="#tabs-2">Relatives Information</a></li>
		<li><a class="address" href="#tabs-3">Contact Details</a></li>
	</ul>
	<div id="tabs-1">
	</div>
	<div id="tabs-2">
	</div>
	<div id="tabs-3">
		
	</div>
<table style="width: 100%">
		<?php 
		        
			foreach ($this->critical_data as $key => $value) {
    		echo '<tr>';
    		echo '<td>'.ucfirst(str_replace('_', ' ', str_replace("_id", '',$key))).'</td>';
    		echo '<td>'.ucfirst($value).'</td>';
    		echo '</tr>';
          //echo $key." ".$value."</br>";
    
}
?>
	</table>
	<table style="width: 100%">
	<center><h2>Relative Information</h2></center>
	<?php 
	foreach ($this->relative_data as $key => $array){
	    echo '<tr>';
	    echo '<th>'.ucfirst($key).'</th>';
	    echo '</tr>';
	    echo '<br>';
	    foreach ($array as $param => $value) {
	        echo '<tr>';
    		echo '<td>'.ucfirst(str_replace('_', ' ', str_replace("_id", '',$param))).'</td>';
    		echo '<td>'.ucfirst($value).'</td>';
    		echo '</tr>';
	    }
	    
	}
	
	
	?>
	
	</table>
	<table style="width: 100%">
	<center><h2>Contact Information</h2></center>
	<?php 
	foreach ($this->address as $key => $array){
	    echo '<tr>';
	    echo '<th>'.ucfirst($key).'</th>';
	    echo '</tr>';
	    echo '<br>';
	    foreach ($array as $param => $value) {
	        echo '<tr>';
    		echo '<td>'.ucfirst(str_replace('_', ' ', str_replace("_id", '',$param))).'</td>';
    		echo '<td>'.ucfirst($value).'</td>';
    		echo '</tr>';
	    }
	    
	}
	
	
	?>
	
	</table>
	
</div>
