<div class="ui-state-hover"><center><H3>Contact Information</H3></center></div>
<div class="info" id="address_info">
	<table id="info_table" style="width: 100%" cellspacing="6" cellpadding="6">
		
	</table>
</div>

<script type="text/javascript">
	var contact = { 1:'Home Landline', 2:'Office Landline', 3: 'Email Id', 4:'Mobile', 5:'Home Mobile' };
    $(function(){
    	$('#topContent').hide();
		var urlgetinfo = "<?php echo $this->url(array('controller' => 'student', 'action' => 'fetchcontactinfo'))?>";
		$.ajax({
    		url : urlgetinfo,
    		dataType : 'json',
            data : {format:'json'},
    		success: function(jStatus){
    			$.each(jStatus,function(contact_type_id,data){
    				var html = '';
    				$.each(data,function(key,value){
        				html += '<tr class="row"><td><span id="heading">'+contact[contact_type_id]+'</span><span id="content">'+value+'</span></td></tr>';
		    		});
    				$('#info_table').append(html);	
    			});
            },
            error: function(response) {
    			$('#errorBox').text(response.responseText).parent().show();
    			console.log(response);
    		}
    	});
    });

</script>

<style type="text/css">
	.info
	{
		font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
		font-size: 14px;
		margin: 15px;
		text-align: left;
		border-collapse: collapse;
	}
	td span#heading{
		color:red;
		font-size:0.9em;
	}
	td span#content{
		float:right;
		font-size:0.9em;
	}
	table {
      	border-color: #c20f2e;
		width:97%;
	}
	td{
		border-bottom:1px dashed #999;
	}
	tr.heading{
		color:black;
		font-size: 1.3em;
		background-color: #F7F7F7;
		border:1px solid black;
	}
	tr.heading td{
		border:none;
	}
}
</style>