<?php
    if(Zend_Auth::getInstance()->hasIdentity()){
		$authInfo = Zend_Auth::getInstance()->getStorage()->read();
		$usertype=$authInfo['userType'];
	}
?>
<div class="ui-state-hover"><center><H3>Address Information</H3></center></div>
<div class="info" id="address_info">
	<table id="info_table" style="width: 100%" cellspacing="5" cellpadding="5">
		
	</table>
</div>

<script type="text/javascript">

    $(function(){
    	$('#topContent').hide();
        
        var urlgetinfo = "<?php echo $this->url(array('controller' => 'student', 'action' => 'fetchaddressinfo'))?>";
        $.ajax({
    		url : urlgetinfo,
    		dataType : 'json',
    		data : {
                format:'json',
                <?php 
            	    if(isset($_GET['member_id']) && !empty($_GET['member_id']))
            	        echo "member_id : ".$_GET['member_id'];
                ?>
			},
    		success: function(jStatus){
        		if((jStatus == null) || (jStatus == false)|| (jStatus == undefined))
        		{
        			$('#info_table').append('No information has been added yet.');
        		}
        		else
        		{
            		var html = '';
        			$.each(jStatus,function(address_type,data){
            			html += '<tr class="heading"><td>'+address_type+' ADDRESS </td></tr>';
            			html += '<tr class="row"><td><span id="heading">Address</span><span id="content">'+data['address']+'</span></td></tr>';
            			html += '<tr class="row"><td><span id="heading">City</span><span id="content">'+data['city']+'</span></td></tr>';
            			html += '<tr class="row"><td><span id="heading">District</span><span id="content">'+data['district']+'</span></td></tr>';
            			html += '<tr class="row"><td><span id="heading">State</span><span id="content">'+data['state']+'</span></td></tr>';
            			html += '<tr class="row"><td><span id="heading">Pin Code</span><span id="content">'+data['postal_code']+'</span></td></tr>';
    		    		html += '<tr></tr>';
        			});
        			$('#info_table').append(html);
        		}
            },
            error: function(response) {
    			$('#errorBox').text(response.responseText).parent().show();
    			console.log(response);
    		}
    	});
    });
    
</script>

<style type="text/css">
	.info
	{
		font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
		font-size: 14px;
		margin: 15px;
		text-align: left;
		border-collapse: collapse;
	}
	td span#heading{
		color:red;
		font-size:0.9em;
	}
	td span#content{
		float:right;
		font-size:0.9em;
	}
	table {
      	border-color: #c20f2e;
		width:97%;
	}
	td{
		border-bottom:1px dashed #999;
	}
	tr.heading{
		color:black;
		font-size: 1.3em;
		background-color: #F7F7F7;
		border:1px solid black;
	}
	tr.heading td{
		border:none;
	}
}
</style>