<h2>Relative's Information</h2>

<form id="relatives_info" action="javascript:submit()" class="uniForm">
    
	<fieldset id="1" title="Father">
		<h4>Father's Information</h4>
    	<div class="ctrlHolder">
    		<label for="landline_no"> Landline No.</label>
    		<input name="landline_no" id="landline_no" value=""  data-default-value="e.g. 017226544331" size="35" maxlength="12" type="text" class="textInput validateInteger"/>
    		<p class="formHint">Landline number, if available.</p>
    	</div>
    	
    	<div class="ctrlHolder">
    		<label for="name"><em>*</em> Father's name</label>
    		<input name="name" id="name" data-default-value="e.g. Sh. Madan Kumar" value=""  size="35" maxlength="50" type="text" class="textInput required"/>
    		<p class="formHint">Father's name of Candidate</p>
    	</div>
            
    	<div class="ctrlHolder">
    		<label for="occupation">Father's occupation</label>
    		<input name="occupation" id="occupation" value="" data-default-value="e.g. Teacher" size="35" maxlength="50" type="text" class="textInput"/>
    		<p class="formHint">Father's occupation</p>
    	</div>
    	
    	<div class="ctrlHolder">
    		<label for="designation" >Father's designation</label>
    		<input name="designation" id="designation" value="" data-default-value="e.g. Lecturer" size="35" maxlength="50" type="text" class="textInput"/>
    		<p class="formHint">Father's designation</p>
    	</div>
            
    	<div class="ctrlHolder">
    		<label for="contact" > Father's contact</label>
    		<input name="contact" id="contact" value=""  data-default-value="e.g. 9416123494" size="35" maxlength="12" type="text" class="textInput validateInteger"/>
    		<p class="formHint">Father's contact number, it should be a mobile number.</p>
    	</div>
            
    	<div class="ctrlHolder">
    		<label for="office_add">Father's Office Address</label>
    		<textarea name="office_add" id="office_add" data-default-value="e.g. PWD B and R Office, Near SDM office, Narnaul"    rows="25" cols="25"></textarea>
    		<p class="formHint">Father's Office Address</p>
    	</div>
	</fieldset>
	
	<fieldset id="2" title="Mother">
		<h4>Mother's Information</h4>
    	<div class="ctrlHolder">
    		<label for="landline_no"> Landline No.</label>
    		<input name="landline_no" id="landline_no" value=""  data-default-value="e.g. 017226544331" size="35" maxlength="12" type="text" class="textInput validateInteger"/>
    		<p class="formHint">Landline number, if available.</p>
    	</div>
    	
    	<div class="ctrlHolder">
    		<label for="name"><em>*</em> Mother's name</label>
    		<input name="name" id="name" value=""  data-default-value="e.g. Smt. Sita Devi" size="35" maxlength="50" type="text" class="textInput required"/>
    		<p class="formHint">Mother's name of Candidate</p>
    	</div>
            
    	<div class="ctrlHolder">
    		<label for="occupation">Mother's occupation</label>
    		<input name="occupation" id="occupation" value="" data-default-value="e.g. Banking" size="35" maxlength="50" type="text" class="textInput"/>
    		<p class="formHint">Mother's occupation</p>
    	</div>
            
    	<div class="ctrlHolder">
    		<label for="designation">Mother's designation</label>
    		<input name="designation" id="designation" value="" data-default-value="e.g. Probationary officer" size="35" maxlength="50" type="text" class="textInput"/>
    		<p class="formHint">Mother's designation</p>
    	</div>
            
    	<div class="ctrlHolder">
    		<label for="office_add">Mother's Office Address</label>
    		<textarea name="office_add" id="office_add" data-default-value="e.g. H.no. 3, PWD B and R Colony, Near Old court"  rows="25" cols="25"></textarea>
    		<p class="formHint">Mother's Office Address (if applicable)</p>
    	</div>
    	
    	<div class="ctrlHolder">
    		<label for="contact" > Mother's contact</label>
    		<input name="contact" id="contact" value=""  data-default-value="e.g. 9416123494" size="35" maxlength="12" type="text" class="textInput validateInteger"/>
    		<p class="formHint">Mother's contact number, it should be a mobile number.</p>
    	</div>
	</fieldset>
	
	<fieldset id="3" title="Guardian">
		<h4>Guardian's Information</h4>
    	<div class="ctrlHolder">
    		<label for="">Guardian's name (if any)</label>
    		<input name="name" id="name" value="" data-default-value="e.g. Sh. Ravi Dutt" size="35" maxlength="50" type="text" class="textInput"/>
    		<p class="formHint">Guardian's name, if Candidate is not with parents.</p>
    	</div>
           
        <div class="ctrlHolder">
    		<label for="occupation">Guardian's occupation</label>
    		<input name="occupation" id="occupation" value="" data-default-value="e.g. Banking" size="35" maxlength="50" type="text" class="textInput"/>
    		<p class="formHint">Guardian's occupation</p>
    	</div>
            
    	<div class="ctrlHolder">
    		<label for="designation">Guardian's designation</label>
    		<input name="designation" id="designation" value="" data-default-value="e.g. Probationary officer" size="35" maxlength="50" type="text" class="textInput"/>
    		<p class="formHint">Guardian's designation</p>
    	</div>
            
    	<div class="ctrlHolder">
    		<label for="office_add">Guardian's Office Address</label>
    		<textarea name="office_add" id="office_add" data-default-value="e.g. H.no. 3, PWD B and R Colony, Near Old court"  rows="25" cols="25"></textarea>
    		<p class="formHint">Mother's Office Address (if applicable)</p>
    	</div>
           
    	<div class="ctrlHolder">
    		<label for="contact">Guardian's contact number</label>
    		<input name="contact" id="contact" value="" data-default-value="e.g. +919799123132" size="35" maxlength="50" type="text" class="textInput"/>
    		<p class="formHint">Guardian's contact number, it should be a mobile number.</p>
    	</div>
    	
    	<div class="ctrlHolder">
    		<label for="landline_no"> Landline No.</label>
    		<input name="landline_no" id="landline_no" value=""  data-default-value="e.g. 017226544331" size="35" maxlength="12" type="text" class="textInput validateInteger"/>
    		<p class="formHint">Landline number, if available.</p>
    	</div>
    </fieldset>
	
	<div id="submitStatus" style="display:none;padding: 1em;" class="ui-state-highlight ui-corner-all" ></div> 
	<div class="buttonHolder">
		<button type="reset" class="secondaryAction">Reset</button>
		<button type="submit" class="primaryAction">Next</button>
	</div>
</form>

<script type="text/javascript">

    $(function(){
    	$('form.uniForm').uniform({
    		prevent_submit : true
    	});

    	$('#topContent').hide();
    	
        var urlgetinfo = "<?php echo $this->url(array('controller' => 'student', 'action' => 'fetchrelativesinfo'))?>";
        $.ajax({
    		url : urlgetinfo,
    		dataType : 'json',
            data : {format:'json'},
    		success: function(jStatus){
    			$.each(jStatus,function(relation_id,data){
    				$.each(data,function(key,value){
        				var field_name = '#'+relation_id;
						var field = '#'+key;
						$(field_name).find(field).val(value).focus();	
		    		});		
    			});
    			$('input:first').focus();
            },
            error: function(response) {
    			$('#errorBox').text(response.responseText).parent().show();
    			console.log(response);
    		}
    	});
    });
    
	function get_params()
	{
		var formData = {};
		var relatives_info = {};
		var abc = {};
		
		$('fieldset').each(function(){
			var temp = {};
    		$(this).find('input,textarea')
    		.not('button,:input[value^="e.g."]')
    		.each(function(){
    			temp[this.name] = this.value;
    		});
    		relatives_info[this.id] = temp;
		});
			
		formData['relatives_info'] = relatives_info;
		return formData;
	}
    
    function submit()
    {
    	var urlSaveInfo = '<?php echo $this->url(array('controller' => 'student', 'action' => 'saverelativesinfo'))?>';
        $.ajax({
            url : urlSaveInfo,
            data : {
                	myarray : get_params(),
					format : 'json'
                	},
            success: function(jStatus){
                alert('Your information has been saved sucessfully');
                window.location.replace('/student/viewrelativesinfo');
            },
    		error: function(response) {
    			$('#errorBox').text(response.responseText).parent().show();
    			console.log(response);
    		}
    	});
    }

</script>

<style type="text/css">
.uniForm{
	background-color:white;
	padding:10px 10px 10px 25px;
	border:1px solid #b4c1da;
	margin:-5px 0 40px 0;
	box-shadow:#e4e4e4 0px 0px 1px 1px; 
}
h2{
	padding:3px 3px 3px 10px;
	background-color:#eceff4;
	border:1px solid #b4c1da;
	width:57%;
	font-size:17px;
	font-weight:100;
}
span{
	float:right;
	font-size:14px;
	font-weight:100;	
}
h4{
	font-size:1.2em;
}
</style>
    
    
<?php
$this->headScript()->appendFile('http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
    
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/smooth.uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/demos/css/demo.css');
?>