<?php
$student_department = $this->department_id;
?>
<h2>Class Information:</h2>

<form action="javascript:submit_info_in_core()" class="uniForm">
    <fieldset id="class_info">

	<div class="ctrlHolder">
		<div class="ctrlHolder">
		<label for="department_id"><em>*</em>Department</label>
		<input name="department_id" id="department_id" value="<?php echo $student_department;?>" readonly="readonly" size="35" disabled="disabled" maxlength="50" type="text" class="textInput required" />
		<p class="formHint">Your Department</p>
	</div>
	</div>

	<div class="ctrlHolder">
		<label for="programme_id"><em>*</em>Programme</label>
		<input name="programme_id" id="programme_id" value="BTECH" readonly="readonly" size="35" disabled="disabled" maxlength="50" type="text" class="textInput required" />
		<p class="formHint">Select the programme</p>
	</div>

	<div class="ctrlHolder">
		<label for="batch_start"><em>*</em>Batch Start</label>
		<input name="batch_start" id="batch_start" value="<?php echo $_GET['batch_start'];?>" readonly="readonly" size="35" disabled="disabled" maxlength="50" type="text" class="textInput required" />
		<p class="formHint">Select the starting year of the batch</p>
	</div>
<br>
	

	<div class="ctrlHolder">
		<label for="group_id"><em>*</em>Group</label>
		<select id="group_id" name="group_id" class="selectInput required">
		<option selected="selected">C2</option>
		</select>
		<p class="formHint">Select Your Group</p>
	</div>

	<div class="ctrlHolder"><label for="roll_no"><em>*</em>Roll number</label>
		<input name="roll_no" id="roll_no" data-default-value="e.g. 2308015" size="35" maxlength="50" type="text" class="textInput required validateInteger" />
		<p class="formHint">Enter your University Roll Number</p>
	</div>
	</fieldset>

	<div id="submitStatus" style="display:none;padding: 1em;" class="ui-state-highlight ui-corner-all" ></div> 
	<div class="buttonHolder">
		<button type="reset" class="secondaryAction">Reset</button>
		<button type="submit" class="primaryAction">Next</button>
	</div>
</form>

<script>
	$(function(){
		$('form.uniForm').uniform({
			prevent_submit : true
		});

	    var urlgetProgrammes = "http://core.aceambala.com/class/fetchprogrammes";
	    $.ajax({
    		url : urlgetProgrammes,
    		dataType : 'jsonp',
            data : {format:'jsonp'},
    		success: function(jStatus){
    			$.each(jStatus['programmes'],function(programme_id,programme_name){
					html_text = '<option value="'+programme_id+'">'+programme_name+'</option>';
					
					$('#programme_id').append(html_text);
    			});
            },
            error: function(response) {
				$('#errorBox').text(response.responseText).parent().show();
    			console.log(response);
    		}
		});
	});

		if($('#department_id').val() == 'CSE')
		{
			var html = '<option value=A1>A1</option>'+
						'<option value=A2>A2</option>'+
						'<option value=A3>A3</option>';

			$('select#group_id').html(html);
		}
		else if($('#department_id').val() == 'MECH')
		{
			var html = '<option value=D1>D1</option>'+
            			'<option value=D2>D2</option>'+
            			'<option value=D3>D3</option>';

			$('select#group_id').html(html);
		}
		else if($('#department_id').val() == 'ECE')
		{
			var html = '<option value=B1>B1</option>'+
            			'<option value=B2>B2</option>'+
            			'<option value=B3>B3</option>';

			$('select#group_id').html(html);
		}
		else if($('#department_id').val() == 'BT')
		{
			var html = '<option value=C1>C1</option>'+
            			'<option value=C2>C2</option>'+
            			'<option value=C3>C3</option>';

			$('select#group_id').html(html);
		}
		else
		{
			$('select#group_id').html('');
		}
	
	function get_params()
	{
		var class_info = {};
		$('fieldset#class_info :input')
    	.not('button,:input[value^="e.g."]')
    	.not(':input[type="checkbox"]')
    	.each(function(){ 
    		class_info[this.name] = this.value;
    	});
    	
    	var semesters_added = new Array();

    	for(var i=1; i<=8; i++)
    	{
    		if($('#sem_'+i).is(':checked'))
        		semesters_added.push(i);
    	}
    	class_info['semesters_added'] = semesters_added;
    	class_info['semesters_deleted'] = false;
		
    	return class_info;
	}
    
    function submit_info_in_core()
    {
        var data = get_params();
    	var urlSaveInfo = '<?php echo $this->url(array('controller' => 'student', 'action' => 'saveclassinfo'))?>';
        $.ajax({
            url : urlSaveInfo,
            async : false,
            data : {
                myarray : {class_info : data},
				format : 'json'
			},
            success: function(class_info){
                submit_in_acad(class_info);
            },
    		error: function(response) {
    			$('#errorBox').text(response.responseText).parent().show();
    			console.log(response);
    		}
    	});
    }

    function submit_in_acad(class_info)
    {
    	var urlSaveInfo = 'http://academic.aceambala.com/student/saveclassinfo';
        $.ajax({
            url : urlSaveInfo,
            async : false,
            dataType : 'jsonp',
            data : {
                	class_info : class_info,
					format : 'jsonp'
                	},
            success: function(jStatus){
                if(jStatus == true)
                	submit_in_tnp(class_info);
            },
    		error: function(response) {
    			$('#errorBox').text(response.responseText).parent().show();
    			console.log(response);
    		}
    	});
    }

    function submit_in_tnp(class_info)
    {
    	var urlSaveInfo = 'http://tnp.aceambala.com/student/saveclassinfo';
        $.ajax({
            url : urlSaveInfo,
            async : false,
            dataType : 'jsonp',
            data : {
            		class_info : class_info,
					format : 'jsonp'
                	},
            success: function(jStatus){
				window.location.replace('/student/viewclassinfo');
            },
    		error: function(response) {
    			$('#errorBox').text(response.responseText).parent().show();
    			console.log(response);
    		}
    	});
    }
    
</script>

<style type="text/css">
.uniForm{
	background-color:white;
	padding:10px 10px 10px 25px;
	border:1px solid #b4c1da;
	margin:-5px 0 40px 0;
	box-shadow:#e4e4e4 0px 0px 1px 1px;
	width:auto;
}
h2{
	padding:3px 3px 3px 10px;
	background-color:#eceff4;
	border:1px solid #b4c1da;
	font-size:17px;
	font-weight:100;
	margin-top:2px;	
}
span{
	float:right;
	font-size:14px;
	font-weight:100;	
}
</style>
    
    
<?php
$this->headScript()->appendFile('http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
    
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/smooth.uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/demos/css/demo.css');
?>