<form id="dmc_info_form" class="uniForm" action="javascript:submit()">
<h3>DMC Details</h3>
<fieldset id="dmc_info">

	<h5>Please fill this form and click on next to fill the subject wise details of DMC.</h5>
	<div class="ctrlHolder">
		<label for="dmc_id"><em>*</em>Serial Number</label>
		<input name="dmc_id" id="dmc_id" value="" data-default-value="e.g. 450" size="35" maxlength="50" type="text" class="textInput required validateAlphaNum"/>
		<p class="formHint">Serial Number on the top of DMC</p>
	</div>
					
	<div class="ctrlHolder">
		<label for="dispatch_date"><em>*</em>Date of Dispatch</label>
		<input name="dispatch_date" id="dispatch_date" data-default-value="2011-04-04" value=""  size="35" maxlength="50" type="text" readonly="readonly" class="textInput required"/>
		<p class="formHint">1. Select year <br/>2. Select Month<br/>3. Click date of Dispatch</p>
	</div>
	
	<div class="ctrlHolder">
		<label for="result_type_id"><em>*</em>Result Type</label>
		<select id="result_type_id" name="result_type_id" class="selectInput required">
			<option value="1">Regular Pass</option>
			<option value="2">Regular Fail</option>
			<option value="3">Re-evaluation Pass</option>
			<option value="4">Re-evaluation Fail</option>
			<option value="5">Re-appear Pass</option>
			<option value="6">Re-appear Fail</option>
		</select>
		<p class="formHint">Select the type of result</p>
	</div>
    		
	<div class="ctrlHolder">
		<label for="marks_obtained"><em>*</em>Marks Obtained</label>
		<input name="marks_obtained" id="marks_obtained" value="" data-default-value="e.g. 145" size="35" maxlength="50" type="text" class="textInput required validateInteger"/>
		<p class="formHint">Marks Obtained</p>
	</div>
	
	<div class="ctrlHolder">
		<label for="max_marks"><em>*</em>Total Marks</label>
		<input name="max_marks" id="max_marks" value="" data-default-value="e.g. 145" size="35" maxlength="50" type="text" class="textInput required validateInteger"/>
		<p class="formHint">Total Marks</p>
	</div>
	
	<div class="ctrlHolder">
		<label for="scaled_marks"><em>*</em>Scaled Marks</label>
		<input name="scaled_marks" id="scaled_marks" value="" data-default-value="e.g. 145" size="35" maxlength="50" type="text" class="textInput required validateInteger"/>
		<p class="formHint">Scaled Marks</p>
	</div>
	
	<!-- <div class="ctrlHolder">
		<label for="percentage"><em>*</em>Percentage</label>
		<input name="percentage" id="percentage" value="" data-default-value="e.g. 90" size="35" maxlength="50" type="text" class="textInput required validateNumber  validateMax val-100"/>
		<p class="formHint">Percentage obtained by Candidate</p>
	</div> -->
	
</fieldset>
</form>

<script>
    var class_id = '<?php echo $_GET['class_id']?>';
	var urlSaveRegistrationInfo = "<?php echo $this->url(array('controller' => 'student', 'action' => 'savedmcinfo'))?>";
	$(function(){
	    $('form#dmc_info_form').uniform({
    	  prevent_submit : true
	    });
		
		var urlgetSubjects = "<?php echo $this->url(array('controller' => 'student', 'action' => 'fetchsubjects'))?>";
	    $.ajax({
    		url : urlgetSubjects,
    		dataType : 'json',
            data : {
	        	    myarray:{'class_id':class_id},
	        	    format : 'json'
        	},
    		success: function(jStatus){

    			$.each(jStatus['subject_info'],function(subject_id,subject_data){
	    			
    				var html = '<h4>'+subject_data['name']+' ('+subject_data['code']+')</h4>'+

					'<fieldset id="subject_number_'+subject_id+'" class="subjects" title="'+subject_id+'" >'+
						'<div class="ctrlHolder">'+
							'<label for="internal"><em>*</em>Internal Marks Obtained</label>'+
							'<input name="internal" id="internal" value="" data-default-value="e.g. 45" size="35" maxlength="50" type="text" class="textInput required validateInteger"/>'+
							'<p class="formHint">Internal Marks of the Subject</p>'+
						'</div>'+
						
						'<div class="ctrlHolder">'+
							'<label for="external"><em>*</em>External Marks Obtained</label>'+
							'<input name="external" id="external" value="" data-default-value="e.g. 65" size="35" maxlength="50" type="text" class="textInput required validateInteger"/>'+
							'<p class="formHint">External Marks of the subject</p>'+
						'</div>'+
						
						'<div class="ctrlHolder">'+
							'<label for="max_marks"><em>*</em>Maximum Marks(Internal+External)</label>'+
							'<input name="max_marks" id="max_marks" value="" data-default-value="e.g. 150" size="35" maxlength="50" type="text" class="textInput required validateNumber"/>'+
							'<p class="formHint">Maximum marks of the subject(Addition of External Maximum Marks + Internal Maximum Marks)</p>'+
						'</div>'+
					'</fieldset>';

					$('#dmc_info_form').append(html);
    			});

    			var btn_html = '<div id="submitStatus" style="display:none;padding: 1em;" class="ui-state-highlight ui-corner-all" ></div>'+ 
    							'<div class="buttonHolder">'+
    							'<button type="reset" class="secondaryAction">Reset</button>'+
    							'<button type="submit" class="primaryAction">Next</button>'+
    							'</div>';
    			$('#dmc_info_form').append(btn_html);
            },
            error: function(response) {
				$('#errorBox').text(response.responseText).parent().show();
    				console.log(response);
    		}
		});
	  });

	$("#dispatch_date").datepicker({
		dateFormat: 'yy-mm-dd',
		changeMonth: true,
		changeYear: true,
		yearRange: '5:+5',
		onClose : function(dateText, inst) {
			this.focus();
			}
	});

    function submit(){
        var dmc_info_data = {};
        var data = {};
        var dmc_data = {};
        var urlSaveDmcInfo = "<?php echo $this->url(array('controller' => 'student', 'action' => 'savedmc'))?>";
		$('fieldset.subjects').each(function(){
	        var sub_data = {};
	        sub_data['is_pass'] = 0;
	        sub_data['is_verified'] = 0;
			var div_id = $(this).attr('id');
			var div_title = $(this).attr('title');

			$('fieldset#'+div_id+' :input').each(function(){
				sub_data[this.name] = this.value;
			})
			sub_data['is_pass'] = $('fieldset#'+div_id+' :input[name="is_pass"]').is(':checked')?1:0;
			sub_data['is_verified'] = $('fieldset#'+div_id+' :input[name="is_verified"]').is(':checked')?1:0;
						
			dmc_data[div_title]=sub_data;
			data['dmc_subject_marks'] = dmc_data;
			data['dmc_info_data'] = dmc_info_data;
		});

		
		$('fieldset#dmc_info :input')
    	.not('button,:input[value^="e.g."]')
    	.not(':input[type="checkbox"]')
    	.each(function(){ 
    		dmc_info_data[this.name] = this.value;
    	});
    	dmc_info_data['class_id'] = class_id;
		$.ajax({
    		url : urlSaveDmcInfo,
    		dataType : 'jsonp',
    		data : {myarray:data,
    			format :'jsonp'},
    		success: function(jStatus){
    			if(jStatus){
            		//$('#dmc_info_div').hide();
        			//show_subject_div();
        			alert('Your data has been saved sucessfully');
        			window.location.replace('/student/viewdmc?dmc_info_id='+jStatus<?php 
        			if(!empty($_GET['member_id'])){
        			    echo '\'&member_id='.$_GET['member_id'].'\'';
        			}?>);
        		}
            },
            error: function(response) {
    			$('#errorBox').text(response.responseText).parent().show();
    				console.log(response);
    		}
    	});
    }
</script>

<style>
	.uniForm{
		background-color:white;
		padding:10px 10px 10px 25px;
		border:1px solid #b4c1da;
		margin:0 0 40px 0;
		box-shadow:#e4e4e4 0px 0px 1px 1px;
		width:auto;
	}
	h3{
    	color: #343434;
    	line-height: 1;
    	margin: 1.5em -28px;
    	padding: 14px 28px;
		background-color: #ECEFF4;
    	border: 1px solid #B4C1DA;
    	font-size: 17px;
    	font-weight: 100;
    	width: 57%;
	}
	h4{
		padding:3px 3px 3px 10px;
		background-color:#eceff4;
		border:1px solid #b4c1da;
		width:57%;
		font-size:17px;
		font-weight:100;
	}
	h5{
		font-size: 14px;
		font-weight:400;
		margin: 0 0 15px 0;
	}
</style>
<?php
$this->headScript()->appendFile('http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
    
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/smooth.uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/demos/css/demo.css');
?>