<form id="gate_form" class="uniForm" action="javascript:submit_gate_info()">
<fieldset id="gate">
	<h3>GATE</h3>
	
	<div class="ctrlHolder">
		<label for="roll_no"><em>*</em>Roll Number</label>
		<input name="roll_no" id="roll_no" value="" data-default-value="e.g. 450" size="35" maxlength="50" type="text" class="textInput required validateInteger"/>
		<p class="formHint">All India Roll No.</p>
	</div>
					
	<div class="ctrlHolder">
		<label for="doc"><em>*</em>Date of Conduct</label>
		<input name="doc" id="doc" data-default-value="2011-04-04" value=""  size="35" maxlength="50" type="text" readonly="readonly" class="textInput required"/>
		<p class="formHint">1. Select year <br/>2. Select Month<br/>3. Click date of birthday</p>
	</div>
        				
	<div class="ctrlHolder">
		<label for="all_india_rank"><em>*</em>All India Rank (AIR)</label>
		<input name="all_india_rank" id="all_india_rank" value="" data-default-value="e.g. 450" size="35" maxlength="50" type="text" class="textInput required validateInteger"/>
		<p class="formHint">All India Rank</p>
	</div>
					
	<div class="ctrlHolder">
		<label for="total_score"><em>*</em>Gate Score</label>
		<input name="total_score" id="total_score" value="" data-default-value="e.g. 145" size="35" maxlength="50" type="text" class="textInput validateInteger"/>
		<p class="formHint">Marks of gate Form</p>
	</div>
	
	<div id="submitStatus" style="display:none;padding: 1em;" class="ui-state-highlight ui-corner-all" ></div> 
	<div class="buttonHolder">
		<button type="reset" class="secondaryAction">Reset</button>
		<button type="submit" class="primaryAction">Next</button>
	</div>
</fieldset>
</form>
<script type="text/javascript">
    $('form.uniForm').uniform({
        prevent_submit : true
 	});

    $("#doc").datepicker({
    	dateFormat: 'yy-mm-dd',
    	changeMonth: true,
		changeYear: true,
		yearRange: '-25:-15',
		onClose : function(dateText, inst) {
			this.focus();
			}
    });

    function submit_gate_info(){
    	var data = {};
        var urlSaveGateInfo = "<?php echo $this->url(array('controller' => 'student', 'action' => 'savegateinfo'))?>";
        var qualificationData = {};
        $('fieldset#gate :input')
        .not('button,:input[value^="e.g."]')
        .each(function(){ 
        	qualificationData[this.name] = this.value;
        });
        data['qualification_name'] = 'GATE';
        data['qualification_data'] = qualificationData;
        $.ajax({
        	url : urlSaveGateInfo,
        	data : {myarray:data},
        	success: function(jStatus){
        		if(jStatus){
            		alert('Your information has been sucessfully submitted...');
            		window.location = '<?php echo $this->url(array('controller' => 'student', 'action' => 'profile'))?>';
        		}
            },
            error: function(response) {
        		$('#errorBox').text(response.responseText).parent().show();
        			console.log(response);
        	}
        });
    }
</script>