<form id="aieee_form" class="uniForm" action="javascript:submit_aieee_info()">
<fieldset id="aieee">
	<h3>AIEEE</h3>
				
	<div class="ctrlHolder">
		<label for=""><em>*</em>Roll Number</label>
		<input name="roll_no" id="roll_no" value="" data-default-value="e.g. 450" size="35" maxlength="50" type="text" class="textInput required validateInteger"/>
		<p class="formHint">All India Roll No. of Candidate</p>
	</div>
					
	<div class="ctrlHolder">
		<label for="doc"><em>*</em>Date of Conduct</label>
		<input name="doc" id="doc" data-default-value="2011-04-04" value=""  size="35" maxlength="50" type="text" readonly="readonly" class="textInput required"/>
		<p class="formHint">1. Select year <br/>2. Select Month<br/>3. Click date of birthday</p>
	</div>
        
					
	<div class="ctrlHolder">
		<label for=""><em>*</em>All India Rank (AIR)</label>
		<input name="all_india_rank" id="all_india_rank" value="" data-default-value="e.g. 450" size="35" maxlength="50" type="text" class="textInput required validateInteger"/>
		<p class="formHint">All India Rank of Candidate</p>
	</div>
					
	<div class="ctrlHolder">
		<label for=""><em>*</em>AIEEE Marks</label>
		<input name="total_score" id="total_score" value="" data-default-value="e.g. 145" size="35" maxlength="50" type="text" class="textInput validateInteger"/>
		<p class="formHint">Marks of AIEEE Form</p>
	</div>
	
	<div id="submitStatus" style="display:none;padding: 1em;" class="ui-state-highlight ui-corner-all" ></div> 
	<div class="buttonHolder">
		<button type="reset" class="secondaryAction">Reset</button>
		<button type="submit" class="primaryAction">Next</button>
	</div>				
</fieldset>
</form>
<?php
$this->headScript()->appendFile('http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
    
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/smooth.uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/demos/css/demo.css');
?>
<script type="text/javascript">
    $('form.uniForm').uniform({
        prevent_submit : true
 	});
    serverDateObj = $.datepicker.parseDate('dd-mm-yy', $('#datetext').text());
    $("#doc").datepicker({
    	dateFormat: 'yy-mm-dd',
    	changeMonth: true,
		changeYear: true,
		yearRange: '-25:-15',
		onClose : function(dateText, inst) {
			this.focus();
			}
    });

    function submit_aieee_info(){
    	var data = {};
    	var urlSaveAieeeInfo = "<?php echo $this->url(array('controller' => 'student', 'action' => 'saveaieeeinfo'))?>";
    	var qualificationData = {};
    	$('fieldset#aieee :input')
    	.not('button,:input[value^="e.g."]')
    	.each(function(){ 
    		qualificationData[this.name] = this.value;
    	});
    	data['qualification_name'] = 'AIEEE';
    	data['qualification_data'] = qualificationData;
    	$.ajax({
    		url : urlSaveAieeeInfo,
    		data : {myarray:data},
    		success: function(jStatus){
        		if(jStatus){
        			alert('Your information has been sucessfully submitted...');
        			window.location = '<?php echo $this->url(array('controller' => 'student', 'action' => 'profile'))?>';
        		}
            },
            error: function(response) {
    			$('#errorBox').text(response.responseText).parent().show();
    				console.log(response);
    		}
    	});
    }
    	
</script>