<!--[if lte ie 7]>
      <style type="text/css" media="screen">
        /* Move these to your IE6/7 specific stylesheet if possible */
        .uniForm, .uniForm fieldset, .uniForm .ctrlHolder, .uniForm .formHint, .uniForm .buttonHolder, .uniForm .ctrlHolder ul{ zoom:1; }
      </style>
<![endif]-->
<h2>Academic Information:<span id="goback"></span></h2>
<div id="initial_div">
	<?php
        foreach ($this->qualifications as $key => $value)
        {
            echo '<span class="name_span">'.$value.' Information : </span>';
            if($this->filled_qualifications[$key] != null){
                //$view_fxn_name = 'show_'.strtolower($value).'_div()';
                $action_name = 'view'.strtolower($value).'info';
                echo '<span class="view_span"><a href="'.$this->url(array('controller' => 'student', 'action' => $action_name)).'">View Information</a></span><br><br>';
            }
            else {
                $create_fxn_name = 'show_'.strtolower($value).'_div()';
                echo '<span class="create_span" onclick="javascript:'.$create_fxn_name.'">Fill Information</span><br><br>';
            }
        }
    ?>
</div>

<div id="matric_div"></div>
<div id="twelfth_div"></div>
<div id="aieee_div"></div>
<div id="diploma_div"></div>
<div id="leet_div"></div>
<div id="btech_div"></div>
<div id="gate_div"></div>


<script>
	var urlCreateMatricInfo = "<?php echo $this->url(array('controller' => 'student', 'action' => 'editmatricinfo'))?>";
	var urlCreateTwelfthInfo = "<?php echo $this->url(array('controller' => 'student', 'action' => 'edittwelfthinfo'))?>";
	var urlCreateAieeeInfo = "<?php echo $this->url(array('controller' => 'student', 'action' => 'editaieeeinfo'))?>";
	var urlCreateDiplomaInfo = "<?php echo $this->url(array('controller' => 'student', 'action' => 'editdiplomainfo'))?>";
	var urlCreateLeetInfo = "<?php echo $this->url(array('controller' => 'student', 'action' => 'editleetinfo'))?>";
	var urlCreateBtechInfo = "<?php echo $this->url(array('controller' => 'student', 'action' => 'editbtechinfo'))?>";
	var urlCreateGateInfo = "<?php echo $this->url(array('controller' => 'student', 'action' => 'editgateinfo'))?>";
	
    function show_matric_div(){
    	$('#initial_div').hide();
        var formDiv = '#matric_div';
    	$(formDiv).load(urlCreateMatricInfo, '', function(response, status, xhr) {
        	if (status == 'error') {
            	var msg = "Sorry but there was an error: ";
                $(".content").html(msg + xhr.status + " " + xhr.statusText);
                return;
            }
        	show_goback();
        });
    }
    function show_twelfth_div(){
    	$('#initial_div').hide();
        var formDiv = '#twelfth_div';
    	$(formDiv).load(urlCreateTwelfthInfo, '', function(response, status, xhr) {
        	if (status == 'error') {
            	var msg = "Sorry but there was an error: ";
                $(".content").html(msg + xhr.status + " " + xhr.statusText);
                return;
            }
        	show_goback();
        });
    	show_goback();
    	var formDiv = '#aieee_div';
    	$(formDiv).load(urlCreateAieeeInfo, '', function(response, status, xhr) {
        	if (status == 'error') {
            	var msg = "Sorry but there was an error: ";
                $(".content").html(msg + xhr.status + " " + xhr.statusText);
                return;
            }
        	show_goback();
            $('#aieee_div').hide();
        });
    }
    function show_diploma_div(){
    	$('#initial_div').hide();
        var formDiv = '#diploma_div';
    	$(formDiv).load(urlCreateDiplomaInfo, '', function(response, status, xhr) {
        	if (status == 'error') {
            	var msg = "Sorry but there was an error: ";
                $(".content").html(msg + xhr.status + " " + xhr.statusText);
                return;
            }
        	show_goback();
        });
    	var formDiv = '#leet_div';
    	$(formDiv).load(urlCreateLeetInfo, '', function(response, status, xhr) {
        	if (status == 'error') {
            	var msg = "Sorry but there was an error: ";
                $(".content").html(msg + xhr.status + " " + xhr.statusText);
                return;
            }
        	show_goback();
        	$('#leet_div').hide();
        });
    }
    function show_btech_div(){
    	$('#initial_div').hide();
        var formDiv = '#btech_div';
    	$(formDiv).load(urlCreateBtechInfo, '', function(response, status, xhr) {
        	if (status == 'error') {
            	var msg = "Sorry but there was an error: ";
                $(".content").html(msg + xhr.status + " " + xhr.statusText);
                return;
            }
        	show_goback();
        });
    	var formDiv = '#gate_div';
    	$(formDiv).load(urlCreateGateInfo, '', function(response, status, xhr) {
        	if (status == 'error') {
            	var msg = "Sorry but there was an error: ";
                $(".content").html(msg + xhr.status + " " + xhr.statusText);
                return;
            }
        	show_goback();
        	$('#gate_div').hide();
        });
    }
    function show_goback(){
    	$('span#goback').html('<a href="<?php echo $this->url(array('controller' => 'student', 'action' => 'profile'))?>">Go back to profile page</a>');
    }
	</script>
    
    <style type="text/css">
    #initial_div{
    	padding:10px;
		background-color:white;
		box-shadow:#e4e4e4 0px 0px 1px 1px;
		width:57%
	}
	.checkbox_name{
		font-size:14px;
		color:#333;
	}
	.uniForm{
		background-color:white;
		padding:10px 10px 10px 25px;
		border:1px solid #b4c1da;
		margin:-5px 0 40px 0;
		box-shadow:#e4e4e4 0px 0px 1px 1px; 
	}
	h2,h3{
		padding:3px 3px 3px 10px;
		background-color:#eceff4;
		border:1px solid #b4c1da;
		width:57%;
		font-size:17px;
		font-weight:100;
	}
	#goback a{
		float:right;
		color:red;
		font-size:14px;
		text-decoration: none;
	}
	.name_span{
		padding:3px 3px 3px 10px;
		/*background-color:#eceff4;
		border:1px solid #b4c1da;*/
		font-size:17px;
		margin:0 10px 10px 0;
	}
	.view_span{
		padding:3px 3px 3px 10px;
		background-color:#fef8f6;
		border:1px solid #cd0a0a;
		font-size:17px;
	}
	.view_span a{
		text-decoration: none;
		color:black;
	}
	.view_span:hover{
		box-shadow:#b99393 0px 0px 1px 1px;
		cursor: pointer;
	}
	.create_span{
		padding:3px 3px 3px 10px;
		background-color:#fcfaf1;
		border:1px solid #fcefa1;
		font-size:17px;
	}
	.create_span:hover{
		box-shadow:#aca162 0px 0px 1px 1px;
		cursor: pointer;
	}
	
</style>

<?php
$this->headScript()->appendFile('http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
    
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/smooth.uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/demos/css/demo.css');
?>