<!--[if lte ie 7]>
      <style type="text/css" media="screen">
        /* Move these to your IE6/7 specific stylesheet if possible */
        .uniForm, .uniForm fieldset, .uniForm .ctrlHolder, .uniForm .formHint, .uniForm .buttonHolder, .uniForm .ctrlHolder ul{ zoom:1; }
      </style>
<![endif]-->

<h2>Academic Information:</h2>
<div id="initial_div">
	<?php
        foreach ($this->qualifications as $key => $value)
        {
            echo '<span class="name_span">'.$value.' Information : </span>';
            if(isset($this->qualifications)){
                if($this->filled_qualifications[$key] != null){
                    $action_name = 'view'.strtolower($value).'info';
                    echo '<span class="view_span"><a href="'.$this->url(array('controller' => 'student', 'action' => $action_name)).'">View Information</a></span><br><br>';
                }
                else {
                    $action_name = 'edit'.strtolower($value).'info';
                    echo '<span class="create_span"><a href="'.$this->url(array('controller' => 'student', 'action' => $action_name)).'">Fill Information</a></span><br><br>';
                }
            }
        }
    ?>
    <?php
        foreach ($this->exams as $key => $value)
        {
            echo '<span class="name_span">'.$value.' Information : </span>';
            if($this->filled_exams[$key] != null){
                $action_name = 'view'.strtolower($value).'info';
                echo '<span class="view_span"><a href="'.$this->url(array('controller' => 'student', 'action' => $action_name)).'">View Information</a></span><br><br>';
            }
            else {
                $action_name = 'edit'.strtolower($value).'info';
                echo '<span class="create_span"><a href="'.$this->url(array('controller' => 'student', 'action' => $action_name)).'">Fill Information</a></span><br><br>';
            }
        }
    ?>
    <br>
    <hr>
    <br>
    <?php 
        foreach ($this->degree_data as $sem_no => $data){
            echo 'Sem No.'.$sem_no.' ';
            foreach ($data as $dmc_no => $dmc_data){
                echo '<a href="/student/viewdmc?dmc_info_id='.$dmc_no.'&class_id='.$dmc_data['class_id'].'&dmc_view_type=single">DMC No.'.$dmc_no.' </a>';
                echo $dmc_data['dispatch_date'].' ';
                echo '<br>';
                echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
            }
            echo '<a href="/student/editdmc?class_id='.$dmc_data['class_id'].'&dmc_view_type=latest">+ Add More</a>';
            echo '<br>';
        }
    ?>
</div>
    
<style type="text/css">
    #initial_div{
    	padding:10px;
		background-color:white;
		box-shadow:#e4e4e4 0px 0px 1px 1px;
		width:37%
	}
	h2,h3{
		padding:3px 3px 3px 10px;
		background-color:#eceff4;
		border:1px solid #b4c1da;
		width:57%;
		font-size:17px;
		font-weight:100;
	}
	.name_span{
		padding:3px 3px 3px 10px;
		font-size:17px;
		margin:0 10px 10px 0;
	}
	.view_span{
		padding:3px 3px 3px 10px;
		background-color:#fef8f6;
		border:1px solid #cd0a0a;
		font-size:17px;
		float:right;
	}
	.view_span a{
		text-decoration: none;
		color:black;
	}
	.view_span:hover{
		box-shadow:#b99393 0px 0px 1px 1px;
		cursor: pointer;
	}
	.create_span{
		padding:3px 3px 3px 10px;
		background-color:#fcfaf1;
		border:1px solid #fcefa1;
		font-size:17px;
		float:right;
	}
	.create_span a{
		text-decoration: none;
		color:black;
	}
	.create_span:hover{
		box-shadow:#aca162 0px 0px 1px 1px;
		cursor: pointer;
	}
	
</style>

<?php
$this->headScript()->appendFile('http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
    
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/smooth.uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/demos/css/demo.css');
?>