<?php 
    $gate = $this->gate;
    
    if(Zend_Auth::getInstance()->hasIdentity()){
		$authInfo = Zend_Auth::getInstance()->getStorage()->read();
		$usertype=$authInfo['userType'];
	}
?>

<div class="ui-state-hover"><center><H3>Gate Details</H3></center></div>
<div id="gate_details">
    	<table id="corner" cellspacing="10" cellpadding="10">
        <?php
            if($gate == null){ 
                echo '<h4>No information has been added yet.</h4>';
            }
            else
            { 
            	echo '<tr><td>Roll Number</td><td>'.$gate['roll_no'].'</td></tr>';
                echo '<tr><td>All India Rank</td><td>'.$gate['all_india_rank'].'</td></tr>';
                echo '<tr><td>Score</td><td>'.$gate['total_score'].'</td></tr>';
                echo '<tr><td>Date</td><td>'.$gate['date'].'</td></tr>';
            }
        ?>
    	</table>
</div>

<?php if($usertype == 'STU'){?>
<input type="button" class="ui-button" value="Edit Information" onclick="window.location.replace('/student/editgateinfo');">
<?php }?>

<script type="text/javascript">
	$(function(){
		$('div#topContent').hide();
	});
</script>

<style type="text/css">
	table {
      	border-color: #c20f2e;
		width:97%;
	}
	tr{
		border-bottom:1px dashed #999;
	}
	#corner
	{
		font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
		font-size: 14px;
		margin: 15px;
		text-align: left;
		border-collapse: collapse;
	}
	#edit_btn {
		width:48%;
		float:left;
	}
	#goback_btn { 
		width:48%;
		float:right;
	}
</style>