
<div class="ui-widget-content ui-corner-all"><center><H3>AIEEE Details</H3></center></div>
<div id="Matric Details">
    	<table id="corner" cellspacing="10" cellpadding="10">
          
        <?php 
        	foreach ($this->aieee as $key => $value) 
        		{
                    echo '<tr>';
    	            echo '<td>'.ucfirst(str_replace('_', ' ',$key)).'</td>';
    	            if($value !=null){
            	        echo '<td>'.ucfirst($value).'</td>';
    	            }
    	            else {
    	                echo '<td><i>Not Mentioned</i></td>';
    	            }
    	            echo '</tr>';
        		} 
            ?>
        	
    	</table>
</div>
<div id="edit_btn" class="ui-widget-content ui-corner-all">
	<h3><center><a href="/student/editaieeeinfo">Edit</a></center></h3>
</div>
<input type="button" class="ui-widget-content ui-corner-all" value="Go Back">
<style type="text/css">
	table {
      	border-color: #c20f2e;
		width:97%;
	}
	tr{
		border-bottom:1px dashed #999;
	}
	#corner
	{
		font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
		font-size: 14px;
		margin: 15px;
		text-align: left;
		border-collapse: collapse;
	}
</style>