<?php 
    $aieee = $this->aieee;
    if(Zend_Auth::getInstance()->hasIdentity()){
		$authInfo = Zend_Auth::getInstance()->getStorage()->read();
		$usertype=$authInfo['userType'];
	}
?>

<div class="ui-state-hover"><center><H3>AIEEE Details</H3></center></div>
<div id="Matric Details">
    <?php
        if($aieee == null)
        {
            echo '<h4>No information has been added yet.</h4>';
        }
        else
        {
            echo '<table id="corner" cellspacing="10" cellpadding="10">';
        	echo '<tr><td>Roll Number</td><td>'.$aieee['roll_no'].'</td></tr>';
            echo '<tr><td>All India Rank</td><td>'.$aieee['all_india_rank'].'</td></tr>';
            echo '<tr><td>Score</td><td>'.$aieee['total_score'].'</td></tr>';
            echo '<tr><td>Date</td><td>'.$aieee['date'].'</td></tr>';
            echo '</table>';
            
            if($usertype == 'STU'){
                echo '<input type="button" class="ui-button" value="Edit Information" onclick="window.location.replace('."'".'/student/editaieeeinfo'."'".');">';
            }
        } 
    ?>
</div>

<script type="text/javascript">
	$(function(){
		$('div#topContent').hide();
	});
</script>

<style type="text/css">
	table {
      	border-color: #c20f2e;
		width:97%;
	}
	tr{
		border-bottom:1px dashed #999;
	}
	#corner
	{
		font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
		font-size: 14px;
		margin: 15px;
		text-align: left;
		border-collapse: collapse;
	}
	#goback_btn { 
		width:48%;
		float:right;
	}
</style>