
<div class="ui-widget-content ui-corner-all"><center><H3>Diploma Details</H3></center></div>
<div id="dip_details">
    	<table id="corner" cellspacing="10" cellpadding="10">
          
        <?php 
        	foreach ($this->diploma as $key => $value) 
        		{
        		    echo '<tr>';
    	            echo '<td>'.ucfirst(str_replace('_', ' ',$key)).'</td>';
    	            if($value !=null){
            	        echo '<td>'.ucfirst($value).'</td>';
    	            }
    	            else {
    	                echo '<td><i>Not Mentioned</i></td>';
    	            }
    	            echo '</tr>';
        		} 
            ?>
        	
    	</table>
	</div>
<style type="text/css">
	table {
      	border-color: #c20f2e;
		width:97%;
	}
	tr{
		border-bottom:1px dashed #999;
	}
	#corner
	{
		font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
		font-size: 14px;
		margin: 15px;
		text-align: left;
		border-collapse: collapse;
	}
</style>