<?php 
    $leet = $this->leet;
    
    if(Zend_Auth::getInstance()->hasIdentity()){
		$authInfo = Zend_Auth::getInstance()->getStorage()->read();
		$usertype=$authInfo['userType'];
	}
?>
<div class="ui-state-hover"><center><H3>LEET Details</H3></center></div>
<div id="leet_details">
          
    <?php
        if($leet == null)
        {
            echo '<h4>No information has been added yet.</h4>';
        }
        else
        {
            echo '<table id="corner" cellspacing="10" cellpadding="10">';
        	echo '<tr><td>Roll Number</td><td>'.$leet['roll_no'].'</td></tr>';
            echo '<tr><td>All India Rank</td><td>'.$leet['all_india_rank'].'</td></tr>';
            echo '<tr><td>Score</td><td>'.$leet['total_score'].'</td></tr>';
            echo '<tr><td>Date</td><td>'.$leet['date'].'</td></tr>';
    		echo '</table>';
    		
            if($usertype == 'STU'){
                echo '<input type="button" class="ui-button" value="Edit Information" onclick="window.location.replace('."'".'/student/editleetinfo'."'".');">';
            }
        }
    ?>
        	
</div>

<script type="text/javascript">
	$(function(){
		$('div#topContent').hide();
	});
</script>

<style type="text/css">
	table {
      	border-color: #c20f2e;
		width:97%;
	}
	tr{
		border-bottom:1px dashed #999;
	}
	#corner
	{
		font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
		font-size: 14px;
		margin: 15px;
		text-align: left;
		border-collapse: collapse;
	}
	#edit_btn {
		width:48%;
		float:left;
	}
	#goback_btn { 
		width:48%;
		float:right;
	}
</style>