
<div  class="ui-state-hover"><center><H3>Matric Details</H3></center></div>
<div id="Matric Details">
    	<table id="corner" cellspacing="10" cellpadding="10">
          
        <?php 
        	foreach ($this->matric as $key => $value) 
        		{
        		    echo '<tr>';
    	            echo '<td>'.ucfirst(str_replace('_', ' ',$key)).'</td>';
    	            if($value !=null){
            	        echo '<td>'.ucfirst($value).'</td>';
    	            }
    	            else {
    	                echo '<td><i>Not Mentioned</i></td>';
    	            }
    	            echo '</tr>';
        		} 
            ?>
        	
    	</table>
</div>
<input type="button" class="ui-button" value="Edit Information" onclick="window.location.replace('/student/editmatricinfo');">
<!--<input type="button" class="ui-button" value="Go Back" onclick="window.location.replace('/student/profile');">-->

<style type="text/css">
	table {
      	border-color: #c20f2e;
		width:97%;
	}
	tr{
		border-bottom:1px dashed #999;
	}
	#corner
	{
		font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
		font-size: 14px;
		margin: 15px;
		text-align: left;
		border-collapse: collapse;
	}
	#edit_btn {
		width:48%;
		float:left;
	}
	#goback_btn { 
		width:48%;
		float:right;
	}
</style>