<?php
$image_url = 'http://'.CDN_SERVER. '/images/activity/arrow.png';
?>
<h2>Welcome User!</h2>
<h3>Click any option..</h3>
<div id="container_div" style="background-color: #E0E7E7; padding: 2px;">
	<div id="content" style="background-color: #E0E7E7;  border: 2px solid #FFFFFF; margin: 0px;">
		<ul style="list-style-image: url('<?php echo $image_url;?>'); font-size: 15px; list-style-position: inside; line-height: 25px;">
			<li><a href="/student/viewprofile">View your profile</a></li>
			<li><a href="/student/createprofile">Create Profile</a></li>
			
		</ul>
	</div>
</div>