
<!--[if lte ie 7]>
      <style type="text/css" media="screen">
        /* Move these to your IE6/7 specific stylesheet if possible */
        .uniForm, .uniForm fieldset, .uniForm .ctrlHolder, .uniForm .formHint, .uniForm .buttonHolder, .uniForm .ctrlHolder ul{ zoom:1; }
      </style>
    <![endif]-->


<form action="javascript:submit();" class="uniForm">

<fieldset>
   <h3>Job Description</h3>
         <div class="ctrlHolder noLabel">
          <label for="job"><em>*</em>Job Title</label>
          <input name="job" id="job" data-default-value="e.g.System Engineer" value="" size="10" maxlength="50" type="text" class="textInput required validateAlpha"/></li>
          <p class="formHint"></p>
        </div>
        <div class="ctrlHolder">
          <label for="doa"><em>*</em>Date of Announcement</label>
          <input name="doa" id="doa" data-default-value="1990-12-31" value=""  size="35" maxlength="50" type="text" readonly="readonly" class="textInput required"/>
          <p class="formHint">1. Select year <br/>2. Select Month<br/>3. Click date of birthday</p>
        </div>
        
        <div class="ctrlHolder">
          <label for="job_description">Job Description</label>
          <textarea name="job_description" id="job_description" rows="25" cols="25" class="textInput required "></textarea>
          <p class="formHint">Brief description of<span class="cName" ></span></p>
        </div>
             
        <div class="ctrlHolder">
          <label for="eligibility_criteria">Eligibilty Criteria</label>
          <textarea name="eligibility_criteria" id="eligibility_criteria" data-default-value=""  rows="25" cols="25" class="textInput required "></textarea>
          <p class="formHint"></p>
        </div>
        
        
        
        </fieldset>
<div id="submitStatus" style="display: none; padding: 1em;"
	class="ui-state-highlight ui-corner-all"></div>

<div class="buttonHolder">
<button type="submit" class="secondaryAction">Cancel and go back</button>
<button type="submit" class="primaryAction">Save</button>
</div>

</form>
<script>
	var urlBasicInfo = "<?php
echo $this->url(array('controller' => 'job', 'action' => 'save'))?>";
      $(function(){
        $('form.uniForm').uniform({
          prevent_submit : true
        });

        serverDateObj = $.datepicker.parseDate('dd-mm-yy', $('#datetext').text());
        $("#doa").datepicker({
        	dateFormat: 'yy-mm-dd',
        	changeMonth: true,
			changeYear: true,
			yearRange: '-25:-15',
			onClose : function(dateText, inst) {
				this.focus();
				}
        });

        $('#job').change(function(){
            var cName = this.value;
        	$('.cName').text(cName);
        });
        
      });

      function submit() {
          $.ajax({
              url : urlBasicInfo,
              data : getValues(),
              success: function(jStatus){
                  
                  }
      });
      }

        function getValues() {
            var formData = {}; 
            $('form.uniForm :input')
            		.not('button,#e_mail_confirm,:input[value^="e.g."]')
            		.each(function(){ 
            			formData[this.name] = this.value; 
                });
        var gender = $('input:radio[name=gender]:checked').val();
        formData.gender = gender; 
  		return formData;
  	}
    </script>
<?php
$this->headScript()->appendFile(
'http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER . '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER . '/plugins/uni-form/css/smooth.uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER . '/plugins/uni-form/demos/css/demo.css');
?>