<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>OOOPSSSS....</title>
  <style>
body {
    font-family: Arial,Helvetica,sans-serif;
    font-size: 14px;
    text-align: center;
}
.error_page {
    margin: auto;
    padding: 50px;
    width: 600px;
}

</style>
</head>
<body>
<div class="error_page">
    <img src="http://<?php echo CDN_SERVER?>/images/activity/error/face_sad.gif" alt="face_sad" />
    <h1>We're sorry...</h1>
    <p>Unable to process your request.</p>
    <p><a href="<?php echo 'http://'.AUTH_SERVER ?>">Return to the homepage</a></p>
</div>
  <p style="font-style: italic;">Server fussed with following message:</p>
  <p><?php echo $this->message ?></p>
  <?php if (isset($this->exception)): ?>

  <h3>Exception information:</h3>
  <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
  </p>

  <h3>Stack trace:</h3>
  <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><?php echo var_export($this->request->getParams(), true) ?>
  </pre>
  <?php endif ?>

</body>
</html>