<!DOCTYPE html>

<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>ACE COUNSELING (<?php $curr = date("Y"); echo $curr; ?>)</title>
<style type="text/css">
div{
	margin: 1em;
	padding-bottom: 1em;
}
.letterhead {
	margin-top: 0cm;
	margin-right: 0cm;
	margin-left: 0cm;	
	text-align: center;
	font-family: "Calibri","sans-serif";
	padding: 0cm 0cm 1.0pt 0cm;
}
.letterhead p {
	margin-top: 0cm;	
	margin-bottom: 0cm;	
	font-size: 12pt;
	font-weight :bold;
	line-height:normal;
	font-family: "Cambria","serif";
}
.letterhead a {
	text-decoration: none;
	color: black;
}
.letterhead h1 {
	margin-top: 0cm;	
	margin-right: 0cm;
	margin-bottom: 2pt;
	margin-left: 0cm;
	font-size: 14pt;
	font-family: "Baskerville Old Face","serif";
}
.formData li{
	clear: both;
	padding-bottom: 1em;
	page-break-before: auto;
}
.formData li table {
	font-size: 0.8em;
}
hr {
	color: red;
}
.infoHeader {
    padding-left: 0.3em;
    padding-right: 0.3em;
	font-family:sans-serif;
	color:#888;
	font-size:0.9em;
	font-weight:bold;
    text-transform: capitalize;
}
.infoContent {
	clear:right;
    padding-left: 0.3em;
    padding-right: 0.3em;
	text-align: right;
	font-family:serif;
	font-size:1.1em;
    text-transform: capitalize;
}
</style>
<?php 
$baseUrl = $this->baseUrl();
// Content Delievery Server i.e. static Files, e.g. CSS, JS, Themes and related images etc
$cdnServer = 'http://'.CDN_SERVER;
// Add most common Script files
// Jquery
$this->jQuery()->setLocalPath($cdnServer . '/js/jquery-1.5.min.js');
// Jquery UI
$this->jQuery()->setUiLocalPath($cdnServer . '/js/jquery-ui-1.8.6.custom.min.js');
echo $this->jQuery()->uiEnable();
?>
</head>

<body>
<div class="letterhead" >
<img src="<?php echo 'http://' . CDN_SERVER .  '/images/logos'; ?>/mainlogo.png" alt="ACE logo" />
<h1> AMBALA COLLEGE OF ENGINEERING &amp; APPLIED RESEARCH (ACE)</h1>
</div>
<hr />
<p class=MsoNormal align=center style='text-align:center'><b><span
style='font-family:"Sylfaen","serif";text-decoration: underline;'>Candidate's Documents/Credentials
Verification Form</span></b></p>
<p class=MsoNormal align=center style='text-align:center'><b><span
style='font-family:"Sylfaen","serif"'>Mode of Admission:</span></b></p>

    <form action="javascript:submit();" class="uniForm">
        <div class="ctrlHolder">
          <p class="label">Gender</p>
          <ul class="blockLabels alternate">
            <li><label for=""><input name="gender" type="radio" value="M" checked="checked" title="Male">Male</label></li>
            <li><label for=""><input  name="gender" type="radio" value="F" title="Female">Female</label></li>
          </ul>
          <p class="formHint">Gender</p>
        </div>
    
    </form>
      
	<script>
	$(function(){
        $('form.uniForm').uniform({
          prevent_submit : true
        });
      });
    </script>