<link rel="stylesheet" href="<?php echo 'http://'. CDN_SERVER . '/css/admission.css';?>">

<div id="main">
	<div id="sidebar" style="float:left">
	<ul class="menu">
		<li class="item1">
			<a href="#">Class Information</a>
			<ul>
				<li class="subitem1"><a href="/student/editclassinfo" target="content_frame">Add/Edit</a></li>
				<li class="subitem1"><a href="/student/viewclassinfo" target="content_frame">View</a></li>
			</ul>
		</li>

		<li class="item2">
			<a href="#">Personal Information</a>
			<ul>
				<li class="subitem1"><a href="/student/editpersonalinfo" target="content_frame">Add/Edit</a></li>
				<li class="subitem1"><a href="/student/viewpersonalinfo" target="content_frame">View</a></li>
			</ul>
		</li>

		<li class="item3">
			<a href="#">Contact Information</a>
			<ul>
				<li class="subitem1"><a href="/student/editcontactinfo" target="content_frame">Add/Edit</a></li>
				<li class="subitem1"><a href="/student/viewcontactinfo" target="content_frame">View</a></li>
			</ul>
		</li>

		<li class="item4">
			<a href="#">Address Information</a>
			<ul>
				<li class="subitem1"><a href="/student/editaddressinfo" target="content_frame">Add/Edit</a></li>
				<li class="subitem1"><a href="/student/viewaddressinfo" target="content_frame">View</a></li>
			</ul>
		</li>

		<li class="item5">
			<a href="#">Family Information</a>
			<ul>
				<li class="subitem1"><a href="/student/editrelativesinfo" target="content_frame">Add/Edit</a></li>
				<li class="subitem1"><a href="/student/viewrelativesinfo" target="content_frame">View</a></li>
			</ul>
		</li>

		<li class="item6">
			<a href="#">University Registration Information</a>
			<ul>
				<li class="subitem1"><a href="/student/editunvregistrationinfo" target="content_frame">Add/Edit</a></li>
				<li class="subitem1"><a href="/student/viewunvregistrationinfo" target="content_frame">View </a></li>
			</ul>
		</li>
	</ul>
	</div>
	<div id="page_content">
		<iframe name="content_frame" width="850" height="900" frameborder="0" scrolling="auto" onload="hide_top()"></iframe>
	</div>
</div>

<script type="text/javascript">
	$(function() {
        var menu_ul = $('.menu > li > ul'),
		menu_a  = $('.menu > li > a');

        menu_ul.hide();
    
        menu_a.click(function(e) {
			e.preventDefault();
            if(!$(this).hasClass('active')) {
                menu_a.removeClass('active');
                menu_ul.filter(':visible').slideUp('normal');
                $(this).addClass('active').next().stop(true,true).slideDown('normal');
            } else {
                $(this).removeClass('active');
                $(this).next().stop(true,true).slideUp('normal');
            }
        });
    });

	function hide_top()
	{
		$('iframe#content_frame').contents().find('div#topContent').hide();		
	}

</script>

<style type="text/css">
	#page_content{
    	float:right;
    }
</style>