<!--[if lte ie 7]>
	<style type="text/css" media="screen">
		/* Move these to your IE6/7 specific stylesheet if possible */
		.uniForm, .uniForm fieldset, .uniForm .ctrlHolder, .uniForm .formHint, .uniForm .buttonHolder, .uniForm .ctrlHolder ul{ zoom:1; }
	</style>
<![endif]-->
<form action="javascipt:void(0)" id="search_criteria">
<div class="main_div">
	<div class="heading">
		<h4>Personal Information</h4>
	</div>
	<fieldset id="personal" class="search_field_div">
		<label for="gender">Gender</label>
		<select name="gender" id="gender">
			<option value="Any">ANY</option>
			<option value="MALE">MALE</option>
			<option value="FEMALE">FEMALE</option>
		</select>&nbsp;
		
		<label for="cast_id">Cast</label>
		<select id="cast_id" name="cast_id">
			<option value="Any">ANY</option>
       		<option value="1">GEN</option>
       		<option value="2">BC</option>
       		<option value="3">SC</option>
       		<option value="4">ST</option>
		</select>&nbsp;
		
		<label for="religion_id">Religion</label>
		<select id="religion_id" name="religion_id" class="selectInput required">
			<option value="Any">ANY</option>
       		<option value="1">Hindu</option>
       		<option value="2">Muslim</option>
       		<option value="3">Sikh</option>
       		<option value="4">Christian</option>
		</select>&nbsp;
		
		<label for="dob_from">Date of Birth from</label>
		<input name="dob_from" id="dob_from" size="18" maxlength="50" type="text" readonly="readonly"/>
		
		<label for="dob_to">To</label>
		<input name="dob_to" id="dob_to" size="18" maxlength="50" type="text" readonly="readonly"/>&nbsp;
		
		<label for="annual_income_from">Annual Income From</label>
		<input name="annual_income_from" id="annual_income_from" size="18" maxlength="50" type="text"/>
		
		<label for="annual_income_to">To</label>
		<input name="annual_income_to" id="annual_income_to" size="18" maxlength="50" type="text"/>
	</fieldset>
</div>

<br>

<div id="academic" class="main_div">
	<div class="heading">
		<h4>Academic Information</h4>
	</div>
	<div class="search_field_div">
	
		<fieldset id="btech">

			<label for="discipline_id">Discipline</label>
			<select id="discipline_id" name="discipline_id" class="selectInput required">
				<option value="Any">ANY</option>
				<option value="CSE">Computer Science</option>
				<option value="ECE">Electronics And Communication</option>
				<option value="MECH">Mechanical</option>
				<option value="BT">Biotechnology</option>
			</select>&nbsp;
			
			<label for="passing_year">B.Tech Batch</label>
			<select name="passing_year" id="passing_year">
				<option value="Any">ANY</option>
				<?php
			    	$current_year = intval(date('Y'));
			    	for($i=2002+4;$i<=$current_year+4;$i++)
			    	{
			    	    echo '<option value="'.$i.'">'.$i.' - '.($i+4).'</option>';
			    	}
				?>
			</select><br>
			
			<label for="percentage">B.Tech Percentage</label>
			<input type="text" id="percentage" readonly="readonly" style="border:0; color:#f6931f; font-weight:bold;" />
			<div id="btech_slider-range"></div>
			
			<label for="backlogs">Backlogs in B.Tech</label>
			<select name="backlogs">
				<option value="never">Never</option>
				<option value="0">0</option>
				<?php 
					for($i=1;$i<=10;$i++)
						echo '<option value="'.$i.'">'.$i.'</option>';
				?>
				<option value="Any">Any</option>
			</select>
		
		</fieldset>
		
		<fieldset id="twelfth">
			<label for="percentage">10+2 Percentage</label>
			<input type="text" id="percentage" readonly="readonly" style="border:0; color:#f6931f; font-weight:bold;" />
			<div id="twelfth_slider-range"></div>
			
			<label for="passing_year">10+2 Passing Year</label>
			<select name="passing_year" id="passing_year">
				<option value="Any">ANY</option>
				<?php
			    	$current_year = intval(date('Y'));
			    	for($i=2002;$i<=$current_year;$i++)
			    	{
			    	    echo '<option value="'.$i.'">'.$i.'</option>';
			    	}
				?>
			</select>
		</fieldset>
		
		<fieldset id="diploma">
			<label for="percentage">Diploma Percentage</label>
			<input type="text" id="percentage" readonly="readonly" style="border:0; color:#f6931f; font-weight:bold;" />
			<div id="diploma_slider-range"></div>
			
			<label for="passing_year">Diploma Passing Year</label>
			<select name="passing_year" id="passing_year">
				<option value="Any">ANY</option>
				<?php
			    	$current_year = intval(date('Y'));
			    	for($i=2002;$i<=$current_year;$i++)
			    	{
			    	    echo '<option value="'.$i.'">'.$i.'</option>';
			    	}
				?>
			</select>
		</fieldset>
		
		<fieldset id="tenth">
			<label for="percentage">Tenth Percentage</label>
			<input type="text" id="percentage" readonly="readonly" style="border:0; color:#f6931f; font-weight:bold;" />
			<div id="tenth_slider-range"></div>
			
			<label for="passing_year">Tenth Passing Year</label>
			<select name="passing_year" id="passing_year">
				<option value="Any">ANY</option>
				<?php
			    	$current_year = intval(date('Y'));
			    	for($i=2002;$i<=$current_year;$i++)
			    	{
			    	    echo '<option value="'.$i.'">'.$i.'</option>';
			    	}
				?>
			</select>
		</fieldset>
		
	</div>
</div>

<br>

<div id="career" class="main_div">
	<div class="heading">
		<h4>Career Information</h4>
	</div>
</div>

<br>

<input type="button" value="Search" onclick="javascript:submit_personal_values()"/>
</form>

<script type="text/javascript">
var personal_result = new Array();
var academic_result = new Array();
	serverDateObj = $.datepicker.parseDate('dd-mm-yy', $('#datetext').text());
	$("#dob_from").datepicker({
		dateFormat: 'yy-mm-dd',
		changeMonth: true,
		changeYear: true,
		yearRange: '-25:-15',
		onClose : function(dateText, inst) {
			this.focus();
			}
	});

	var b = new Array(12,45,2,67,34,10,14);
	
	alert(b.sort());
	
	serverDateObj = $.datepicker.parseDate('dd-mm-yy', $('#datetext').text());
	$("#dob_to").datepicker({
		dateFormat: 'yy-mm-dd',
		changeMonth: true,
		changeYear: true,
		yearRange: '-25:-15',
		onClose : function(dateText, inst) {
			this.focus();
			}
	});
	$( "#tenth_slider-range" ).slider({
		range: true,
		min: 0,
		max: 100,
		values: [ 40, 100 ],
		slide: function( event, ui ) {
			$("fieldset#tenth > #percentage").val( ui.values[ 0 ] + "-" + ui.values[ 1 ] );
		}
	});
	$( "fieldset#tenth > #percentage" ).val( $( "#tenth_slider-range" ).slider( "values", 0 ) +
		"-" + $( "#tenth_slider-range" ).slider( "values", 1 ) );

	$( "#twelfth_slider-range" ).slider({
		range: true,
		min: 0,
		max: 100,
		values: [ 40, 100 ],
		slide: function( event, ui ) {
			$( "fieldset#twelfth > #percentage" ).val( ui.values[ 0 ] + "-" + ui.values[ 1 ] );
		}
	});
	$( "fieldset#twelfth > #percentage" ).val( $( "#twelfth_slider-range" ).slider( "values", 0 ) +
		"-" + $( "#twelfth_slider-range" ).slider( "values", 1 ) );

	$( "#btech_slider-range" ).slider({
		range: true,
		min: 0,
		max: 100,
		values: [ 40, 100 ],
		slide: function( event, ui ) {
			$( "fieldset#btech > #percentage" ).val( ui.values[ 0 ] + "-" + ui.values[ 1 ] );
		}
	});
	$( "fieldset#btech > #percentage" ).val( $( "#btech_slider-range" ).slider( "values", 0 ) +
		"-" + $( "#btech_slider-range" ).slider( "values", 1 ) );

	$( "#diploma_slider-range" ).slider({
		range: true,
		min: 0,
		max: 100,
		values: [ 40, 100 ],
		slide: function( event, ui ) {
			$( "fieldset#diploma > #percentage" ).val( ui.values[ 0 ] + "-" + ui.values[ 1 ] );
		}
	});
	$( "fieldset#diploma > #percentage" ).val( $( "#diploma_slider-range" ).slider( "values", 0 ) +
		"-" + $( "#diploma_slider-range" ).slider( "values", 1 ) );

	function submit_personal_values()
	{
		var personal_values={};
		var dob = {};
		var annual_income = {};
		
		if($('#gender').val()!='Any')
			personal_values['0gender'] = $('#gender').val();
		if($('#cast_id').val()!='Any')
			personal_values['0cast_id'] = $('#cast_id').val();
		if($('#religion_id').val()!='Any')
			personal_values['0religion_id'] = $('#religion_id').val();
		if($("#dob_from").val()!='')
			dob['from'] = $("#dob_from").val();
		if($("#dob_to").val()!='')
			dob['to'] = $("#dob_to").val();
		if(dob['from']!=null || dob['to']!=null)
			personal_values['0dob'] = dob;
		
		if($("#annual_income_from").val()!='')
			annual_income['from'] = $("#annual_income_from").val();
		if($("#annual_income_to").val()!='')
			annual_income['to'] = $("#annual_income_to").val();
		if(annual_income['from']!=null || annual_income['to']!=null)
			personal_values['1annual_income'] = annual_income;

		if($('fieldset#btech > #discipline_id').val() != 'Any')
			personal_values['discipline_id'] = $('fieldset#btech > #discipline_id').val();

		if($('fieldset#btech > #passing_year').val() != 'Any')
			personal_values['batch_start'] = $('fieldset#btech > #passing_year').val();

		personal_values['programme_id'] = 'B.TECH';
		
		var urlsubmitpersonal = "http://core.aceambala.com/search/search";
		$.ajax({
    		url : urlsubmitpersonal,
    		dataType : 'jsonp',
    		data : {
        			myarray:personal_values,
					format:'jsonp'
        			},
    		success: function(jStatus){
    			if(jStatus != 'false')
				{
    				var i=0;
    				$.each(jStatus,function(index,value){
						personal_result[i] = value;
						i++;
        			});
				}
    			submit_academic_values();
    		},
            error: function(response) {
				$('#errorBox').text(response.responseText).parent().show();
    			console.log(response);
    		}
		});
	}

	function submit_academic_values()
	{
		var academic_values = {};
		
		if($('fieldset#tenth > #passing_year').val() != 'Any')
			academic_values['0passing_year'] = $('fieldset#tenth > #passing_year').val();
		
		var tenth_percentage = $('fieldset#tenth > #percentage').val();
		var tenth_l = tenth_percentage.substring(0,tenth_percentage.search('-'));
		var tenth_u = tenth_percentage.substring(tenth_percentage.search('-')+1,tenth_percentage.length);

		academic_values['0percentage'] = {'from':tenth_l, 'to':tenth_u};

		if($('fieldset#twelfth > #passing_year').val() != 'Any')
			academic_values['1passing_year'] = $('fieldset#twelfth > #passing_year').val();
		
		var twelfth_percentage = $('fieldset#twelfth > #percentage').val();
		var twelfth_l = twelfth_percentage.substring(0,twelfth_percentage.search('-'));
		var twelfth_u = twelfth_percentage.substring(twelfth_percentage.search('-')+1,twelfth_percentage.length);

		academic_values['1percentage'] = {'from':twelfth_l, 'to':twelfth_u};

		if($('fieldset#diploma > #passing_year').val() != 'Any')
			academic_values['2passing_year'] = $('fieldset#diploma > #passing_year').val();
		
		var diploma_percentage = $('fieldset#diploma > #percentage').val();
		var diploma_l = diploma_percentage.substring(0,diploma_percentage.search('-'));
		var diploma_u = diploma_percentage.substring(diploma_percentage.search('-')+1,diploma_percentage.length);

		academic_values['2percentage'] = {'from':diploma_l, 'to':diploma_u};
		
		var btech_percentage = $('fieldset#btech > #percentage').val();
		var btech_l = btech_percentage.substring(0,btech_percentage.search('-'));
		var btech_u = btech_percentage.substring(btech_percentage.search('-')+1,btech_percentage.length);

		academic_values['3percentage'] = {'from':btech_l, 'to':btech_u};

		academic_values['backlogs'] = $('#backlogs').val();
		
		var urlsubmitacademic = "http://academic.aceambala.com/search/search";
		$.ajax({
    		url : urlsubmitacademic,
    		dataType : 'jsonp',
    		data : {
        			myarray : academic_values,
					format : 'jsonp'
        			},
    		success: function(jStatus){
				if(jStatus != 'false')
				{
					var i=0;
    				$.each(jStatus,function(index,value){
						academic_result[i] = value;
						i++;
        			});
				}

				intersect_arrays();
    		},
            error: function(response) {
				$('#errorBox').text(response.responseText).parent().show();
    			console.log(response);
    		}
		});
	}

	function intersect_arrays()
	{
		personal_result.sort();
		academic_result.sort();
		var i=j=0;
		ret=[];
		while(i<personal_result.length && j<academic_result.length)
		{
			if(personal_result[i]<academic_result[j])
				i++;
			else if(academic_result[j]<personal_result[i])
				j++;
			else 
			{
				ret.push(personal_result[i]);
				i++,j++;
			}
		}
		
	}

</script>

<style type="text/css">
	.main_div{
		background-color: #F9F9F9;
		border: 0.1em solid #D1D1D1;
		border-radius:4px;	
	}
	.heading {
		background-color:#E1E1E1;
	}
	.heading > h4{
		font-size: 1.1em;
		margin-top:0px;
		margin-bottom:10px;
		padding:2px 0 2px 10px;
	}
	.search_field_div{
		padding:2px;
	}
	fieldset{
		padding:5px 20px 5px 5px;
		line-height: 2.6em;
		border:0.1em solid #F9F9F9;
	}
</style>