
<!--[if lte ie 7]>
      <style type="text/css" media="screen">
        /* Move these to your IE6/7 specific stylesheet if possible */
        .uniForm, .uniForm fieldset, .uniForm .ctrlHolder, .uniForm .formHint, .uniForm .buttonHolder, .uniForm .ctrlHolder ul{ zoom:1; }
      </style>
    <![endif]-->
<div id="progressbar"></div>
<form action="javascript:submit();" class="uniForm">
<h2><?php
$stepNo = $this->stepNo;
echo 'Step '.($stepNo+1).'/'.count($this->steps).': '.ucfirst($this->steps[$stepNo]);?> Information:</h2>
<hr />
<fieldset>
<h3>Enroll</h3>
<div class="ctrlHolder">
<p class="label"><em>*</em>Filling Application for</p>
<ul class="blockLabels">
	<li><label for=""><input name="appType" type="radio" value="btech"
		title="BTECH" class="required">B.Tech</label></li>
	<li><label for=""><input name="appType" type="radio" value="mtech"
		title="MTECH" class="required">M.Tech</label></li>
	
	
</ul>

</div>

<br />
<div class="buttonHolder">
<button type="reset" class="secondaryAction">Reset the form</button>
<button type="submit" class="primaryAction" >Proceed</button>
</div>

</fieldset>
</form>
<script>
	/**@todo
	*apply validate roll number
	**/
	var urlBasicInfo  = "<?php
echo $this->url(array('controller' => 'profile', 'action' => 'settype'))?>";
	
	var type;
	
    $(function(){
        $('form.uniForm').uniform({
            prevent_submit : true
        });

        $('input[name=appType]').change(function(){
            type = this.value;
        	$('.appType').text(' of '+this.title);
        });
      });

    function submit(){
   	 
    	$.ajax({
        	url: urlBasicInfo,
            data : {
          
    		application_type : type
        	},
            success: function(jStatus)
            {
        		window.location = "/profile/degreedetails";
    	    }
           ,
            error: function(response) {
              	  $('#errorBox').text(response.responseText).parent().show();
                    console.log(response);
                    }
                });
    }
    
      
    
</script>
<?php
$this->headScript()->appendFile(
'http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER . '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER . '/plugins/uni-form/css/smooth.uni-form.css');
?>