   
    <!--[if lte ie 7]>
      <style type="text/css" media="screen">
        /* Move these to your IE6/7 specific stylesheet if possible */
        .uniForm, .uniForm fieldset, .uniForm .ctrlHolder, .uniForm .formHint, .uniForm .buttonHolder, .uniForm .ctrlHolder ul{ zoom:1; }
      </style>
    <![endif]-->

    <form action="javascript:submit();" class="uniForm">
        <fieldset>
        <h3>Enroll</h3>
        <div class="ctrlHolder">
          <p class="label"><em>*</em>Application Basis</p>
          <ul class="blockLabels">
            <li><label for=""><input name="appBasis" type="radio" value="aieee" title="AIEEE" class="required">AIEEE</label></li>
            <li><label for=""><input  name="appBasis" type="radio" value="twelth" title="10+2" class="required">10+2</label></li>
            <li><label for=""><input  name="appBasis" type="radio" value="diploma" title="Diploma" class="required">Diploma</label></li>
          </ul>
          <p class="formHint">Basis of Application</p>
        </div>
        <div class="ctrlHolder">
          <label for=""><em>*</em>Roll number</label>
          <input name="rollno" id="rollno"  size="35" maxlength="50" type="text" class="textInput required"/>
          <p class="formHint">Roll number <span class="appBasis" >on above basis.</span></p>
        </div>
        <br/>
      <div class="buttonHolder">
        <button type="reset" class="secondaryAction">Reset the form</button>
        <button type="submit" class="primaryAction">Proceed</button>
      </div>

        </fieldset>
    </form>
	<script>
	var urlCheckRollno = "<?php echo $this->url(array('controller' => 'validate', 'action' => 'rollno'))?>";
	var rollNo;
	var basis;
    $(function(){
        $('form.uniForm').uniform({
            prevent_submit : true
        });

        $('input[name=appBasis]').change(function(){
            basis = this.value;
        	$('.appBasis').text(' of '+this.title);
        });
      });

      function submit() {
    	  rollNo = $('#rollno').val();
          $.ajax({
              url : urlCheckRollno,
              dataType : 'json',
              data : {roll_no: rollNo,
                  	  application_basis:basis},
              success: function(jStatus){
            	  if (confirm("Application not submitted.\nClick 'OK' to continue.")){
            		  window.location = "/applicationform";
            	  }
              },
                  error: function(response) {
                	  $('#errorBox').text(response.responseText).parent().show();
                      console.log(response);
                      }
                  });
      }
    </script>
<?php
$this->headScript()->appendFile('http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
    
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/smooth.uni-form.css');
?>