<?php
    $department = $this->departments;
    $programme = $this->programmes;
?>
<h3>Add New Class</h3>
<form id="batch" class="uniForm" action="javascript:submit_batch_info()">

<fieldset id="batch_info">
	<h5>Please fill this form and click on next to add a new class.</h5>
	<div class="ctrlHolder">
		<label for="department_id"><em>*</em>Department</label>
		<select id="department_id" name="department_id" class="required">
		<option value="">Select the department</option>
		<?php 
		    foreach ($department as $key => $value)
		    {
                echo '<option value="'.$key.'">'.$value.'</option>';
		    }
		?>
		</select>
		<p class="formHint">Select Department</p>
	</div>
					
	<div class="ctrlHolder">
		<label for="programme_id"><em>*</em>Programme</label>
		<select id="programme_id" name="programme_id" class="required">
			<option value="">Select the programme</option>
			<?php 
		    foreach ($programme as $key => $value)
		    {
                echo '<option value="'.$key.'">'.$value.'</option>';
		    }
		?>
		</select>
		<p class="formHint">Select the programme</p>
	</div>
	
	<div class="ctrlHolder">
		<label for="batch_start"><em>*</em>Batch Start</label>
		<select id="batch_start" name="batch_start" class="required">
			<option value="">Select the year</option>
			<?php
			    $current_year = intval(date('Y'));
			    for($i=2002;$i<=$current_year;$i++)
			    {
			        echo '<option value="'.$i.'">'.$i.'</option>';
			    }
			?>
		</select>
		<p class="formHint">Select the starting year of the batch</p>
	</div>
    
   <div id="submitStatus" style="display:none;padding: 1em;" class="ui-state-highlight ui-corner-all" ></div> 
	<div class="buttonHolder">
		<button type="reset" class="secondaryAction">Reset</button>
		<button type="submit" class="primaryAction">Next</button>
	</div>
</fieldset>
</form>


<form id="class" class="uniForm" action="javascript:submit_class_info()">
<fieldset id="class_info">
	<h5>Please fill this form and click on next to add a new class.</h5>
	<div class="ctrlHolder">
		<label for="semester_id"><em>*</em>Semester</label>
		<select id="semester_id" name="semester_id" class="required">
		<option value="">Select the semester</option>
		<?php 
		    for($i=1;$i<=8;$i++)
            {
                echo '<option value="'.$i.'">'.$i.'</option>';
            }
		?>
		</select>
		<p class="formHint">Select Department</p>
	</div>
					
	<div class="ctrlHolder">
		<label for="semester_type"><em>*</em>Semester type</label>
		<input name="semester_type" id="semester_type" value="" data-default-value="e.g. ODD" size="35" maxlength="20" type="text" class="required textInput" readonly="readonly"/>
		<p class="formHint">Select the semster type</p>
	</div>
	
	<div class="ctrlHolder">
		<label for="semester_duration"><em>*</em>Semester Duration (in Months)</label>
		<input name="semester_duration" id="semester_duration" value="" data-default-value="e.g. 3" size="35" maxlength="20" type="text" class="required textInput validateNumber"/>
		<p class="formHint">Select the semster duration</p>
	</div>
	
	<div class="ctrlHolder">
		<label for="handled_by_dept"><em>*</em>Handled By Department</label>
		<select id="handled_by_dept" name="handled_by_dept" class="required">
		<option value="">Select the department</option>
		<?php 
		    foreach ($department as $key => $value)
		    {
                echo '<option value="'.$key.'">'.$value.'</option>';
		    }
		?>
		</select>
		<p class="formHint">Select Department</p>
	</div>
    
    <div class="ctrlHolder">
		<label for="start_date"><em>*</em>Start Date</label>
		<input name="start_date" id="start_date" data-default-value="2011-04-04" value=""  size="35" maxlength="50" type="text" readonly="readonly" class="textInput required"/>
		<p class="formHint">1. Select year <br/>2. Select Month<br/>3. Click date of start</p>
	</div>
		
    <div class="ctrlHolder">
		<label for="completion_date"><em>*</em>Completion Date</label>
		<input name="completion_date" id="completion_date" data-default-value="2011-04-04" value=""  size="35" maxlength="50" type="text" readonly="readonly" class="required textInput "/>
		<p class="formHint">1. Select year <br/>2. Select Month<br/>3. Click end date</p>
	</div>
    
    <div class="ctrlHolder">
		<label for="is_active">Is Batch Active</label>
		<input name="is_active" id="is_active" type="checkbox" class="checkbox"/>
		<p class="formHint">Click if batch is active</p>
	</div>
	
	<div id="submitStatus" style="display:none;padding: 1em;" class="ui-state-highlight ui-corner-all" ></div> 
	<div class="buttonHolder">
		<button type="reset" class="secondaryAction">Reset</button>
		<button type="submit" class="primaryAction">Next</button>
	</div>
</fieldset>
</form>

<script>

$(function(){
	var batch_no = 0;
	$('form#class').hide(10);
	$('form.uniForm').uniform({
		prevent_submit : true
	});

	serverDateObj = $.datepicker.parseDate('dd-mm-yy', $('#datetext').text());
	$("#start_date").datepicker({
	dateFormat: 'yy-mm-dd',
	changeMonth: true,
		changeYear: true,
		yearRange: '-10:+5',
		onClose : function(dateText, inst) {
			this.focus();
		}
	});
	$("#completion_date").datepicker({
	  	dateFormat: 'yy-mm-dd',
	  	changeMonth: true,
			changeYear: true,
			yearRange: '-10:+5',
			onClose : function(dateText, inst) {
				this.focus();
			}
	});

	$('#semester_id').change(function(){
		var semester_id = parseInt($(this).val(), 10); 
		if(semester_id % 2 == 0)
		{
			$('#semester_type').attr('value','EVEN');
		}
		else
		{
			$('#semester_type').attr('value','ODD');
		}
	});
});       

function submit_batch_info() {
	var urlSaveInfo = '<?php echo $this->url(array('controller' => 'batch', 'action' => 'getbatchids'))?>';
	$.ajax({
		url : urlSaveInfo,
		data : {
				myarray:getBatchValues(),
				format : 'json'
			},
		success: function(jStatus){
			if(jStatus == false)
			{
				var choice = confirm('The batch for selected branch is not registered. Please register the batch first. Click Ok to Add New Batch');
				if(choice)
					window.location.replace('/batch/addbatch');
			}
			else {
				batch_no = jStatus;
				$('form#batch').hide();
				$('form#class').show('slow');
			}
		},
		error: function(response) {
			$('#errorBox').text(response.responseText).parent().show();
			console.log(response);
		}
    });
}

function submit_class_info() {
	var urlSaveInfo = '<?php echo $this->url(array('controller' => 'class', 'action' => 'saveclass'))?>';
	$.ajax({
		url : urlSaveInfo,
		data : {
				myarray:getClassValues(),
				format : 'json'
			},
		success: function(jStatus){
			alert("The information has been saved sucessfully.");
			//window.location.replace("/index/index");
		},
		error: function(response) {
			$('#errorBox').text(response.responseText).parent().show();
			console.log(response);
		}
    });
}

function getBatchValues() {
	var formData = {};
	var batch_params = {};
	$('form#batch :input')
	.each(function(){ 
		batch_params[this.name] = this.value; 
	});
	formData['batch_params'] = batch_params;
	return formData;
}

function getClassValues() {
	var formData = {};
	var class_info = {};
	$('form#class :input')
	.each(function(){ 
		class_info[this.name] = this.value; 
	});
	class_info['is_active'] = $('#is_active').is(':checked')?1:0;
	class_info['batch_id'] = parseInt(batch_no, 10);
	formData['class_info'] = class_info;
	
	return formData;
}
</script>

<style>
	.uniForm{
		background-color:white;
		padding:10px 10px 10px 25px;
		border:1px solid #b4c1da;
		margin:-5px 0 40px 0;
		box-shadow:#e4e4e4 0px 0px 1px 1px; 
	}
	h3{
    	color: #343434;
    	line-height: 1;
    	margin: 1.5em -28px;
    	padding: 14px 28px;
		background-color: #ECEFF4;
    	border: 1px solid #B4C1DA;
    	font-size: 17px;
    	font-weight: 100;
    	width: 57%;
	}
	h4{
		padding:3px 3px 3px 10px;
		background-color:#eceff4;
		border:1px solid #b4c1da;
		width:57%;
		font-size:17px;
		font-weight:100;
	}
	h5{
		font-size: 14px;
		font-weight:400;
		margin: 0 0 15px 0;
	}
</style>
<?php
$this->headScript()->appendFile('http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
    
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/smooth.uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/demos/css/demo.css');
?>