<div class="ui-state-hover"><center><H3>Personal Information</H3></center></div>
<div class="info" id="personal_info">
	<table id="info_table" style="width: 100%" cellspacing="6" cellpadding="6">
		
	</table>
</div>

<script type="text/javascript">

    $(function(){
    	$('#topContent').hide();
    	
        var casts = { 1:'General', 2:'OBC', 3: 'SC', 4:'ST', 5:'BC'};
        var religions = { 1:'Hindu', 2:'Muslim', 3:'Sikh', 4:'Christian'};
        var nationalities = { 1:'Indian', 2:'American', 3:'British', 4:'Australian'};
        
        var urlgetinfo = "<?php echo $this->url(array('controller' => 'member', 'action' => 'fetchpersonalinfo'))?>";
        $.ajax({
    		url : urlgetinfo,
    		dataType : 'json',
            data : {format:'json'},
            success: function(jStatus){
            	if((jStatus == null) || (jStatus == false)|| (jStatus == undefined))
    			{
    				$('#info_table').append('No information has been added yet.');
    			}
                else
				{
        			var html = '';
        			html += '<tr class="row"><td><span id="heading">First Name</span><span id="content">'+jStatus['first_name']+'</span></td></tr>';
        			html += '<tr class="row"><td><span id="heading">Last Name</span><span id="content">'+jStatus['last_name']+'</span></td></tr>';
        			html += '<tr class="row"><td><span id="heading">Gender</span><span id="content">'+jStatus['gender']+'</span></td></tr>';
        			html += '<tr class="row"><td><span id="heading">Date of Birth</span><span id="content">'+jStatus['dob']+'</span></td></tr>';
    				html += '<tr class="row"><td><span id="heading">Cast</span><span id="content">'+casts[jStatus['cast_id']]+'</span></td></tr>';
    				html += '<tr class="row"><td><span id="heading">Religion</span><span id="content">'+religions[jStatus['religion_id']]+'</span></td></tr>';
    				html += '<tr class="row"><td><span id="heading">Nationality</span><span id="content">'+nationalities[jStatus['nationality_id']]+'</span></td></tr>';
    				html += '<tr class="row"><td><span id="heading">Blood Group</span><span id="content">'+jStatus['blood_group']+'</span></td></tr>';
        			$('#info_table').append(html);
        			
        			var urlfetchimagelocation = 'http://core.aceambala.com/student/getimagename';
        	        $.ajax({
        				url : urlfetchimagelocation,
        				data : {format : 'jsonp'},
        				dataType : 'jsonp',
        				success : function(jStatus){
        					if((jStatus == null) || (jStatus == false)|| (jStatus == undefined))
        					{
        						var html = '<tr class="row"><td><img src="http://site.cdn.aceambala.com/images/memberimages/dummy.jpg" height = "100" width = "85"></td></tr>';
            					$('#info_table').prepend(html);
        					}
        					else
        					{
                				var html = '<tr class="row"><td><img src="http://site.cdn.aceambala.com/images/memberimages/'+jStatus+'" height = "100" width = "85"></td></tr>';
            					$('#info_table').prepend(html);
        					}
        				},
        				error : function(response){

        				}
        	        });
				}
            },
            error: function(response) {
    			$('#errorBox').text(response.responseText).parent().show();
    			console.log(response);
    		}
    	});
    });
</script>

<style type="text/css">
	.info
	{
		font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
		font-size: 14px;
		margin: 15px;
		text-align: left;
		border-collapse: collapse;
	}
	td span#heading{
		color:red;
		font-size:0.9em;
	}
	td span#content{
		float:right;
		font-size:0.9em;
	}
	table {
      	border-color: #c20f2e;
		width:97%;
	}
	td{
		border-bottom:1px dashed #999;
	}
	tr.heading{
		color:black;
		font-size: 1.3em;
		background-color: #F7F7F7;
		border:1px solid black;
	}
	tr.heading td{
		border:none;
	}
}
</style>