<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="Content-Language" content="en-GB" />
<?php
$baseTheme = 'cupertino';
$module = 'academics';
// Various Servers and Addresses
$baseUrl = $this->baseUrl();
// Content Delievery Server i.e. static Files, e.g. CSS, JS, Themes and related images etc
$cdnServer = 'http://'.CDN_SERVER;
// Images of users, events etc
$imageServer = $baseUrl;
$this->headScript()->setAllowArbitraryAttributes(true);
// Add most common CSS files
$this->headLink()->prependStylesheet(
$cdnServer . '/css/layouts/'.$module.'/default.css');
//Jquery UI Theme
$this->jQuery()->addStylesheet(
$cdnServer . '/css/themes/jqueryui/' . $baseTheme . '/jquery-ui.css');
// Add most common Script files
$this->headScript()->prependFile(
$cdnServer . '/js/plugins/jquery.hoverIntent.minified.js', null,array('async'=>'true', 'defer'=>'defer'));
// Jquery
$this->jQuery()->setLocalPath($cdnServer . '/js/jquery-1.7.min.js', null,array('async'=>'true', 'defer'=>'defer'));
// Jquery UI
$this->jQuery()->setUiLocalPath(
$cdnServer . '/js/jquery-ui-1.8.16.custom.min.js', null,array('async'=>'true', 'defer'=>'defer'));


echo $this->headMeta();
echo $this->headTitle();
echo $this->headLink();
echo $this->jQuery()->uiEnable();
/*
 * set body color by -> style="background-image: url('<?php $cdnServer; ?>/css/themes/jqueryui/<?php echo $baseTheme;?>/images/ui-bg_glass_100_fdf5ce_1x400.png');"
 */
?>
</head> 

<body>
<span class="errorBox" style="top: 0;width:100%; position:fixed; z-index: 99; text-align: center; color: maroon; display: none;" ><span style=" background-color:#eee; padding: 0.5em; "  id="errorBox" >hello</span> <a href="javascript:void(0);">Hide</a></span>
<div id="topContent" class="noprint" ><span id="topRightInfo"> <span
	class="ui-state-default ui-corner-bottom noprint">Today&rsquo;s date: <span
	id="datetext"><?php
$date = new Zend_Date();
echo $date->get(Zend_Date::DATE_MEDIUM)?></span></span>
<?php
if (Zend_Auth::getInstance()->hasIdentity()) {
    ?>
<span class="ui-state-default ui-corner-bottom noprint"><span  class="noprint" >Hi!</span> <span id="userName"><?php
    $authContent = Zend_Auth::getInstance()->getStorage()->read();
    echo $authContent['identity'];
    ?></span></span>
<?php
    if ($authContent['identity'] != 'anon') {
        ?>
	<span class="ui-state-default ui-corner-bl noprint"><a id="logout"
	href="<?php
        echo $this->url(
        array('controller' => 'authenticate', 'action' => 'logout'), 'default')?>">
Logout<span
	class="ui-icon ui-icon ui-icon-closethick ui-state-default ui-corner-br"
	style="float: right; padding-left: 1px; margin-left: -1px;"> </span></a></span>
	<?php
    }
    ?>
<?php
}
?>
</span>

<div id="header"><img
	alt="Ambala College of Engineering and Applied Research"
	src="<?php
echo $cdnServer . '/images/logos/mainLogo_' . $baseTheme . '.png';
?>">

<div id="divTopNav"  class="noprint" >
<ul id="topnav" class="ui-widget">
	<li><a href="http://<?php echo AUTH_SERVER?>" class="main">Home</a></li>
	<li><a href="http://<?php echo LIBRARY_SERVER?>" class="main">Library</a>
	</li>
</ul>
</div>
</div>
</div>




<div class="ui-widget container ui-corner-all"><!--<div id="moduleRibbon"></div>-->
<div id="content">
    <?php
    echo $this->layout()->content;
    ?>
    </div>
<div id="lastDiv"></div>
<?php
echo $this->headScript()?>
</div>
<script>
$('.errorBox').css('opacity', 0.5);

$('.errorBox > a').click(function() {
	$(this).parent().hide();
} );
</script>
</body>
</html>
