

<!--[if lte ie 7]>
      <style type="text/css" media="screen">
        /* Move these to your IE6/7 specific stylesheet if possible */
        .uniForm, .uniForm fieldset, .uniForm .ctrlHolder, .uniForm .formHint, .uniForm .buttonHolder, .uniForm .ctrlHolder ul{ zoom:1; }
      </style>
    <![endif]-->


<form action="javascript:submit();" class="uniForm">
<div id="mtech">
<fieldset>
<h3>M.Tech</h3>

<div class="ctrlHolder"><label for=""><em>*</em>Department</label> <input
	name="deptt" id="deptt" value="" data-default-value="e.g. CSE"
	size="35" maxlength="50" type="text"
	class="textInput required validateAlpha" />
<p class="formHint">Department of <span class="cName">Candidate</span></p>
</div>
<div id="mtech_details" class="ctrlHolder"><label for=""><em>*</em>Marks
Obtained(Semester wise)</label>
<div>
<table id="mtech_sem1_details" cellspacing="">

	<thead></thead>
	
		<tr>
			<td>Code</td>
			<td>Subject Name</td>
			<td>Marks Obtained</td>
			<td>Total Marks</td>
		</tr>
		<tr id="mtech_sem1_row1">
		
			<td><input name="mtech_sem1_subcode1" id="mtech_sem1_subcode1" value=""
				data-default-value="e.g. CSE-712E" size="35" maxlength="50"
				type="text" class="textInput required validateAlpha" /></td>
			<td><input name="mtech_sem1_subname1" id="mtech_sem1_subname1" value=""
				data-default-value="e.g. Data Structures" size="35" maxlength="50"
				type="text" class="textInput required validateAlpha" /></td>
			<td><input name="mtech_sem1_marks1" id="mtech_sem1_marks1" value=""
				data-default-value="e.g. 500" size="35" maxlength="50" type="text"
				class="textInput required validateInteger" /></td>
			<td><input name="mtech_sem1_total_marks1" id="mtech_sem1_total_marks1" value=""
				data-default-value="e.g. 500" size="35" maxlength="50" type="text"
				class="textInput required validateInteger" /></td>
		</tr>

		
</table>
<a href="#" onclick="show_newRow('mtech')">Add</a><br>
<a href="#" onclick="show_newTable('mtech')">Add</a>

</div>
</div>

<div class="ctrlHolder"><label for=""><em>*</em>Total Marks</label> <input
	name="total_marks" id="total_marks" value=""
	data-default-value="e.g. 500" size="35" maxlength="50" type="text"
	class="textInput required validateInteger" />
<p class="formHint">Total Marks obtained</p>
</div>
<div class="ctrlHolder"><label for=""><em>*</em>Cumulative %</label> <input
	name="total_marks" id="total_marks" value=""
	data-default-value="e.g. 76%" size="35" maxlength="50" type="text"
	class="textInput required validateInteger" /></div>

<div class="ctrlHolder"><label for=""><em>*</em>Year of Passing</label>
<input name="passing_year" id="passing_year" value=""
	data-default-value="e.g. 2007" size="35" maxlength="50" type="text"
	class="textInput required validateInteger" />
<p class="formHint">Year in which <span class="cName">Candidate</span>
passed theDegree</p>
</div>
<div class="ctrlHolder">
<p class="label">Passed in first attempt</p>
<ul class="blockLabels alternate">
	<li><label for=""><input name="first_attempt" type="radio"
		value="false" title="No">No</label></li>
	<li><label for=""><input name="first_attempt" type="radio" value="true"
		title="Yes">Yes</label></li>
</ul>
<p class="formHint">Passed in first attempt?</p>
</div>

</div>
</fieldset>

<fieldset>
<h3>B.Tech</h3>
<div class="ctrlHolder"><label for=""><em>*</em>Department</label> <input
	name="deptt" id="deptt" value="" data-default-value="e.g. CSE"
	size="35" maxlength="50" type="text"
	class="textInput required validateAlpha" />
<p class="formHint">Department of <span class="cName">Candidate</span></p>
</div>
<div class="ctrlHolder"><label for=""><em>*</em>Marks Obtained(Semester
wise)</label> <table id="btech_sub_marks" cellspacing="">
	<thead></thead>
	
		<tr>
			<td>Code</td>
			<td>Subject Name</td>
			<td>Marks Obtained</td>
			<td>Total Marks</td>
		</tr>
		<tr id="semester1_row1">
			<td><input name="sub_code1" id="sub_code1" value=""
				data-default-value="e.g. CSE-712E" size="35" maxlength="50"
				type="text" class="textInput required validateAlpha" /></td>
			<td><input name="sub_name1" id="sub_name1" value=""
				data-default-value="e.g. Data Structures" size="35" maxlength="50"
				type="text" class="textInput required validateAlpha" /></td>
			<td><input name="marks1" id="marks1" value=""
				data-default-value="e.g. 500" size="35" maxlength="50" type="text"
				class="textInput required validateInteger" /></td>
			<td><input name="total_marks1" id="total_marks1" value=""
				data-default-value="e.g. 500" size="35" maxlength="50" type="text"
				class="textInput required validateInteger" /></td>
		</tr>
		
</table>
<a href="#" onclick="show_newRow('btech')">Add</a></div>

<div class="ctrlHolder"><label for=""><em>*</em>Total Marks</label> <input
	name="total_marks" id="total_marks" value=""
	data-default-value="e.g. 500" size="35" maxlength="50" type="text"
	class="textInput required validateInteger" />
<p class="formHint">Total Marks obtained</p>
</div>
<div class="ctrlHolder"><label for=""><em>*</em>Cumulative %</label> <input
	name="total_marks" id="total_marks" value=""
	data-default-value="e.g. 76%" size="35" maxlength="50" type="text"
	class="textInput required validateInteger" /></div>

<div class="ctrlHolder"><label for=""><em>*</em>Year of Passing</label>
<input name="passing_year" id="passing_year" value=""
	data-default-value="e.g. 2007" size="35" maxlength="50" type="text"
	class="textInput required validateInteger" />
<p class="formHint">Year in which <span class="cName">Candidate</span>
passed the	degree</p>
</div>
<div class="ctrlHolder">
<p class="label">Passed in first attempt</p>
<ul class="blockLabels alternate">
	<li><label for=""><input name="first_attempt" type="radio"
		value="false" title="No">No</label></li>
	<li><label for=""><input name="first_attempt" type="radio" value="true"
		title="Yes">Yes</label></li>
</ul>
<p class="formHint">Passed in first attempt?</p>
</div>
</fieldset>

<fieldset>
<h3>Diploma Marks</h3>
<div class="ctrlHolder"><label for=""><em>*</em>Rank in DET</label> <input
	name="leet_rank" id="leet_rank"
	value="<?php echo $this->applicant->leet_rank ?>"
	data-default-value="e.g. 450" size="35" maxlength="50" type="text"
	class="textInput required validateInteger" />
<p class="formHint">Rank of <span class="cName">Candidate</span></p>
</div>
<div class="ctrlHolder"><label for=""><em>*</em>Marks Obtained</label> <input
	name="marks_obtained" id="marks_obtained"
	value="<?php echo $this->applicant->marks_obtained ?>"
	data-default-value="e.g. 450" size="35" maxlength="50" type="text"
	class="textInput required validateInteger" />
<p class="formHint">Marks Obtained by <span class="cName">Candidate</span></p>
</div>

<div class="ctrlHolder"><label for=""><em>*</em>Total Marks</label> <input
	name="total_marks" id="total_marks"
	value="<?php echo $this->applicant->total_marks ?>"
	data-default-value="e.g. 500" size="35" maxlength="50" type="text"
	class="textInput required validateInteger" />
<p class="formHint">Total Marks</p>
</div>

<div class="ctrlHolder"><label for=""><em>*</em>Year of Passing</label>
<input name="passing_year" id="passing_year"
	value="<?php echo $this->applicant->passing_year ?>"
	data-default-value="e.g. 2007" size="35" maxlength="50" type="text"
	class="textInput required validateInteger" />
<p class="formHint">Year in which <span class="cName">Candidate</span>
passed theDegree</p>
</div>

<div class="ctrlHolder"><label for=""><em>*</em>Institution</label> <input
	name="institution" id="institution"
	value="<?php echo $this->applicant->institution ?>"
	data-default-value="e.g. Govt. Polytechnic" size="35" maxlength="50"
	type="text" class="textInput required" />
<p class="formHint">Institution in Diploma</p>
</div>

<div class="ctrlHolder"><label for=""><em>*</em>City</label> <input
	name="institution_city" id="institution_city"
	value="<?php echo $this->applicant->institution_city ?>"
	data-default-value="e.g. Ambala" size="35" maxlength="50" type="text"
	class="textInput required" />
<p class="formHint">City of Institution</p>
</div>

<div class="ctrlHolder"><label for=""><em>*</em>State</label> <input
	name="institution_state" id="institution_state"
	value="<?php echo $this->applicant->institution_state ?>"
	data-default-value="e.g. Haryana" size="35" maxlength="50" type="text"
	class="textInput required" />
<p class="formHint">State of Institution</p>
</div>

<div class="ctrlHolder"><label for=""><em>*</em>Branch</label> <input
	name="branch" id="branch"
	value="<?php echo $this->applicant->branch ?>"
	data-default-value="e.g. Computer Science" size="35" maxlength="50"
	type="text" class="textInput required validatePhrase" />
<p class="formHint">Branch of <span class="cName">Candidate</span>(in
full form only)</p>
</div>

<div class="ctrlHolder"><label for=""><em>*</em>University</label> <input
	name="board" id="board" value="<?php echo $this->applicant->board ?>"
	data-default-value="e.g. KUK" size="35" maxlength="50" type="text"
	class="textInput required" />
<p class="formHint">Education University in Diploma</p>
</div>
<div class="ctrlHolder"><label for=""><em>*</em>LEET Marks</label> <input
	name="leet_marks" id="leet_marks"
	value="<?php echo $this->applicant->leet_marks ?>"
	data-default-value="e.g. 120" size="35" maxlength="50" type="text"
	class="textInput validateInteger" />
<p class="formHint">Marks of LEET</p>
</div>
</fieldset>
<fieldset>
<h3>AIEEE</h3>
<div class="ctrlHolder"><label for=""><em>*</em>All India Rank (AIR)</label>
<input name="ai_rank" id="ai_rank"
	value="<?php echo $this->applicant->ai_rank ?>"
	data-default-value="e.g. 450" size="35" maxlength="50" type="text"
	class="textInput required validateInteger" />
<p class="formHint">All India Rank of <span class="cName">Candidate</span></p>
</div>

<div class="ctrlHolder"><label for=""><em>*</em>All India Category Rank</label>
<input name="ai_cat_rank" id="ai_cat_rank"
	value="<?php echo $this->applicant->ai_cat_rank ?>"
	data-default-value="e.g. 500" size="35" maxlength="50" type="text"
	class="textInput required validateInteger" />
<p class="formHint">All India Category Rank of <span class="cName">Candidate</span></p>
</div>

<div class="ctrlHolder"><label for=""><em>*</em>State Rank</label> <input
	name="state_rank" id="state_rank"
	value="<?php echo $this->applicant->state_rank ?>"
	data-default-value="e.g. 90" size="35" maxlength="50" type="text"
	class="textInput required validateInteger" />
<p class="formHint">State Rank of <span class="cName">Candidate</span></p>
</div>

<div class="ctrlHolder"><label for=""><em>*</em>State Category Rank</label>
<input name="state_cat_rank" id="state_cat_rank"
	value="<?php echo $this->applicant->state_cat_rank ?>"
	data-default-value="e.g. 2000" size="35" maxlength="50" type="text"
	class="textInput required validateInteger" />
<p class="formHint">State Category Rank of <span class="cName">Candidate</span></p>
</div>

<div class="ctrlHolder"><label for=""><em>*</em>Application Number</label>
<input name="application_no" id="application_no"
	value="<?php echo $this->applicant->application_no ?>"
	data-default-value="e.g. A234834" size="35" maxlength="50" type="text"
	class="textInput validateAlphaNum" />
<p class="formHint">Application Number of AIEEE Form</p>
</div>
<div class="ctrlHolder"><label for=""><em>*</em>AIEEE Marks</label> <input
	name="aieee_marks" id="aieee_marks"
	value="<?php echo $this->applicant->aieee_marks ?>"
	data-default-value="e.g. 145" size="35" maxlength="50" type="text"
	class="textInput validateInteger" />
<p class="formHint">Marks of AIEEE Form</p>
</div>
</fieldset>

<fieldset>
<h3>Twelfth Marks</h3>

<div class="ctrlHolder"><label for=""><em>*</em>Marks Obtained</label> <input
	name="marks_obtained" id="marks_obtained"
	value="<?php echo $this->applicant->marks_obtained ?>"
	data-default-value="e.g. 450" size="35" maxlength="50" type="text"
	class="textInput required validateInteger" />
<p class="formHint">Marks Obtained by <span class="cName">Candidate</span></p>
</div>

<div class="ctrlHolder"><label for=""><em>*</em>Total Marks</label> <input
	name="total_marks" id="total_marks"
	value="<?php echo $this->applicant->total_marks ?>"
	data-default-value="e.g. 500" size="35" maxlength="50" type="text"
	class="textInput required validateInteger" />
<p class="formHint">Total Marks</p>
</div>

<div class="ctrlHolder"><label for=""><em>*</em>PCM/PCB Percentage</label>
<input name="pcm_percent" id="pcm_percent"
	value="<?php echo $this->applicant->pcm_percent ?>"
	data-default-value="e.g. 90" size="35" maxlength="50" type="text"
	class="textInput required validateNumber  validateMax val-100" />
<p class="formHint">Percentage obtained by <span class="cName">Candidate</span>
in Physics, Chemistry, Math/Biology</p>
</div>

<div class="ctrlHolder"><label for=""><em>*</em> 10+2 Roll no.</label> <input
	name="board_roll" id="board_roll"
	value="<?php echo $this->applicant->board_roll ?>"
	data-default-value="e.g. 2310654" size="35" maxlength="20" type="text"
	class="textInput" />
<p class="formHint">10+2 roll number of <?php echo $this->applicant->first_name?></p>
</div>
<div class="ctrlHolder"><label for=""><em>*</em>Year of Passing</label>
<input name="passing_year" id="passing_year"
	value="<?php echo $this->applicant->passing_year ?>"
	data-default-value="e.g. 2007" size="35" maxlength="50" type="text"
	class="textInput required validateInteger validateMax val-<?php echo date('Y');?>" />
<p class="formHint">Year in which <span class="cName">Candidate</span>
passed the 12th</p>
</div>

<div class="ctrlHolder"><label for=""><em>*</em>Institution</label> <input
	name="institution" id="institution"
	value="<?php echo $this->applicant->institution ?>"
	data-default-value="e.g. Saraswati Senior Secondary School" size="35"
	maxlength="50" type="text" class="textInput required" />
<p class="formHint">Institution in 12th</p>
</div>
<div class="ctrlHolder"><label for=""><em>*</em>City</label> <input
	name="institution_city" id="institution_city"
	value="<?php echo $this->applicant->institution_city ?>"
	data-default-value="e.g. Ambala" size="35" maxlength="50" type="text"
	class="textInput required" />
<p class="formHint">City of Institution</p>
</div>

<div class="ctrlHolder"><label for=""><em>*</em>State</label> <input
	name="institution_state" id="institution_state"
	value="<?php echo $this->applicant->institution_state ?>"
	data-default-value="e.g. Haryana" size="35" maxlength="50" type="text"
	class="textInput required" />
<p class="formHint">State of Institution</p>
</div>
<div class="ctrlHolder"><label for=""><em>*</em>Board</label> <input
	name="board" id="board" value="<?php echo $this->applicant->board ?>"
	data-default-value="e.g. CBSE" size="35" maxlength="50" type="text"
	class="textInput required" />
<p class="formHint">Education Board in 12th</p>
</div>

<div class="ctrlHolder"><label for="">School Rank</label> <input
	name="school_rank" id="school_rank"
	value="<?php echo $this->applicant->school_rank ?>"
	data-default-value="e.g. 1" size="35" maxlength="50" type="text"
	class="textInput validateInteger" />
<p class="formHint">School rank of <span class="cName">Candidate</span></p>
</div>
</fieldset>


<fieldset>
<h3>Matric Information</h3>

<div class="ctrlHolder"><label for=""><em>*</em>Marks Obtained</label> <input
	name="matric_marks_obtained" id="matric_marks_obtained"
	value="<?php echo $this->applicant->matric_marks_obtained ?>"
	data-default-value="e.g. 450" size="35" maxlength="50" type="text"
	class="textInput required validateInteger" />
<p class="formHint">Marks Obtained by <span class="cName">Candidate</span></p>
</div>

<div class="ctrlHolder"><label for=""><em>*</em>Total Marks</label> <input
	name="matric_total_marks" id="matric_total_marks"
	value="<?php echo $this->applicant->matric_total_marks ?>"
	data-default-value="e.g. 500" size="35" maxlength="50" type="text"
	class="textInput required validateInteger" />
<p class="formHint">Total Marks</p>
</div>
          <?php 
          /*
            <div class="ctrlHolder">
            <label for=""><em>*</em>Percentage</label>
            <input name="matric_percentage" id="percentage" data-default-value="e.g. 90" size="35" maxlength="50" type="text" class="textInput required"/>
            <p class="formHint">Percentage obtained by <span class="cName" >Candidate</span></p>
          </div>
           */
          ?>
         
          
          <div class="ctrlHolder"><label for=""><em>*</em> Matric Roll
no.</label> <input name="matric_roll_no" id="matric_roll_no"
	value="<?php echo $this->applicant->matric_roll_no ?>"
	data-default-value="e.g. 10654" size="35" maxlength="20" type="text"
	class="textInput required" />
<p class="formHint">matric(10th) roll number of <?php echo $this->applicant->first_name?></p>
</div>

<div class="ctrlHolder"><label for=""><em>*</em>Institution</label> <input
	name="matric_institution" id="matric_institution"
	value="<?php echo $this->applicant->matric_institution ?>"
	data-default-value="e.g. DAV Public School" size="35" maxlength="50"
	type="text" class="textInput required" />
<p class="formHint">Institution in 10th</p>
</div>

<div class="ctrlHolder"><label for=""><em>*</em>City</label> <input
	name="matric_city" id="matric_city"
	value="<?php echo $this->applicant->matric_city ?>"
	data-default-value="e.g. Kanina" size="35" maxlength="50" type="text"
	class="textInput required" />
<p class="formHint">City of Institution</p>
</div>

<div class="ctrlHolder"><label for=""><em>*</em>State</label> <input
	name="matric_state" id="matric_state"
	value="<?php echo $this->applicant->matric_state ?>"
	data-default-value="e.g. Haryana" size="35" maxlength="50" type="text"
	class="textInput required" />
<p class="formHint">State of Institution</p>
</div>

<div class="ctrlHolder"><label for=""><em>*</em> Board</label> <input
	name="matric_board" id="matric_board"
	value="<?php echo $this->applicant->matric_board ?>"
	data-default-value="e.g. HSBE" size="35" maxlength="20" type="text"
	class="textInput required" />
<p class="formHint">Education Board in matric(10th)</p>
</div>
<div class="ctrlHolder"><label for=""><em>*</em> Passing year</label> <input
	name="matric_passing_year" id="matric_passing_year"
	value="<?php echo $this->applicant->matric_passing_year ?>"
	data-default-value="e.g. 2005" size="35" maxlength="20" type="text"
	class="textInput required validateInteger" />
<p class="formHint">Year in which <?php echo $this->applicant->first_name?> passed the matriculation.</p>
</div>
<div class="ctrlHolder"><label for="">School Rank</label> <input
	name="matric_school_rank" id="matric_school_rank"
	value="<?php echo $this->applicant->matric_school_rank ?>"
	data-default-value="e.g. 3" size="35" maxlength="20" type="text"
	class="textInput validateInteger" />
<p class="formHint">Mention school rank of <?php echo $this->applicant->first_name?> if applicable.</p>
</div>
</fieldset>
<fieldset>
<h3>Misc</h3>
<div class="ctrlHolder"><label for=""><em>*</em>State of Domicile</label>
<input name="state_of_domicile" id="state_of_domicile"
	value="<?php echo $this->applicant->state_of_domicile ?>"
	data-default-value="e.g. Haryana" size="35" maxlength="50" type="text"
	class="textInput required validatePhrase" />
<p class="formHint">State of Domicile.</p>
</div>

<div class="ctrlHolder">
<p class="label">Compartment(s)</p>
<ul class="blockLabels alternate">
	<li><label for=""><input name="compartments" type="radio" value="false"
		<?php if (isset($this->applicant->compartments)) {
                echo ('false' == strtolower($this->applicant->compartments)?'checked="checked"':'');
            } else {echo 'checked="checked"';} ?>
		title="No">No</label></li>
	<li><label for=""><input name="compartments" type="radio" value="true"
		<?php echo ('true' == strtolower($this->applicant->compartments)?'checked="checked"':'') ?>
		title="Yes">Yes</label></li>
</ul>
<p class="formHint">Does the <?php echo $this->applicant->first_name?> has any compartment?</p>
</div>


<div class="ctrlHolder">
<p class="label">Passed in first attempt</p>
<ul class="blockLabels alternate">
	<li><label for=""><input name="first_attempt" type="radio"
		value="false"
		<?php echo ('false' == strtolower($this->applicant->first_attempt)?'checked="checked"':'') ?>
		title="No">No</label></li>
	<li><label for=""><input name="first_attempt" type="radio" value="true"
		<?php if (isset($this->applicant->first_attempt)) {
                echo ('true' == strtolower($this->applicant->first_attempt)?'checked="checked"':'');
            } else {echo 'checked="checked"';} ?>
		title="Yes">Yes</label></li>
</ul>
<p class="formHint">Passed in first attempt?</p>
</div>

<div class="ctrlHolder">
<p class="label">Ever disqualified</p>
<ul class="blockLabels alternate">
	<li><label for=""><input name="ever_disqualified" type="radio"
		value="false"
		<?php if (isset($this->applicant->ever_disqualified)) {
                echo ('false' == strtolower($this->applicant->ever_disqualified)?'checked="checked"':'');
            } else {echo 'checked="checked"';} ?>
		title="No">No</label></li>
	<li><label for=""><input name="ever_disqualified" type="radio"
		value="true"
		<?php echo ('true' == strtolower($this->applicant->ever_disqualified)?'checked="checked"':'') ?>
		title="Yes">Yes</label></li>
</ul>
<p class="formHint">Ever disqualified from exam/studies?</p>
</div>
</fieldset>
<div id="submitStatus" style="display: none; padding: 1em;"
	class="ui-state-highlight ui-corner-all"></div>

<div class="buttonHolder">
<button type="reset" class="secondaryAction">Reset</button>
<button type="submit" class="primaryAction">Next</button>
</div>
</form>

<script>
	var row_no = 1;
	var urlAcadmicInfo = "<?php echo $this->url(array('controller' => 'applicationform', 'action' => 'academicprofile'));?>";

    $(function(){
  		
        $('form.uniForm').uniform({
          prevent_submit : false
        });
    });

    function calcPercent(marks,total) {
        return ((marks/total)*100).toFixed(2);
    }
      function submit() {
          $.ajax({
              url : urlAcadmicInfo,
              data : getValues(),
              success: function(jStatus){
                
       },
                  error: function(response) {
                	  $('#errorBox').text(response.responseText).parent().show();
                      console.log(response);
                      }
                  });
      }
      function getValues() {
          var formData = {}; 
          $('form.uniForm :input')
          		.not('button,:input[value^="e.g."]')
          		.each(function(){ 
          			formData[this.name] = this.value; 
              });

          var compartments = $('input:radio[name=compartments]:checked').val();
          formData.compartments = compartments; 
          
          var first_attempt = $('input:radio[name=first_attempt]:checked').val();
          formData.first_attempt = first_attempt; 
    
          var ever_disqualified = $('input:radio[name=ever_disqualified]:checked').val();
          formData.ever_disqualified = ever_disqualified;


          var marks = parseInt($('#marks_obtained').val());
          var total = parseInt($('#total_marks').val());
          formData.percentage = calcPercent(marks,total);

          marks = parseInt($('#matric_marks_obtained').val());
          total = parseInt($('#matric_total_marks').val());
          formData.matric_percentage = calcPercent(marks,total);
          
		return formData;
	}
      
      
      /*function show_newRow(programe) {
          alert(i);
          i++;
          var tableName = "#"+programe+"_sub_marks tr:last";
          var rowName = "#"+programe+"_sub_marks tr:last";
    	  $(tableName).clone(true).insertAfter(rowName);
           return false;   
      }*/
      function show_newRow(program){
    	  row_no++;
    	  var tableName = "#"+program+"_sem1_details";
          var abc = "<tr id='mtech_sem1_row"+row_no+"'>"
			+" <td><input name='mtech_sem1_subcode"+row_no+"' id='mtech_sem1_subcode"+row_no+"' value='' "
			+"data-default-value='e.g. CSE-712E' size='35' maxlength='50 '"
			+"type='text' class='textInput required validateAlpha' /></td>"
			+"<td><input name='mtech_sem1_sub_name"+row_no+"' id='mtech_sem1_sub_name"+row_no+"' value='' "
			+"data-default-value='e.g. Data Structures' size='35' maxlength='50' "
			+"type='text' class='textInput required validateAlpha' /></td> "
			+"<td><input name='mtech_sem1_marks"+row_no+"' id='mtech_sem1_marks"+row_no+"' value='' "
			+"data-default-value='e.g. 500' size='35' maxlength='50' type='text' "
			+"class='textInput required validateInteger' /></td> "
			+"<td><input name='mtech_sem1_total_marks"+row_no+"' id='mtech_sem1_total_marks"+row_no+"' value=' '"
			+"data-default-value='e.g. 500' size='35' maxlength='50' type='text' "
			+"class='textInput required validateInteger' /></td>"
			+"</tr>";
			alert(abc);
      	   $(tableName).append(abc);
      	   //$(tableName).show();
         }

      function show_newTable(program){
    	  i++;
    	  //var tableName ="#"+program+"_sub_marks";
    	  var tableName = "#"+program+"_sem_marks1";
    	  var abc= "<table id='mtech_sub_marks"+i+"'>"
    	+"<thead> "
  		+"</thead> "
	    +"<tr> "
		+"<td>Code</td> "
		+"<td>Subject Name</td> "
		+"<td>Marks Obtained</td> "
		+"<td>Total Marks</td> "
		+"</tr> "
		+"<tr id='semester1_row1'> "
		+"<td><input name='sub_code1' id='sub_code1' value='' "
		+"data-default-value='e.g. CSE-712E' size='35' maxlength='50' "
		+"type='text' class='textInput required validateAlpha' /></td> "
		+"<td><input name='sub_name1' id='sub_name1' value='' "
		+"data-default-value='e.g. Data Structures' size='35' maxlength='50' "
		+"type='text' class='textInput required validateAlpha' /></td> "
		+"<td><input name='marks1' id='marks1' value='' "
		+"data-default-value='e.g. 500' size='35' maxlength='50' type='text'' "
		+"class='textInput required validateInteger' /></td>"
		+"<td><input name='total_marks' id='total_marks' value=' '"
		+"data-default-value='e.g. 500' size='35' maxlength='50' type='text' "
		+"class='textInput required validateInteger' /></td>"
		+"</tr>"
		+"</table>"
		+"<a href='#' onclick='show_newRow('mtech')'>Add</a><br>"
		+"<a href='#' onclick='show_newTable('mtech')'>Add</a>";
	    
        $(tableName).append(abc);
    	}
     
     
    </script>

<?php
$this->headScript()->appendFile('http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
    
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/smooth.uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/demos/css/demo.css');
?>