<!--[if lte ie 7]>
      <style type="text/css" media="screen">
        /* Move these to your IE6/7 specific stylesheet if possible */
        .uniForm, .uniForm fieldset, .uniForm .ctrlHolder, .uniForm .formHint, .uniForm .buttonHolder, .uniForm .ctrlHolder ul{ zoom:1; }
      </style>
    <![endif]-->


<form action="javascript:submit();" class="uniForm">
<h2>Career Details</h2>
        
        <fieldset>
        <h3>Basic Skills</h3>

        <div class="ctrlHolder">
            <label for=""><em>*</em>Feild</label>
            <input name="" id="" value="" data-default-value="e.g. C, C++" size="35" maxlength="50" type="text" class="textInput required validateInteger"/>
            <p class="formHint">Technical feild known by <span class="cName" >Candidate</span></p>
          </div>
          
          <div class="ctrlHolder">
            <label for=""><em>*</em>Proficiency</label>
             <select id="profiency" name="profiency" class="selectInput required">
          		<option value="EXPERT">Expert</option>
          		<option value="INTERMEDIATE">Intermediate</option>
          		<option value="BASIC">Beginner</option>
      	  </select>
            <p class="formHint">Select the proficiency level</p>
          </div>
          <div class="ctrlHolder">
            <label for=""><em>*</em>Technical Stream</label>
            <input name="matric_percentage" id="percentage" data-default-value="e.g. 90" size="35" maxlength="50" type="text" class="textInput required"/>
            <p class="formHint">Percentage obtained by <span class="cName" >Candidate</span></p>
          </div>
      </fieldset>
      <fieldset><h3>Professional Certification</h3>
          <div class="ctrlHolder">
            <label for="technical_feild"><em>*</em>Technical Feild</label>
            <select id="technical_feild" name="technical_feild" class="selectInput required">
          		<option value="Networking">Networking</option>
          		
      	  </select>
            <p class="formHint">Technical feild in which certification is done </p>
          </div>
          <div class="ctrlHolder">
            <label for=""><em>*</em>Certification Name</label>
            <select id="technical_sector" name="technical_sector" class="selectInput required">
          		<option value="CCNA">CCNA</option>
          		<option value="OCP">OCP</option>
          		<option value="RHCE">RHCE</option>
      	  </select>
      	  <p class="formHint">Select name of Professional certification </p>
           
          </div></fieldset>
<fieldset>
<h3>Training</h3>
           <div class="ctrlHolder">
            <label for="technical_feild"><em>*</em>Technical Feild</label>
            <select id="technical_feild" name="technical_feild" class="selectInput required">
          		<option value="Networking">Networking</option>
          		
      	  </select>
            <p class="formHint">Technical feild in which training is done </p>
          </div>
          <div class="ctrlHolder">
            <label for=""><em>*</em>Training Technology</label>
            <select id="technical_sector" name="technical_sector" class="selectInput required">
          		<option value="CCNA">CCNA</option>
          		<option value="OCP">OCP</option>
          		<option value="RHCE">RHCE</option>
      	  </select>
           <p class="formHint">Technology in which training is done </p>
          </div>
          </fieldset> 
          
        
   <fieldset>
   <h3>Languages Known</h3>
         <div class="ctrlHolder">
            <label for=""><em>*</em>Languages Known</label>
            <select id="language_id" name="language_id" class="selectInput required">
          		<option value="1">Hindi</option>
          		<option value="2">English</option>
          		<option value="3">Punjabi</option>
          		<option value="4">Foreign</option>
      	  </select>
           <p class="formHint">Languages Known by <span class="cName" >Candidate</span> </p>
          </div>
          
          <div class="ctrlHolder">
            <label for=""><em>*</em>Total Marks</label>
            <select id="language_id" name="language_id" class="selectInput required">
          		<option value="READ">Read</option>
          		<option value="WRITE">Write</option>
          		<option value="SPEAK">Speak</option>
          		<option value="ALL">All</option>
      	  </select>
            <p class="formHint">Select proficiency</p>
          </div>
            </fieldset>
   <fieldset>
   
          <h3>Prefrences</h3>
        	<div class="ctrlHolder">
            <ul class="blockLabels alternate">
            <li><label for="IT"><input name="IT" type="radio" value="false"   title="No" >IT</label></li>
            <li><label for="core"><input  name="core" type="radio" value="true"   title="Yes" >Core </label></li>
            <li><label for="defence"><input  name="defence" type="radio" value="true"   title="Yes" >Defence</label></li>
            <li><label for="government"><input  name="government" type="radio" value="true"   title="Yes" >Govt</label></li>
          </ul>
          <p class="formHint">Filter on basis of the job preferred </p>
          </div>
          </fieldset>       
          
        
        <div id="submitStatus" style="display:none;padding: 1em;" class="ui-state-highlight ui-corner-all" ></div>
        
        <div class="buttonHolder">
        	<button type="submit" class="secondaryAction">Cancel and go back</button>
        	<button type="submit" class="primaryAction">Next</button>
    	</div>
    	<br>
    </div>
</form>
    
<script>
var urlBasicInfo  = "<?php echo $this->url(array('controller' => 'student', 'action' => 'personalprofile'))?>";
$(function(){
  $('form.uniForm').uniform({
    prevent_submit : true
  });

  serverDateObj = $.datepicker.parseDate('dd-mm-yy', $('#datetext').text());
  $("#dob").datepicker({
  	dateFormat: 'yy-mm-dd',
  	changeMonth: true,
		changeYear: true,
		yearRange: '-25:-15',
		onClose : function(dateText, inst) {
			this.focus();
		}
  });
});       
 $('#first_name').change(function(){
      var cName = this.value;
  	$('.cName').text(cName);
  });
  

function submit() {
    $.ajax({
        url : urlBasicInfo,
        data : getValues(),
        success: function(jStatus){
            
        },
            error: function(response) {
          	  $('#errorBox').text(response.responseText).parent().show();
                console.log(response);
                }
            });
}

  function getValues() {
      var formData = {}; 
      $('form.uniForm :input')
      		.not('button,#e_mail_confirm,:input[value^="e.g."]')
      		.each(function(){ 
      			formData[this.name] = this.value; 
          });
  var gender = $('input:radio[name=gender]:checked').val();
  formData.gender = gender; 
	return formData;
}
</script>
<?php
$this->headScript()->appendFile('http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
    
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/smooth.uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/demos/css/demo.css');
?>
    