<h2>Experience<span id="goback"><a href="<?php echo $this->url(array('controller' => 'student', 'action' => 'profile'))?>">Go back to profile page</a></span></h2>
<form action="javascript:submit();" class="uniForm">
      
 <fieldset>

          	<div class="ctrlHolder">
					<label for="">Industry</label>
					<input name="industry_name" id="industry_name" value="" data-default-value="e.g. Allsoft Solutions" size="35" maxlength="50" type="text" class="textInput required"/>
					<p class="formHint">Name of the industry</p>
				</div>
			<div class="ctrlHolder">
				<label for="">Functional Area</label>
				<input name="functional_area_name" id="functional_area_name" value="" data-default-value="e.g.Software Development" size="35" maxlength="50" type="text" class="textInput required"/>
				<p class="formHint">Semester after which training is taken</p>
			</div>
				 
			<div class="ctrlHolder">
				<label for="">Role</label>
				<input name="role_name" id="role_name" value="" data-default-value="e.g.Coder" size="35" maxlength="50" type="text" class="textInput required"/>
				<p class="formHint">Semester after which training is taken</p>
			</div>
			<div class="ctrlHolder">
					<label for="">Experience </label>
					<input name="experience_years" id="experience_years" value="" data-default-value="e.g. 2 years" size="35" maxlength="50" type="text" class="textInput validateInteger"/>
					<p class="formHint">Exeprience in number of years</p>
			</div>	 
         
        
          
          </fieldset> 
             
      </form>
      
  <script>

$(function(){
  $('form.uniForm').uniform({
    prevent_submit : true
  });

  serverDateObj = $.datepicker.parseDate('dd-mm-yy', $('#datetext').text());
  $("#date").datepicker({
  	dateFormat: 'yy-mm-dd',
  	changeMonth: true,
		changeYear: true,
		yearRange: '-25:-15',
		onClose : function(dateText, inst) {
			this.focus();
		}
  });
});       
 
  

function submit() {
    $.ajax({
        url : urlBasicInfo,
        data : getValues(),
        success: function(jStatus){
            
        },
            error: function(response) {
          	  $('#errorBox').text(response.responseText).parent().show();
                console.log(response);
                }
            });
}

  function getValues() {
      var formData = {}; 
      $('form.uniForm :input')
      		.not('button,#e_mail_confirm,:input[value^="e.g."]')
      		.each(function(){ 
      			formData[this.name] = this.value; 
          });
  
	return formData;
}
</script>
<style>
	.uniForm{
		background-color:white;
		padding:10px 10px 10px 25px;
		border:1px solid #b4c1da;
		margin:-5px 0 40px 0;
		box-shadow:#e4e4e4 0px 0px 1px 1px; 
	}
	h2,h3{
		padding:3px 3px 3px 10px;
		background-color:#eceff4;
		border:1px solid #b4c1da;
		width:57%;
		font-size:17px;
		font-weight:100;
	}
	#goback a{
		float:right;
		color:red;
		font-size:14px;
		text-decoration: none;
	}
</style>
<?php
$this->headScript()->appendFile('http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
    
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/smooth.uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/demos/css/demo.css');
?>
    