<?php
	$skills = $this->skill_info;
?>

<h2>Skill Set</h2>
<form action="javascript:submit();" class="uniForm">
<fieldset>
	<?php
		echo '<div class="ctrlHolder"><label for="skill_id"><em>*</em>Name</label>';
			echo '<select id="skill_id" name="skill_id" class="selectInput required" readonly="readonly">';
   				echo '<option value="'.$skills['skill_id'].'">'.$skills['skill_name'].'</option>';
			echo '</select>';
			echo '<p class="formHint">Name of the skill known by Candidate</p>';
		echo '</div>';
   	?>

	<div class="ctrlHolder"><label for="proficiency"><em>*</em>Proficiency</label>
		<select id="proficiency" name="proficiency" class="selectInput required">
			<option value="EXPERT">Expert</option>
			<option value="INTERMEDIATE">Intermediate</option>
			<option value="BASIC">Beginner</option>
		</select>
		<p class="formHint">Select the proficiency level</p>
	</div>
</fieldset>

<div id="submitStatus" style="display: none; padding: 1em;"
	class="ui-state-highlight ui-corner-all"></div>

<div class="buttonHolder">
	<button type="submit" class="secondaryAction">Cancel and go back</button>
	<button type="submit" class="primaryAction">Next</button>
</div>
</form>

<script>

	$(function(){
  		$('form.uniForm').uniform({
    		prevent_submit : true
 		});

  	var proficiency = '<?php echo $skills['proficiency']?>';
  		$('#proficiency').val(proficiency);
	});

	function submit() {
		var urlSaveInfo = '<?php echo $this->url(array('controller' => 'student', 'action' => 'saveskills'))?>';
    	$.ajax({
        	url : urlSaveInfo,
        	data : {myarray : getValues()},
        	success: function(jStatus){
        		alert("Your information has been submitted successfully");
                window.location.replace("/student/viewskillinfo");
        	},
            error: function(response) {
          	  $('#errorBox').text(response.responseText).parent().show();
                console.log(response);
                }
            });
	}	

	function getValues() {
		var formData = {};
		var skill_info = {};

		skill_info['skill_id'] = '<?php echo $skills['skill_id']?>';
		skill_info['proficiency'] = $('#proficiency').val();
		
	    formData['skill_info'] = skill_info;

		return formData;
	}
</script>
<style>
	.uniForm{
		background-color:white;
		padding:10px 10px 10px 25px;
		border:1px solid #b4c1da;
		margin:-5px 0 40px 0;
		box-shadow:#e4e4e4 0px 0px 1px 1px;
		width:auto;
	}
	h2,h3{
		padding:3px 3px 3px 10px;
		background-color:#eceff4;
		border:1px solid #b4c1da;
		font-size:17px;
		font-weight:100;
		margin-top:2px;
	}
	#goback a{
		float:right;
		color:red;
		font-size:14px;
		text-decoration: none;
	}
</style>
<?php
$this->headScript()->appendFile(
'http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER . '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER . '/plugins/uni-form/css/smooth.uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER . '/plugins/uni-form/demos/css/demo.css');
?>