<?php
	$emptestinfo = $this->response['employability_test'];
	$certifications = $this->response['certifications'];
	$training = $this->response['training'];
	$experience = $this->response['experience'];
	$languages_known = $this->response['language'];
	$job_preferred = $this->response['job_preferred'];
	$co_curricular = $this->response['co_curricular'];
	$job_preferred = $this->response['job_preferred'];
?>

<div id="student_navigation">
	<img alt="Student" id="student_img" width="40" height="46">
	<ul id="list">
		<li id="core_link"><a href="http://core.aceambala.com/student">Core Profile</a></li>
		<li id="academic_link"><a href="http://academic.aceambala.com/student">Academic Profile</a></li>
		<li id="tnp_link"><a href="http://tnp.aceambala.com/student">TNP Profile</a></li>
	</ul>
</div>
<br>

<link rel="stylesheet" href="<?php echo 'http://'. CDN_SERVER . '/css/admission.css';?>">

<div id="main">
	<div id="sidebar" style="float:left">
	<ul class="menu">
		<li class="item1">
			<a href="#">Employability Test</a>
			<ul>
				<li class="subitem1"><a href="/student/viewemptestrecord" target="content_frame">View</a></li>
				<li class="subitem1"><a href="/student/addemptestrecord" target="content_frame">Add/Edit</a></li>
			</ul>
		</li>

		<li class="item2">
			<a href="#">Certifications</a>
			<ul>
				<li class="subitem1"><a href="/student/addcertificationinfo" target="content_frame">Add/Edit</a></li>
				<li class="subitem1"><a href="/student/viewcertificationinfo" target="content_frame">View</a></li>
			</ul>
		</li>

		<li class="item3">
			<a href="#">Training</a>
			<ul>
				<li class="subitem1"><a href="/student/addtraininginfo" target="content_frame">Add/Edit</a></li>
				<li class="subitem1"><a href="/student/viewtraininginfo" target="content_frame">View</a></li>
			</ul>
		</li>

		<li class="item4">
			<a href="#">Languages Known</a>
			<ul>
				<li class="subitem1"><a href="/student/addmemberlanguage" target="content_frame">Add/Edit</a></li>
				<li class="subitem1"><a href="/student/viewlanguagesknown" target="content_frame">View</a></li>
			</ul>
		</li>

		<li class="item5">
			<a href="#">Skills</a>
			<ul>
				<li class="subitem1"><a href="/student/addmemberskill" target="content_frame">Add/Edit</a></li>
				<li class="subitem1"><a href="/student/viewskillinfo" target="content_frame">View</a></li>
			</ul>
		</li>

		<li class="item6">
			<a href="#">Co Curricular</a>
			<ul>
				<li class="subitem1"><a href="/student/editcocurricular" target="content_frame">Add/Edit</a></li>
				<li class="subitem1"><a href="/student/viewcocurricular" target="content_frame">View </a></li>
			</ul>
		</li>
		
		<li class="item6">
			<a href="#">Job Preferred</a>
			<ul>
				<li class="subitem1"><a href="/student/addjobpreferred" target="content_frame">Add/Edit</a></li>
				<li class="subitem1"><a href="/student/viewjobpreferred" target="content_frame">View </a></li>
			</ul>
		</li>
	</ul>
	</div>
	<div id="page_content">
		<iframe id="content_frame" name="content_frame" width="100%" height="900" frameborder="0" scrolling="auto" onload="hide_top()"></iframe>
	</div>
</div>

<script type="text/javascript">
	$(function() {

		$('#topnav').hide();
		$('#tnp_link').css('background-color','#b3cdd6');
		$('#tnp_link').css('border','1px solid black');
		$('#tnp_link').css('padding','5px 6px');

		var urlfetchimagelocation = 'http://core.aceambala.com/student/getimagename';
        $.ajax({
			url : urlfetchimagelocation,
			data : {format : 'jsonp'},
			dataType : 'jsonp',
			success : function(jStatus){
				if((jStatus == null) || (jStatus == false)|| (jStatus == undefined))
					$('#student_img').attr('src','http://site.cdn.aceambala.com/images/memberimages/dummy.jpg');
				else
					$('#student_img').attr('src','http://site.cdn.aceambala.com/images/memberimages/'+jStatus);
			},
			error : function(response){

			}
        });
		
        var menu_ul = $('.menu > li > ul'),
		menu_a  = $('.menu > li > a');

        menu_ul.hide();
    
        menu_a.click(function(e) {
			e.preventDefault();
            if(!$(this).hasClass('active')) {
                menu_a.removeClass('active');
                menu_ul.filter(':visible').slideUp('normal');
                $(this).addClass('active').next().stop(true,true).slideDown('normal');
            } else {
                $(this).removeClass('active');
                $(this).next().stop(true,true).slideUp('normal');
            }
        });

        $('.menu > li > a:first').click();
        var path = $('.subitem1 > a').attr('href');
        $('#content_frame').attr('src',path);
    });
	function hide_top()
	{
		$('iframe#content_frame').contents().find('div#topContent').hide();
	}
</script>

<style type="text/css">
	#page_content{
    	float:left;
		width:65%;
    }
    div#main{
    	margin-top:10px;
	}
	.red{
		color:red;
		font-size:1.2em;
	}
	.black{
		color:black;
		font-size:1.2em;
	}
	div#student_navigation{
		background-color:#d6ebf2;
		border:0.1em solid #97afb7;
		border-radius:2px;
		margin:10px 0;
		padding:11px;
	}
	ul#list{
		padding:5px 5px 5px 5px;
		list-style: none outside none;
    	margin: 0;
	}
	ul#list>li{
		display:inline;
		padding:5px 6px 5px 6px;
	}
	ul#list>li:hover{
		display:inline;
		padding:5px 5px 5px 5px;
		background-color:#b3cdd6;
		border: 1px solid black;
	}
	ul#list>li>a{
		text-decoration:none;
		color:black;
	}
	#student_img{
		float:left;
		border:1px solid grey;
		border-radius:2px;
		margin: -5px 10px 0 -3px;
	}
</style>