<?php
	$emptestinfo = $this->response['employability_test'];
	$certifications = $this->response['certifications'];
	$training = $this->response['training'];
	$experience = $this->response['experience'];
	$languages_known = $this->response['language'];
	$job_preferred = $this->response['job_preferred'];
	$co_curricular = $this->response['co_curricular'];
	$skills = $this->response['skills'];
	$job_preferred = $this->response['job_preferred'];
?>

<link rel="stylesheet" href="<?php echo 'http://'. CDN_SERVER . '/css/admission.css';?>">
<h3>Training and Placement</h3>

<div id="main">
	<div id="sidebar" style="float:left">
	<ul class="menu">
		<li class="item1">
			<a href="#">Employability Test</a>
			<ul>
			<?php 
			foreach ($emptestinfo as $test_id => $test_info)
			{
				echo '<li class="subitem1"><a target="content_frame" href="viewtestinfo?employability_test_id='.$test_id.'&test_name='.$test_info['test_name'].'&date_of_conduct='.$test_info['date'].'">';
					echo $test_info['test_name'];
					echo '  ('.$test_info['date'].')';
				echo '</a></li>';
			}
			?>
			<li class="subitem1"><a href="/student/edittestinfo" target="content_frame">Add New</a></li>
			</ul>
		</li>

		<li class="item2">
			<a href="#">Certifications</a>
			<ul>
			<?php 
			foreach ($certifications as $certification_id => $certification_info)
			{
				echo '<li class="subitem1"><a href="viewcertification?certification_id='.$certification_id.'" target="content_frame">';
					echo $certification_info['name'];
				echo '</a></li>';
			}
			?>
			<li class="subitem1"><a href="/student/editcertification" target="content_frame">Add New</a></li>
			</ul>
		</li>

		<li class="item3">
			<a href="#">Experience</a>
			<ul>
			<?php
			foreach ($experience as $experience_id => $experience_info)
			{
				echo '<li class="subitem1"><a href="viewexperience?experience_id='.$experience_id.'" target="content_frame">';
					echo $experience_info['organisation'];
				echo '</a></li>';
			}
			?>
			<li class="subitem1"><a href="/student/editexperience" target="content_frame">Add New</a></li>
			</ul>
		</li>

		<li class="item4">
			<a href="#">Trainings</a>
			<ul>
			<?php 
			foreach ($training as $training_id => $training_info)
			{
				echo '<li class="subitem1"><a href="viewtraining?training_id='.$training_id.'" target="content_frame">';
					echo $training_info['institute'].' ';
					echo $training_info['semester'].'th semester';
				echo '</a></li>';
			}
			?>
			<li class="subitem1"><a href="/student/edittraining" target="content_frame">Add New</a></li>
			</ul>
		</li>

		<li class="item5">
			<a href="#">Languages Known</a>
			<ul>
			<?php 
			foreach ($languages_known as $name => $proficiency)
			{
				//echo '<a href="viewtestinfo?employability_test_id='.$test_id.'&test_name='.$test_info['test_name'].'&date_of_conduct='.$test_info['date'].'">';
				echo '<li class="subitem1"><a href="#">'.$name;
				echo ' ('.$proficiency.')</a></li>';
				//echo '</a>';
			}
			?>
			<li class="subitem1"><a href="/student/editlanguagesknown" target="content_frame">Add New</a></li>
			</ul>
		</li>

		<li class="item6">
			<a href="#">Skills</a>
			<ul>
			<?php 
			foreach ($skills as $name => $proficiency)
			{
				echo '<li class="subitem1"><a href="#">'.$name;
				echo '  '.$proficiency.'</a></li>';
			}
			?>
			<li class="subitem1"><a href="/student/editskills" target="content_frame">Add New</a></li>
			</ul>
		</li>
		
		<li class="item6">
			<a href="#">Co Curricular</a>
			<ul>
			<?php
			if($co_curricular){
				echo '<li class="subitem1"><a href="/student/viewcocurricular" target="content_frame">Co-Curricular View</a></li>';
			}
			else {
				echo '<li class="subitem1"><a href="/student/editcocurricular" target="content_frame">Co-Curricular Create</a></li>';
			}
			?>
			</ul>
		</li>
		
		<li class="item6">
			<a href="#">Job Preferred</a>
			<ul>
			<?php
			echo '<li class="subitem1"><a href="#">'.$job_preferred[0].'</a></li>';
			?>
			<li class="subitem1"><a href="/student/editjobpreferred" target="content_frame">Add New</a></li>
			</ul>
		</li>
	</ul>
	</div>
	<div id="page_content">
		<iframe id="content_frame" name="content_frame" width="850" height="900" frameborder="0" scrolling="auto" onload="hide_top()"></iframe>
	</div>
</div>

<script type="text/javascript">
	$(function() {
        var menu_ul = $('.menu > li > ul'),
		menu_a  = $('.menu > li > a');

        menu_ul.hide();
    
        menu_a.click(function(e) {
			e.preventDefault();
            if(!$(this).hasClass('active')) {
                menu_a.removeClass('active');
                menu_ul.filter(':visible').slideUp('normal');
                $(this).addClass('active').next().stop(true,true).slideDown('normal');
            } else {
                $(this).removeClass('active');
                $(this).next().stop(true,true).slideUp('normal');
            }
        });

        $('.menu > li > a:first').click();
        var path = $('.subitem1 > a').attr('href');
        $('#content_frame').attr('src',path);
    });
	function hide_top()
	{
		$('iframe#content_frame').contents().find('div#topContent').hide();
	}
</script>

<style type="text/css">
	#page_content{
    	float:right;
    }
	.red{
		color:red;
		font-size:1.2em;
	}
	.black{
		color:black;
		font-size:1.2em;
	}
</style>