<?php 
	$test_info = $this->test_info;
	print_r($test_info);
?>
<div class="ui-widget-content ui-corner-all"><center><H3>Employability Test</H3></center></div>
<div id="test_details">
	
<table style="width: 100%" id="corner" cellspacing="10" cellpadding="10">
	<?php 
       	foreach ($test_info as $key => $value) 
    	{   			
        	echo '<tr>';
        		echo '<td><span id="heading">'.ucfirst(str_replace('_',' ',$key)).'</span>';
        		echo '<span id="content">'.$value.'</span></td>';
        	echo '</tr>';
		}  
	?>
</table>
</div>
    
<div id="edit_test" class="ui-widget-content ui-corner-all">
	<h3><center><a href="/student/viewsectionscore?employability_test_id=<?php echo $_GET['employability_test_id']?>&test_name=<?php echo $test_info['test_name']?>&date_of_conduct=<?php echo $test_info['date_of_conduct']?>">View Sectional Score</a></center></h3>
</div>
<div id="goback" class="ui-widget-content ui-corner-all">
	<h3><center><a href="/student/profile">Go Back</a></center></h3>
</div>

<style type="text/css">
	table {
      	border-color: #c20f2e;
		width:97%;
	}
	tr{
		border-bottom:1px dashed #999;
	}
	#corner
	{
		font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
		font-size: 14px;
		margin: 15px;
		text-align: left;
		border-collapse: collapse;
	}
	td span#heading{
		color:red;
	}
	td span#content{
		float:right;
	}
	#edit_test {
		width:50%;
		float:left
	}
	#goback {
		width:45%;
		float:right;
	}
</style>