<div class="ui-widget-content ui-corner-all"><center><H3>Languages Known</H3></center></div>
<div id="lng_details">
    	<table style="width: 100%" id="corner" cellspacing="10" cellpadding="10">
			<tr>
				<th>Name</th>
				<th>Proficiency</th>
			</tr>
            <?php 
        	foreach ($this->language as $skillId => $value) 
        		{
        			echo '<tr>';
        	        echo '<td>'.ucfirst($value['lang_name']).'</td>';
        	        echo '<td>'.ucfirst($value['lang_prof']).'</td>';
        	        
        	        echo '</tr>'; 
        			 
        		}  
            ?>
        	
    	</table>
	</div>
	<div id="edit_lng" class="ui-widget-content ui-corner-all">
	<h3><center><a href="/student/editlanguagesknowninfo">Edit</a></center></h3>
</div>
<style type="text/css">
	table {
      	border-color: #c20f2e;
		width:97%;
	}
	tr{
		border-bottom:1px dashed #999;
	}
	#corner
	{
		font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
		font-size: 14px;
		margin: 15px;
		text-align: left;
		border-collapse: collapse;
	}
</style>