<div class="ui-widget-content ui-corner-all"><center><H3>Employability Test</H3></center></div>
<div id="test_details">
	
	<table style="width: 100%" id="corner" cellspacing="10" cellpadding="10">
			<tr>
				<th>Registration Number</th>
				<th>Test Name</th>
				<th>Total Marks</th>
				<th>Percentile</th>
			</tr>
            <?php 
        	foreach ($this->test as $test => $array) 
        		{
        			
        				echo '<tr>';
        				echo '<td>'.ucfirst($array['test_reg_no']).'</td>';
        	      		echo '<td>'.ucfirst($array['test_name']).'</td>';
        	        	echo '<td>'.ucfirst($array['test_marks']).'</td>';
        	        	echo '<td>'.ucfirst($array['test_percentile']).'</td>';
        	            echo '</tr>';
        			
        		}  
            ?>
            
       	</table>
    	</div>
    
<div id="edit_test" class="ui-widget-content ui-corner-all">
	<h3><center><a href="/student/edittestinfo">Edit</a></center></h3>
</div>
<style type="text/css">
	table {
      	border-color: #c20f2e;
		width:97%;
	}
	tr{
		border-bottom:1px dashed #999;
	}
	#corner
	{
		font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
		font-size: 14px;
		margin: 15px;
		text-align: left;
		border-collapse: collapse;
	}
</style>