<style type="text/css">
#MyProfileDiv label {
	padding: 0.1em;
}
span {
    color: #444444;
    font-weight: normal;
}
</style>
<div id="markattendanceDiv" class="ui-state-default ui-corner-all"  style="padding :1em 0 0 0; text-align: center; " >My Profile
<br><br><table id="corner" cellspacing="10" cellpadding="10" align="center">
<tr>
<th class="ui-widget-content ui-corner-all" style="text-align: center">
<a class="personal_detail_link" href="#">Personal Details</a></th>
		<th class="ui-widget-content ui-corner-all" style="text-align: center">
<a class="academic_detail_link" href="#"> Academic Details </a></th>
		<th class="ui-widget-content ui-corner-all" style="text-align: center">
<a class="career_detail_link" href="#">Career Details</a></th>
	</tr></table>
</div>

<br>
<div class="" id="myProfileDiv"></div>



<script type="text/javascript">
$(function(){
	var urlfetchdetail = "<?php echo 'http://'.CORE_SERVER.'/student/getprofile' ?>"; //rename to studentpersonal

	$.ajax({
    	url : urlfetchdetail,
        dataType : 'jsonp',
        data : {format:'jsonp'},
        success: function(personal_detail){
            table_string = '<table  width="100%" cellspacing="0" cellpadding="3" border="0">';
            $.each(personal_detail,function(index,value){
                if(value==null)
                {
                	table_string += '';
                }             
                else
                {
            		table_string += '<tr><td>'+index.toUpperCase()+'</td>';
                	table_string += '<td>'+value+'</td></tr>';
                }
            });
            $('#myProfileDiv').html(table_string);
          },
       error: function(event) {
            alert(event.responseText);
       }
    });//End ajax call.
});

$(".personal_detail_link").click(function(){
	location.reload(true);
});

$(".academic_detail_link").click(function(){
	//alert("academic clicked");
	$('#myProfileDiv').html("academic_detail_link");
});

$(".career_detail_link").click(function(){
	//alert("academic clicked");
	$('#myProfileDiv').html("career_detail_link");
});

</script>
