<div class="ui-widget-content ui-corner-all"><center><H3>Co-Curricular Activities</H3></center></div>
<div id="cci_details">
	
	<table style="width: 100%" id="corner" cellspacing="10" cellpadding="10">
			<tr>
				<th>Achievements</th>
				<th>Activities</th>
				<th>Hobbies</th>
							</tr>
            <?php 
        	foreach ($this->test as $test => $array) 
        		{
        			
        				echo '<tr>';
        				echo '<td>'.ucfirst($array['achievements']).'</td>';
        	      		echo '<td>'.ucfirst($array['activities']).'</td>';
        	        	echo '<td>'.ucfirst($array['hobbies']).'</td>';
        	        	
        	            echo '</tr>';
        			
        		}  
            ?>
            
       	</table>
    	</div>
    
<div id="edit_cci" class="ui-widget-content ui-corner-all">
	<h3><center><a href="/student/editcocurricularinfo">Edit</a></center></h3>
</div>
<style type="text/css">
	table {
      	border-color: #c20f2e;
		width:97%;
	}
	tr{
		border-bottom:1px dashed #999;
	}
	#corner
	{
		font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
		font-size: 14px;
		margin: 15px;
		text-align: left;
		border-collapse: collapse;
	}
</style>