<div id="ctrlHolder">
	  <H3>Basic Skills</H3></div>
	  <div>
    	<table style="width: 100%" id="corner" cellspacing="10" cellpadding="10">
			<tr>
				<th>Name</th>
				<th>Proficiency</th>
				<th>Field</th>
			</tr>
            <?php 
        	foreach ($this->skills as $skillId => $value)
        		{
        			echo '<tr>';
        	        echo '<td>'.ucfirst($value['skill_name']).'</td>';
        	        echo '<td>'.ucfirst($value['skill_prof']).'</td>';
        	        echo '<td>'.ucfirst($value['skill_field']).'</td>';
        	        echo '</tr>'; 
        		}  
            ?>
        	
    	</table>
	</div>
    
    <div id="ctrlHolder"><H3>Certification Details</H3></div>
    <div>
    	<table style="width: 100%" id="corner" cellspacing="10" cellpadding="10">
			<tr>
				<th>Name</th>
				<th>Technical Field</th>
				<th>Technical Sector</th>
				<th>From</th>
				<th>To</th>
			</tr>
            <?php 
        	foreach ($this->certification as $id => $value) 
        		{
        			echo '<tr>';
        	        echo '<td>'.ucfirst($value['certification_name']).'</td>';
        	        echo '<td>'.ucfirst($value['technical_field_name']).'</td>';
        	        echo '<td>'.ucfirst($value['technical_sector']).'</td>';
        	        echo '<td>'.ucfirst($value['certification_start_date']).'</td>';
        	        echo '<td>'.ucfirst($value['certification_complete_date']).'</td>';
        	        echo '</tr>'; 
        			 
        		}  
            ?>
        	
    	</table>
	</div>
    
    <div id="ctrlHolder"><H3>Training/Internship</H3></div>
    <div>
    	<table style="width: 100%" id="corner" cellspacing="10" cellpadding="10">
			<tr>
				<th>Technology</th>
				<th>Technical Field</th>
				<th>Technical Sector</th>
				<th>Institution</th>
				<th>Semester</th>
				<th>From</th>
				<th>To</th>
			</tr>
            <?php 
        	foreach ($this->training as $id => $value) 
        		{
        			echo '<tr>';
        	        echo '<td>'.ucfirst($value['training_technology']).'</td>';
        	        echo '<td>'.ucfirst($value['training_field']).'</td>';
        	        echo '<td>'.ucfirst($value['training_sector']).'</td>';
        	        echo '<td>'.ucfirst($value['training_inst']).'</td>';
        	        echo '<td>'.ucfirst($value['training_sem']).'</td>';
        	        echo '<td>'.ucfirst($value['training_start']).'</td>';
        	        echo '<td>'.ucfirst($value['training_end']).'</td>';
        	        echo '</tr>'; 
        			 
        		}  
            ?>
    	</table>
    </div>
    
 <div id="ctrlHolder"> <H3>Work Experience</H3></div>
 <div>
    	<table style="width: 100%" id="corner" cellspacing="10" cellpadding="10">
			<tr>
				<th>Industry</th>
				<th>Functional Area</th>
				<th>Role</th>
				<th>Experience(in months)</th>
				<th>Organisation</th>
				<th>From</th>
				<th>To</th>
				<th>To</th>
				<th>Part-time</th>
			</tr>
            <?php 
        	foreach ($this->experience as $id => $value) 
        		{
        			echo '<tr>';
        	        echo '<td>'.ucfirst($value['industry_name']).'</td>';
        	        echo '<td>'.ucfirst($value['functional_area']).'</td>';
        	        echo '<td>'.ucfirst($value['role']).'</td>';
        	        echo '<td>'.ucfirst($value['experience_months']).'</td>';
        	        echo '<td>'.ucfirst($value['experience_organisation']).'</td>';
        	        echo '<td>'.ucfirst($value['start_date']).'</td>';
        	        echo '<td>'.ucfirst($value['end_date']).'</td>';
        	        echo '<td>'.ucfirst($value['was_part_time']).'</td>';
        	        echo '</tr>'; 
        			 
        		}  
            ?>
    	</table>
    	</div>
    	<div id="ctrlHolder"><H3>Languages Known</H3></div>
    	<div>
    	<table style="width: 100%" id="corner" cellspacing="10" cellpadding="10">
			<tr>
				<th>Name</th>
				<th>Proficiency</th>
			</tr>
            <?php 
        	foreach ($this->language as $skillId => $value) 
        		{
        			echo '<tr>';
        	        echo '<td>'.ucfirst($value['lang_name']).'</td>';
        	        echo '<td>'.ucfirst($value['lang_prof']).'</td>';
        	        
        	        echo '</tr>'; 
        			 
        		}  
            ?>
        	
    	</table>
	</div>
	<!--<div id="ctrlHolder">
	<H3>Emplaoyability Test</H3>
	<table style="width: 100%" id="corner" cellspacing="10" cellpadding="10">
			<tr>
				<th>Registration Number</th>
				<th>Test Name</th>
				<th>Total Marks</th>
				<th>Percentile</th>
			</tr>
            <?php 
        	foreach ($this->test as $test => $array) 
        		{
        			
        				echo '<tr>';
        				echo '<td>'.ucfirst($array['test_reg_no']).'</td>';
        	      		echo '<td>'.ucfirst($array['test_name']).'</td>';
        	        	echo '<td>'.ucfirst($array['test_marks']).'</td>';
        	        	echo '<td>'.ucfirst($array['test_percentile']).'</td>';
        	            echo '</tr>';
        			
        		}  
            ?>
            
       	</table>
    	</div>
    
</div>
-->
<style type="text/css">
	#personal_details label {
		padding: 0.1em;
	}

	span {
		color: #444444;
		font-weight: normal;
	}
	 #ctrlHolder{
		padding: 1em; 
		border-bottom: 1px solid #efefef;
		background: #efefef;
		height: 20px;
		padding-top: .6em;
		border-radius:         4px;
        -webkit-border-radius: 4px;
        -moz-border-radius:    4px;
        -o-border-radius:      4px;
        -khtml-border-radius:  4px; 
      }
      
      table {
      	border-color: #c20f2e;
}
#corner
{
	font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
	font-size: 12px;
	margin: 15px;
	width: 1000px;
	text-align: left;
	border-collapse: collapse;
}

</style>