   
    <!--[if lte ie 7]>
      <style type="text/css" media="screen">
        /* Move these to your IE6/7 specific stylesheet if possible */
        .uniForm, .uniForm fieldset, .uniForm .ctrlHolder, .uniForm .formHint, .uniForm .buttonHolder, .uniForm .ctrlHolder ul{ zoom:1; }
      </style>
    <![endif]-->
<div id="progressbar"></div>

    <form action="javascript:submit();" class="uniForm">
        <h2><?php $stepNo = 0;
        echo 'Step '.($stepNo+1).'/'.count($this->steps).': '.ucfirst($this->steps[$stepNo]);?> Information:</h2>
        <hr/>
        <fieldset>
         <h3>Personnel Information</h3>
        <div class="ctrlHolder noLabel">
          <ul class="alternate">
            <li><label for="first_name"><em>*</em> First Name</label>
          <input name="first_name" id="first_name" data-default-value="e.g. Ravi" value="<?php echo $this->company->first_name ?>" size="10" maxlength="50" type="text" class="textInput required validateAlpha"/></li>
            <li><label for="middle_name"> Middle Name</label>
          <input name="middle_name" id="middle_name" data-default-value="e.g. Kumar" value="<?php echo $this->company->middle_name ?>"  size="10" maxlength="50" type="text" class="textInput validateAlpha"/></li>
            <li><label for="last_name"> Last Name</label>
          <input name="last_name" id="last_name" data-default-value="e.g. Gupta" value="<?php echo $this->company->last_name ?>"  size="10" maxlength="50" type="text" class="textInput validateAlpha"/></li>
          </ul>
          <p class="formHint">Full Name of candidate</p>
        </div>
        <div class="ctrlHolder">
          <label for="personnel_designation" >Personnel's designation</label>
          <input name="personnel_designation" id="personnel_designation" value="<?php echo $this->company->personnel_designation ?>" data-default-value="e.g. HR" size="35" maxlength="50" type="text" class="textInput"/>
          <p class="formHint">personnel's designation</p>
        </div>
        </fieldset>
        <fieldset>
	        <h3>Contact Information</h3>
	        <div class="ctrlHolder">
          <label for="">Email address</label>
          <input name="e_mail" id="e_mail" value="<?php echo $this->company->e_mail ?>" data-default-value="e.g. ravigupta@gmail.com"  size="35" maxlength="50" type="text" class="textInput validateEmail"/>
          <p class="formHint">A valid email address</p>
        </div>
      
        <div class="ctrlHolder">
          <label for="e_mail_confirm">Email confirm</label>
          <input name="e_mail_confirm" id="e_mail_confirm" data-default-value="i.e. same as above" value="<?php echo $this->company->e_mail ?>"  size="35" maxlength="50" type="text" class="textInput validateSameAs e_mail"/>
          <p class="formHint"></p>
        </div>
        
        <div class="ctrlHolder">
          <label for="mobile_no">Mobile No.</label>
          <input name="lmobile_no" id="mobile_no" value="<?php echo $this->company->mobile_no ?>"  data-default-value="e.g. 097226544331" size="35" maxlength="12" type="text" class="textInput validateInteger"/>
          <p class="formHint">Mobile number</p>
        </div>
        <div class="ctrlHolder">
          <label for="landline_no"> Landline No.</label>
          <input name="landline_no" id="landline_no" value="<?php echo $this->company->landline_no ?>"  data-default-value="e.g. 017226544331" size="35" maxlength="12" type="text" class="textInput validateInteger"/>
          <p class="formHint">Landline number</p>
        </div>
        
        <div class="ctrlHolder">
          <label for="fax_no">Fax No.</label>
          <input name="fax_no" id="fax_no" value="<?php echo $this->company->fax_no ?>"  data-default-value="e.g. 017226544331" size="35" maxlength="12" type="text" class="textInput validateInteger"/>
          <p class="formHint">Fax number</p>
        </div>
        
        
        
        </fieldset>
        <div id="submitStatus" style="display:none;padding: 1em;" class="ui-state-highlight ui-corner-all" ></div>
        
        <div class="buttonHolder">
        	<button type="submit" class="secondaryAction">Cancel and go back</button>
        	<button type="submit" class="primaryAction">Next</button>
    	</div>

    </form>
	<script>
	var urlBasicInfo = "<?php 
	echo $this->url(array('controller' => 'company', 'action' => 'save'))?>";
      $(function(){
        $('form.uniForm').uniform({
          prevent_submit : true
        });

        serverDateObj = $.datepicker.parseDate('dd-mm-yy', $('#datetext').text());
        $("#dob").datepicker({
        	dateFormat: 'yy-mm-dd',
        	changeMonth: true,
			changeYear: true,
			yearRange: '-25:-15',
			onClose : function(dateText, inst) {
				this.focus();
				}
        });

        $('#first_name').change(function(){
            var cName = this.value;
        	$('.cName').text(cName);
        });
        $(function() {
    		$( "#progressbar" ).progressbar({
    			value: <?php echo (100/count($this->steps))*($stepNo+1); ?>
    		});
    	});
      });

      function submit() {
          $.ajax({
              url : urlBasicInfo,
              data : getValues(),
              success: function(jStatus){
                  $( "#submitStatus" ).html(jStatus).slideDown('slow', function(){
                    	setTimeout(function(){
                    		window.location = "/company/<?php echo $this->steps[$stepNo+1]?>";
                        	},10000);
                    }).append('<br/><a href="/company/<?php echo $this->steps[$stepNo+1];?>" >NEXT&gt;&gt;</a>');
              },
                  error: function(response) {
                	  $('#errorBox').text(response.responseText).parent().show();
                      console.log(response);
                      }
                  });
      }

        function getValues() {
            var formData = {}; 
            $('form.uniForm :input')
            		.not('button,#e_mail_confirm,:input[value^="e.g."]')
            		.each(function(){ 
            			formData[this.name] = this.value; 
                });
        var gender = $('input:radio[name=gender]:checked').val();
        formData.gender = gender; 
  		return formData;
  	}
    </script>
<?php
$this->headScript()->appendFile('http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
    
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/smooth.uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/demos/css/demo.css');
?>