   
    <!--[if lte ie 7]>
      <style type="text/css" media="screen">
        /* Move these to your IE6/7 specific stylesheet if possible */
        .uniForm, .uniForm fieldset, .uniForm .ctrlHolder, .uniForm .formHint, .uniForm .buttonHolder, .uniForm .ctrlHolder ul{ zoom:1; }
      </style>
    <![endif]-->
<div id="progressbar"></div>

<form action="javascript:submit();" class="uniForm">
<h2><?php
$stepNo = $this->stepNo;
echo 'Step '.($stepNo+1).'/'.count($this->steps).': '.ucfirst($this->steps[$stepNo]);?> Information:</h2>
<hr />
         <fieldset>
         <h3>Basic Skills</h3>
         <div class="ctrlHolder">
          <label for="skills"><em>*</em>Feild</label>
          <input name="skill" id="skill" value="" data-default-value="e.g. C, C++" value="<?php echo $this->applicant->skill ?>"  size="35" maxlength="50" type="text"  class="textInput required validateAlpha"/>
          <p class="formHint">Please enter the technical feild you are skilled in</p>
        </div>
        <div class="ctrlHolder">
          <label for="proficiency">Proficiency</label>
          <select id="proficiency" name="proficiency" class="selectInput">
          		<option value="EXPERT" <?php echo ($this->applicant->proficiency)?'selected="selected"':'';?> >Expert</option>
          		<option value="INTERMEDIATE" <?php echo ($this->applicant->proficiency)?'selected="selected"':'';?> >Intermediate</option>
          		<option value="BASIC" <?php echo ($this->applicant->proficiency)?'selected="selected"':'';?> >Beginner</option>
          		
      	  </select>
          <p class="formHint">Select the proficeincy level</span></p>
        </div>
        <div class="ctrlHolder">
          <label for="skills"><em>*</em>Technical Stream</label>
            <input name="tech_stream" id="tech_stream" data-default-value="e.g. Computer programming" value="<?php echo $this->applicant->tech_stream ?>"  size="35" maxlength="50" type="text"  class="textInput required validateAlpha"/>
          <p class="formHint">Please enter the technical feild you are skilled in</p>
        </div>       
        </fieldset>
        
        <fieldset>
        <h3>Professional Certification</h3>
        <div class="ctrlHolder">
            <label for="technical_feild"><em>*</em>Technical Feild</label>
            <select id="technical_feild" name="technical_feild" class="selectInput required">
          		<option value="Networking <?php echo ($this->applicant->technical_feild)?'selected="selected"':'';?>">Networking</option>
          		
      	  </select>
            <p class="formHint">Technical feild in which certification is done </p>
          </div>
          <div class="ctrlHolder">
            <label for=""><em>*</em>Certification Name</label>
            <select id="technical_sector" name="technical_sector" class="selectInput required">
          		<option value="CCNA <?php echo ($this->applicant->technical_sector)?'selected="selected"':'';?>">CCNA</option>
          		<option value="OCP <?php echo ($this->applicant->technical_sector)?'selected="selected"':'';?>">OCP</option>
          		<option value="RHCE <?php echo ($this->applicant->technical_sector)?'selected="selected"':'';?>">RHCE</option>
      	  </select>
      	  <p class="formHint">Select name of Professional certification </p>
           
          </div>
</fieldset>
<fieldset>
<h3>Training</h3>
           <div class="ctrlHolder">
            <label for="technical_feild"><em>*</em>Technical Feild</label>
            <select id="technical_feild" name="technical_feild" class="selectInput required">
          		<option value="Networking <?php echo ($this->applicant->technical_feild)?'selected="selected"':'';?>">Networking</option>
          		
      	  </select>
            <p class="formHint">Technical feild in which training is done </p>
          </div>
          <div class="ctrlHolder">
            <label for=""><em>*</em>Training Technology</label>
            <select id="technical_sector" name="technical_sector" class="selectInput required">
          		<option value="CCNA <?php echo ($this->applicant->technical_sector)?'selected="selected"':'';?>">CCNA</option>
          		<option value="OCP <?php echo ($this->applicant->technical_sector)?'selected="selected"':'';?>">OCP</option>
          		<option value="RHCE <?php echo ($this->applicant->technical_sector)?'selected="selected"':'';?>">RHCE</option>
      	  </select>
           <p class="formHint">Technology in which training is done </p>
          </div>
          </fieldset> 
          
        
 <fieldset>
   <h3>Languages Known</h3>
         <div class="ctrlHolder">
            <label for=""><em>*</em>Languages Known</label>
            <select id="language_id" name="language_id" class="selectInput required">
          		<option value="1" <?php echo (1 == $this->applicant->language_id?'selected="selected"':'');?> >Hindi</option>
          		<option value="2" <?php echo (1 == $this->applicant->language_id?'selected="selected"':'');?>>English</option>
          		<option value="3" <?php echo (1 == $this->applicant->language_id?'selected="selected"':'');?>>Punjabi</option>
          		<option value="4" <?php echo (1 == $this->applicant->language_id?'selected="selected"':'');?>>Foreign</option>
      	  </select>
           <p class="formHint">Languages Known by <span class="cName" >Candidate</span> </p>
          </div>
          
          <div class="ctrlHolder">
            <label for="lang_proficiency"><em>*</em>Proficiency</label>
            <select id="lang_proficiency" name="lang_proficiency" class="selectInput required">
          		<option value="READ <?php echo ($this->applicant->lang_proficiency)?'selected="selected"':'';?>">Read</option>
          		<option value="WRITE <?php echo ($this->applicant->lang_proficiency)?'selected="selected"':'';?>">Write</option>
          		<option value="SPEAK <?php echo ($this->applicant->lang_proficiency)?'selected="selected"':'';?>">Speak</option>
          		<option value="ALL <?php echo ($this->applicant->lang_proficiency)?'selected="selected"':'';?>">All</option>
      	  </select>
            <p class="formHint">Select proficiency</p>
          </div>
  </fieldset>
  <fieldset>
   
          <h3>Prefrences</h3>
        	<div class="ctrlHolder">
            <ul class="blockLabels alternate">
            <li><label for="IT"><input name="IT" type="radio" value="false <?php echo ('IT' == $this->applicant->cast?'selected="selected"':'');?>"   title="No" >IT</label></li>
            <li><label for="core"><input  name="core" type="radio" value="true <?php echo ('CORE' == $this->applicant->cast?'selected="selected"':'');?>"   title="Yes" >Core </label></li>
            <li><label for="defence"><input  name="defence" type="radio" value="true <?php echo ('DEFENCE' == $this->applicant->cast?'selected="selected"':'');?>"   title="Yes" >Defence</label></li>
            <li><label for="government"><input  name="government" type="radio" value="true <?php echo ('GOVT' == $this->applicant->cast?'selected="selected"':'');?>"   title="Yes" >Govt</label></li>
          </ul>
          <p class="formHint">Filter on basis of the job preferred </p>
          </div>
          </fieldset>    
        
        
    
        
        <div id="submitStatus" style="display:none;padding: 1em;" class="ui-state-highlight ui-corner-all" ></div>
        
        <div class="buttonHolder">
        	<button type="submit" class="secondaryAction">Cancel and go back</button>
        	<button type="submit" class="primaryAction">Next</button>
    	</div>

    </form>
	<script>
	var urlBasicInfo = "<?php 
	echo $this->url(array('controller' => 'profile', 'action' => 'save'))?>";
      $(function(){
        $('form.uniForm').uniform({
          prevent_submit : true
        });

        $(function() {
    		$( "#progressbar" ).progressbar({
    			value: <?php echo (100/count($this->steps))*($stepNo+1); ?>
    		});
    	});
      });

      function submit() {
          $.ajax({
              url : urlBasicInfo,
              data : getValues(),
              success: function(jStatus){
                  
              },
                  error: function(response) {
                	  $('#errorBox').text(response.responseText).parent().show();
                      console.log(response);
                      }
                  });
      }

        function getValues() {
            var formData = {}; 
            $('form.uniForm :input')
            		.not('button,#e_mail_confirm,:input[value^="e.g."]')
            		.each(function(){ 
            			formData[this.name] = this.value; 
                });
        var gender = $('input:radio[name=gender]:checked').val();
        formData.gender = gender; 
  		return formData;
  	}
    </script>
<?php
$this->headScript()->appendFile('http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
    
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/smooth.uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/demos/css/demo.css');
?>