<h2>Languages Known:<span id="goback"><a href="<?php echo $this->url(array('controller' => 'student', 'action' => 'profile'))?>">Go back to profile page</a></span></h2>
<form action="javascript:submit();" class="uniForm">
      
    <fieldset>
   
   
         <div class="ctrlHolder">
            <label for="">Languages Known</label>
            <select id="language_id" name="language_id" class="selectInput ">
          		<option value="1">Hindi</option>
          		<option value="2">English</option>
          		<option value="3">Punjabi</option>
          		<option value="4">Foreign</option>
      	  </select>
           <p class="formHint">Languages Known by <span class="cName" >Candidate</span> </p>
          </div>
          
          <div class="ctrlHolder">
            <label for="">Proficiency</label>
            <select id="proficiency" name="proficiency" class="selectInput ">
          		<option value="READ">Read</option>
          		<option value="WRITE">Write</option>
          		<option value="SPEAK">Speak</option>
          		<option value="ALL">All</option>
      	  </select>
            <p class="formHint">Select proficiency</p>
          </div>
          
          
            </fieldset>
             
        <div id="submitStatus" style="display:none;padding: 1em;" class="ui-state-highlight ui-corner-all" ></div>
        
        <div class="buttonHolder">
        	<button type="submit" class="secondaryAction">Cancel and go back</button>
        	<button type="submit" class="primaryAction">Next</button>
    	</div>
    	<br>
      </form>
      
 <script>

$(function(){
  $('form.uniForm').uniform({
    prevent_submit : true
  });

  serverDateObj = $.datepicker.parseDate('dd-mm-yy', $('#datetext').text());
  $("#date").datepicker({
  	dateFormat: 'yy-mm-dd',
  	changeMonth: true,
		changeYear: true,
		yearRange: '-25:-15',
		onClose : function(dateText, inst) {
			this.focus();
		}
  });
});       
 
  

function submit() {
    $.ajax({
        url : urlBasicInfo,
        data : getValues(),
        success: function(jStatus){
            
        },
            error: function(response) {
          	  $('#errorBox').text(response.responseText).parent().show();
                console.log(response);
                }
            });
}

  function getValues() {
      var formData = {}; 
      $('form.uniForm :input')
      		.not('button,#e_mail_confirm,:input[value^="e.g."]')
      		.each(function(){ 
      			formData[this.name] = this.value; 
          });
  
	return formData;
}
</script>
<style>
	.uniForm{
		background-color:white;
		padding:10px 10px 10px 25px;
		border:1px solid #b4c1da;
		margin:-5px 0 40px 0;
		box-shadow:#e4e4e4 0px 0px 1px 1px; 
	}
	h2,h3{
		padding:3px 3px 3px 10px;
		background-color:#eceff4;
		border:1px solid #b4c1da;
		width:57%;
		font-size:17px;
		font-weight:100;
	}
	#goback a{
		float:right;
		color:red;
		font-size:14px;
		text-decoration: none;
	}
</style>
<?php
$this->headScript()->appendFile('http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
    
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/smooth.uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/demos/css/demo.css');
?>
  