<?php 
	$test_names = $this->test_names;
?>

<h2>Professional Certification<span id="goback"><a href="<?php echo $this->url(array('controller' => 'student', 'action' => 'profile'))?>">Go back to profile page</a></span></h2>
<form action="javascript:submit();" class="uniForm">
	
	<fieldset id="technical_info">
		<div class="ctrlHolder">
			<label for="technical_field_name">Technical Field</label>
			<select id="technical_field_name" name="technical_field_name" class="selectInput required">
            	<?php 
            		foreach ($test_names as $key => $value)
            		{
            			echo '<option value="'.$key.'">'.$value.'</option>';
            		}
            	?>
            	<option value="other">Other</option>
			</select>
            <p class="formHint">Technical feild in which certification is done </p>
		</div>
	</fieldset>
	    
	<fieldset id="certification_info">
		<div class="ctrlHolder">
			<label for="certification_name"><em class="red">*</em>Certification Name</label>
			<input name="certification_name" id="certification_name" value="" data-default-value="e.g. OCJP" size="35" maxlength="50" type="text" class="textInput "/>
			<p class="formHint">Name of the Certification.</p>
		</div>
	 </fieldset>
	 
	 <fieldset id="certification_detail">   
		<div class="ctrlHolder">
			<label for="start_date">Start Date</label>
			<input name="start_date" id="start_date" data-default-value="2011-04-04" value=""  size="35" maxlength="50" type="text" readonly="readonly" class="textInput required"/>
			<p class="formHint">1. Select year <br/>2. Select Month<br/>3. Click date of birthday</p>
		</div>
        
        <div class="ctrlHolder">
			<label for="complete_date">Complete Date</label>
			<input name="complete_date" id="complete_date" data-default-value="2011-04-04" value=""  size="35" maxlength="50" type="text" readonly="readonly" class="textInput required"/>
			<p class="formHint">1. Select year <br/>2. Select Month<br/>3. Click date of birthday</p>
		</div>  
	</fieldset>
    
	<div id="submitStatus" style="display:none;padding: 1em;" class="ui-state-highlight ui-corner-all" ></div>
	<div class="buttonHolder">
		<button type="submit" class="secondaryAction">Cancel and go back</button>
		<button type="submit" class="primaryAction">Next</button>
	</div>
	
	<br>
</form>

<script>

$(function(){
	$('form.uniForm').uniform({
		prevent_submit : true
	});

	serverDateObj = $.datepicker.parseDate('dd-mm-yy', $('#datetext').text());
	$("#start_date").datepicker({
		dateFormat: 'yy-mm-dd',
		changeMonth: true,
		changeYear: true,
		yearRange: '-25:-15',
		onClose : function(dateText, inst) {
			this.focus();
		}
	});
	$("#complete_date").datepicker({
		dateFormat: 'yy-mm-dd',
		changeMonth: true,
		changeYear: true,
		yearRange: '-25:-15',
		onClose : function(dateText, inst) {
			this.focus();
		}
	});
});       

var div_html = '<div class="ctrlHolder" id="other_field"><label for="other_technical_field_name"><em class="red">*</em>Techical Field Name</label><input name="other_technical_field_name" id="other_technical_field_name" value="" data-default-value="" size="35" maxlength="50" type="text" class="required textInput"/><p class="formHint">Select the name of the field</p></div>'+
				'<div class="ctrlHolder" id="other_sector"><label for="technical_sector"><em class="red">*</em>Sector Name</label><input name="technical_sector" id="technical_sector" value="" data-default-value="Technical Sector" size="35" maxlength="50" type="text" class="required textInput"/><p class="formHint">Sector of the certification</p></div>';
$('#technical_field_name').change(function(){
	if($('#technical_field_name').val() == 'other'){
		$('fieldset#technical_info').append(div_html);
	}
	else {
		$('div#other_field').remove();
		$('div#other_sector').remove();
	}
});

function submit() {
	var urlSaveInfo = '<?php echo $this->url(array('controller' => 'student', 'action' => 'savecertification'))?>';
    $.ajax({
        url : urlSaveInfo,
        data : {myarray:getValues()},
        success: function(jStatus){
            
        },
            error: function(response) {
          	  $('#errorBox').text(response.responseText).parent().show();
                console.log(response);
                }
            });
}

function getValues() {
	var technical_info = {};
	var certification_info = {};
	var certification_detail = {};
	var formData = {};

	if($('#technical_field_name').val() == 'other') {
		technical_info['technical_field_name'] =  $('#other_technical_field_name').val();
		technical_info['technical_sector'] =  $('#technical_sector').val();
	}
	else {
		technical_info['technical_field_id'] =  $('#technical_field_name').val();
	}
	$('fieldset#certification_info :input')
		.each(function(){ 
		certification_info[this.name] = this.value; 
	});
	$('fieldset#certification_detail :input')
		.each(function(){ 
		certification_detail[this.name] = this.value; 
	});

	formData['technical_info'] = technical_info;
	formData['certification_info'] = certification_info;
	formData['certification_detail'] = certification_detail;
	return formData;
}
</script>
<style>
	.uniForm{
		background-color:white;
		padding:10px 10px 10px 25px;
		border:1px solid #b4c1da;
		margin:-5px 0 40px 0;
		box-shadow:#e4e4e4 0px 0px 1px 1px; 
	}
	h2,h3{
		padding:3px 3px 3px 10px;
		background-color:#eceff4;
		border:1px solid #b4c1da;
		width:57%;
		font-size:17px;
		font-weight:100;
	}
	#goback a{
		float:right;
		color:red;
		font-size:14px;
		text-decoration: none;
	}
</style>
<?php
$this->headScript()->appendFile('http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
    
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/smooth.uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/demos/css/demo.css');
?>
 