<?php 
	$industries = $this->industries;
	$roles = $this->roles;
	$functional_areas = $this->functional_areas;
?>

<h2>Experience<span id="goback"><a href="<?php echo $this->url(array('controller' => 'student', 'action' => 'profile'))?>">Go back to profile page</a></span></h2>
<form action="javascript:submit();" class="uniForm">
      
<fieldset id="experience_info">
	<div class="ctrlHolder" id="industry_div">
		<label for="industry_name">Industry</label>
		<select id="industry_name" name="industry_name" class="selectInput" onchange="javascript:show_industry_div()">
				<?php 
					foreach ($industries as $key => $value)
            		{
            			echo '<option value="'.$key.'">'.$value.'</option>';
            		}
          		?>
          		<option value="other">Other</option>
		</select>
		<p class="formHint">Name of the industry</p>
	</div>
	
	<div class="ctrlHolder" id="functional_area_div">
		<label for="functional_area_name">Functional Area</label>
		<select id="functional_area_name" name="functional_area_name" class="selectInput" onchange="javascript:show_fa_div()">
				<option value="av">Oer</option>
				<?php 
					foreach ($functional_areas as $key => $value)
            		{
            			echo '<option value="'.$key.'">'.$value.'</option>';
            		}
          		?>
          		<option value="other">Other</option>
		</select>
		<p class="formHint">Name of the industry</p>
	</div>
	
	<div class="ctrlHolder" id="role_name_div">
		<label for="role_name">Role</label>
		<select id="role_name" name="role_name" class="selectInput" onchange="javascript:show_role_div()">
				<option value="av">Oer</option>
				<?php 
					foreach ($roles as $key => $value)
            		{
            			echo '<option value="'.$key.'">'.$value.'</option>';
            		}
          		?>
          		<option value="other">Other</option>
		</select>
		<p class="formHint">Name of the industry</p>
	</div>
</fieldset>

<fieldset id="student_experience">
	<div class="ctrlHolder">
		<label for="start_date">Start Date</label>
		<input name="start_date" id="start_date" data-default-value="2011-04-04" value=""  size="35" maxlength="50" type="text" readonly="readonly" class="textInput "/>
		<p class="formHint">1. Select year <br/>2. Select Month<br/>3. Click date of birthday</p>
	</div>
		
    <div class="ctrlHolder">
		<label for="end_date">End Date</label>
		<input name="end_date" id="end_date" data-default-value="2011-04-04" value=""  size="35" maxlength="50" type="text" readonly="readonly" class="textInput "/>
		<p class="formHint">1. Select year <br/>2. Select Month<br/>3. Click date of birthday</p>
	</div>
		
	<div class="ctrlHolder">
		<label for="organisation">Organisation Name</label>
		<input name="organisation" id="organisation" value="" data-default-value="e.g. Infosys India Limited" size="35" maxlength="50" type="text" class="textInput required"/>
	</div>
	
	<div class="ctrlHolder">
		<label for="experience_years">Experience (Years)</label>
		<input name="experience_years" id="experience_years" value="" data-default-value="e.g. 2" size="35" maxlength="50" type="text" class="textInput validateInteger required"/>
		<p class="formHint">Exeprience in number of years</p>
	</div>	 
	
	<div class="ctrlHolder">
		<label for="experience_months">Experience (Months)</label>
		<input name="experience_months" id="experience_months" value="" data-default-value="e.g. 10" size="35" maxlength="50" type="text" class="textInput validateInteger required"/>
		<p class="formHint">Exeprience in number of months</p>
	</div>
</fieldset>

<div id="submitStatus" style="display:none;padding: 1em;" class="ui-state-highlight ui-corner-all" ></div>
	<div class="buttonHolder">
		<button type="submit" class="secondaryAction">Cancel and go back</button>
		<button type="submit" class="primaryAction">Next</button>
	</div>
             
</form>
      
<script>

$(function(){
  $('form.uniForm').uniform({
    prevent_submit : true
  });

  serverDateObj = $.datepicker.parseDate('dd-mm-yy', $('#datetext').text());
  $("#start_date").datepicker({
  	dateFormat: 'yy-mm-dd',
  	changeMonth: true,
		changeYear: true,
		yearRange: '-25:-15',
		onClose : function(dateText, inst) {
			this.focus();
		}
  });

  $("#end_date").datepicker({
	  	dateFormat: 'yy-mm-dd',
	  	changeMonth: true,
			changeYear: true,
			yearRange: '-25:-15',
			onClose : function(dateText, inst) {
				this.focus();
			}
	  });
  show_industry_div();
  show_fa_div();
  show_role_div();
});       

function show_industry_div(){
var industry_div_html = '<div class="ctrlHolder" id="new_industry_div">'+
				'<label for="new_industry_name"><em class="red">*</em>Industry Name</label>'+
				'<input name="new_industry_name" id="new_industry_name" value="" data-default-value="" size="35" maxlength="50" type="text" class="required textInput"/>'+
				'<p class="formHint">Enter the name of the industry</p>'+
				'</div>';
//$('#industry_name').change(function(){
	if($('#industry_name').val() == 'other'){
		$('#industry_div').after(industry_div_html);
	}
	else {
		$('div#new_industry_div').remove();
	}
//});
}

function show_fa_div(){
var fa_div_html = '<div class="ctrlHolder" id="new_functional_area_div">'+
				'<label for="new_functional_area_name"><em class="red">*</em>Functional Area Name</label>'+
				'<input name="new_functional_area_name" id="new_functional_area_name" value="" data-default-value="" size="35" maxlength="50" type="text" class="required textInput"/>'+
				'<p class="formHint">Enter the name of the functional area</p>'+
				'</div>';
//$('#functional_area_name').change(function(){
	if($('#functional_area_name').val() == 'other'){
		$('#functional_area_div').after(fa_div_html);
	}
	else {
		$('div#new_functional_area_div').remove();
	}
//});
}

function show_role_div(){
var role_div_html = '<div class="ctrlHolder" id="new_role_div">'+
			'<label for="new_role_name"><em class="red">*</em>Role Name</label>'+
			'<input name="new_role_name" id="new_role_name" value="" data-default-value="" size="35" maxlength="50" type="text" class="required textInput"/>'+
			'<p class="formHint">Enter your role</p>'+
		'</div>';
//$('#role_name').change(function(){
	if($('#role_name').val() == 'other'){
		$('#role_name_div').after(role_div_html);
	}
	else {
		$('div#new_role_div').remove();
	}
//});
}

function submit() {
	var urlSaveInfo = '<?php echo $this->url(array('controller' => 'student', 'action' => 'saveexperience'))?>';
    $.ajax({
        url : urlSaveInfo,
        data : {myarray:getValues()},
        success: function(jStatus){
            
        },
        error: function(response) {
          $('#errorBox').text(response.responseText).parent().show();
             console.log(response);
        }
    });
}

function getValues() {
	var formData = {};
	var experience_info = {};
	var student_experience = {};

	if($('#industry_name').val() == 'other') {
		experience_info['industry_name'] =  $('#new_industry_name').val();
	}
	else {
		student_experience['industry_id'] =  $('#industry_name').val();
	}
	
	if($('#functional_area_name').val() == 'other') {
		experience_info['functional_area_name'] =  $('#new_functional_area_name').val();
	}
	else {
		student_experience['functional_area_id'] =  $('#functional_area_name').val();
	}
	
	if($('#role_name').val() == 'other') {
		experience_info['role_name'] =  $('#new_role_name').val();
	}
	else {
		student_experience['role_id'] =  $('#role_name').val();
	}

	$('fieldset#student_experience :input')
		.each(function(){ 
  			student_experience[this.name] = this.value; 
	});

    formData['experience_info'] = experience_info;
  	formData['student_experience'] = student_experience;
	return formData;
}
</script>
<style>
	.uniForm{
		background-color:white;
		padding:10px 10px 10px 25px;
		border:1px solid #b4c1da;
		margin:-5px 0 40px 0;
		box-shadow:#e4e4e4 0px 0px 1px 1px; 
	}
	h2,h3{
		padding:3px 3px 3px 10px;
		background-color:#eceff4;
		border:1px solid #b4c1da;
		width:57%;
		font-size:17px;
		font-weight:100;
	}
	#goback a{
		float:right;
		color:red;
		font-size:14px;
		text-decoration: none;
	}
</style>
<?php
$this->headScript()->appendFile('http://' . CDN_SERVER . '/plugins/uni-form/js/uni-form-validation.jquery.js');
    
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/css/smooth.uni-form.css');
$this->headLink()->prependStylesheet(
'http://' . CDN_SERVER .  '/plugins/uni-form/demos/css/demo.css');
?>
    