<div class="ui-widget-content ui-corner-all"><center><H3>Training/Internship</H3></center></div>
<div id="training_details">
    	<table style="width: 100%" id="corner" cellspacing="10" cellpadding="10">
			<tr>
				<th>Technology</th>
				<th>Technical Field</th>
				<th>Technical Sector</th>
				<th>Institution</th>
				<th>Semester</th>
				<th>From</th>
				<th>To</th>
			</tr>
            <?php 
        	foreach ($this->training as $id => $value) 
        		{
        			echo '<tr>';
        	        echo '<td>'.ucfirst($value['training_technology']).'</td>';
        	        echo '<td>'.ucfirst($value['training_field']).'</td>';
        	        echo '<td>'.ucfirst($value['training_sector']).'</td>';
        	        echo '<td>'.ucfirst($value['training_inst']).'</td>';
        	        echo '<td>'.ucfirst($value['training_sem']).'</td>';
        	        echo '<td>'.ucfirst($value['training_start']).'</td>';
        	        echo '<td>'.ucfirst($value['training_end']).'</td>';
        	        echo '</tr>'; 
        			 
        		}  
            ?>
    	</table>
    </div>
    <div id="edit_tain" class="ui-widget-content ui-corner-all">
	<h3><center><a href="/student/edittraininginfo">Edit</a></center></h3>
</div>
<style type="text/css">
	table {
      	border-color: #c20f2e;
		width:97%;
	}
	tr{
		border-bottom:1px dashed #999;
	}
	#corner
	{
		font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
		font-size: 14px;
		margin: 15px;
		text-align: left;
		border-collapse: collapse;
	}
</style>