<div class="ui-widget-content ui-corner-all"><center><H3>Certification Details</H3></center></div>
<div id="certification_details">
   
    	<table style="width: 100%" id="corner" cellspacing="10" cellpadding="10">
			<tr>
				<th>Name</th>
				<th>Technical Field</th>
				<th>Technical Sector</th>
				<th>From</th>
				<th>To</th>
			</tr>
            <?php 
        	foreach ($this->certification as $id => $value) 
        		{
        			echo '<tr>';
        	        echo '<td>'.ucfirst($value['certification_name']).'</td>';
        	        echo '<td>'.ucfirst($value['technical_field_name']).'</td>';
        	        echo '<td>'.ucfirst($value['technical_sector']).'</td>';
        	        echo '<td>'.ucfirst($value['certification_start_date']).'</td>';
        	        echo '<td>'.ucfirst($value['certification_complete_date']).'</td>';
        	        echo '</tr>'; 
        			 
        		}  
            ?>
        	
    	</table>
	</div>
	<div id="edit_certification" class="ui-widget-content ui-corner-all">
	<h3><center><a href="/student/editcertificationinfo">Edit</a></center></h3>
</div>
<style type="text/css">
	table {
      	border-color: #c20f2e;
		width:97%;
	}
	tr{
		border-bottom:1px dashed #999;
	}
	#corner
	{
		font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
		font-size: 14px;
		margin: 15px;
		text-align: left;
		border-collapse: collapse;
	}
</style>