<?php 
	$job_preferred = $this->job_preferred;
	
	if(Zend_Auth::getInstance()->hasIdentity()){
		$authInfo = Zend_Auth::getInstance()->getStorage()->read();
		$usertype=$authInfo['userType'];
	}
?>

<div class="ui-state-hover"><center><H3>Job Area Preferred</H3></center></div>
<div id="skill_details">
	<table style="width: 100%" id="corner" cellspacing="10" cellpadding="10">
	<?php 
		if($job_preferred == false)
		{
			echo "<h4>No information has been added yet.</h4>";
		}
		else
		{
			foreach ($this->job_preferred as $skillId => $value)
			{
				echo '<tr>';
				echo '<td>'.ucfirst($value).'</td>';
				echo '</tr>';
			}
		}
	?>
	</table>
</div>

<?php if($usertype == 'STU') {?>
<input type="button" value="Edit" onclick="window.location.replace('/student/editjobpreferred')">
<?php }?>

<script type="text/javascript">
	$(function(){
		$('div#topContent').hide();
	});
</script>

<style type="text/css">
	table {
      	border-color: #c20f2e;
		width:97%;
	}
	tr{
		border-bottom:1px dashed #999;
	}
	#corner
	{
		font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
		font-size: 14px;
		margin: 15px;
		text-align: left;
		border-collapse: collapse;
	}
</style>