<?php 
	$job_preferred = $this->job_preferred;
	
	if(Zend_Auth::getInstance()->hasIdentity()){
		$authInfo = Zend_Auth::getInstance()->getStorage()->read();
		$usertype=$authInfo['userType'];
	}
?>

<div class="ui-state-hover"><center><H3>Job Area Preferred</H3></center></div>
<div id="skill_details">
	<?php 
		if($job_preferred == false)
		{
			echo "<h4>No information has been added yet.</h4>";
		}
		else
		{
            echo '<table id="corner" cellspacing="10" cellpadding="10">';
				echo '<tr>';
				echo '<td>'.ucfirst($job_preferred).'</td>';
				echo '</tr>';
			echo '</table>';
			
        	if($usertype == 'STU'){
                echo '<input type="button" class="ui-button" value="Edit Information" onclick="window.location.replace('."'".'/student/editcocurricular'."'".');">';
            }
		}
	?>
</div>

<script type="text/javascript">
	$(function(){
		$('div#topContent').hide();
	});
</script>

<style type="text/css">
	table {
      	border-color: #c20f2e;
		width:97%;
	}
	tr{
		border-bottom:1px dashed #999;
	}
	#corner
	{
		font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
		font-size: 14px;
		margin: 15px;
		text-align: left;
		border-collapse: collapse;
	}
</style>