<?php
	$certification = $this->certification;
?>

<div class="ui-widget-content ui-corner-all"><center><H3>Certification Details</H3></center></div>
<div id="certification_details">
	<table style="width: 100%" id="corner" cellspacing="10" cellpadding="10">
	<?php
		foreach ($certification as $key => $value) 
		{
        	echo '<tr>';
        		echo '<td><span id="heading">'.ucfirst(str_replace('_',' ',$key)).'</span>';
        		echo '<span id="content">'.$value.'</span></td>';
        	echo '</tr>';
		}
	?>
	</table>
</div>

<div id="edit_certification" class="ui-widget-content ui-corner-all">
	<h3><center><a href="/student/profile">Go Back</a></center></h3>
</div>
<style type="text/css">
	table {
      	border-color: #c20f2e;
		width:97%;
	}
	tr{
		border-bottom:1px dashed #999;
	}
	#corner
	{
		font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
		font-size: 14px;
		margin: 15px;
		text-align: left;
		border-collapse: collapse;
	}
	td span#heading{
		color:red;
		font-size:16px;
	}
	td span#content{
		float:right;
		font-size:16px;
	}
</style>