<?php 
	$cocurricular = $this->co_curicular_info;
	
	if(Zend_Auth::getInstance()->hasIdentity()){
		$authInfo = Zend_Auth::getInstance()->getStorage()->read();
		$usertype=$authInfo['userType'];
	}
?>

<div class="ui-state-hover"><center><H3>Cocurricular Details</H3></center></div>
<div id="certification_details">
	<?php
		if($cocurricular == false)
		{
			echo "<h4>No information has been added yet.</h4>";
		}
		else
        {
            echo '<table id="corner" cellspacing="10" cellpadding="10">';
			foreach ($cocurricular as $key => $value) 
			{
	        	echo '<tr>';
	        		echo '<td><span id="heading">'.ucfirst(str_replace('_',' ',$key)).'</span><br>';
	        		$array = explode("\n",$value);
	        		echo '<ul style="list-style:none;">';
	        		foreach ($array as $key => $content )
	        		{
	        			echo '<li><span id="content">'.$content.'</span></li>';
	        		}
	        		echo '</td>';
	        	echo '</tr>';
			}
    		echo '</table>';
        	if($usertype == 'STU'){
                echo '<input type="button" class="ui-button" value="Edit Information" onclick="window.location.replace('."'".'/student/editcocurricular'."'".');">';
            }
        }
	?>
</div>

<script type="text/javascript">
	$(function(){
		$('div#topContent').hide();
	});
</script>

<style type="text/css">
	table {
      	border-color: #c20f2e;
		width:97%;
	}
	tr{
		border-bottom:1px dashed #999;
	}
	#corner
	{
		font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
		font-size: 14px;
		margin: 15px;
		text-align: left;
		border-collapse: collapse;
	}
	td span#heading{
		color:red;
		font-size:16px;
	}
	td span#content{
		float:left;
		font-size:16px;
	}
</style>