<div style="padding :2em 0 2em 0; text-align: center; " >
<form >Select date: <input type="text"
	id="datepicker1" readonly="readonly"
	class="ui-widget-content  ui-corner-all" style="text-align: center"></input> <span style="color: gray; " >(i.e. period date)</span>
</form>
</div>


<table id="tblgrid" class="scroll"></table>
<div id="gridpager" class="scroll" style="text-align: center;"></div>
<br/>
<table id="detailGrid" class="scroll"></table>
<script type="text/javascript">

var session_startdate = '<?php echo $this->session_startdate;?>';  
var urlAttOverviewData = "<?php echo $this->url(array('controller' => 'studentattendance', 'action' => 'getoverviewdata'))?>";
var urlAttDetailData = "<?php echo $this->url(array('controller' => 'studentattendance', 'action' => 'getdetaildata'))?>";

var gridTable = "#tblgrid";
var detailGrid = "#detailGrid";
var gridPager = "#gridpager"; 

serverDateObj = $.datepicker.parseDate('dd-mm-yy', $('#datetext').text());
//TODO session_startdate is different because its date from db server.
sessionStartdateObj= $.datepicker.parseDate('yy-mm-dd', session_startdate);
var selectedDate = null;
/* utility functions */
$("#datepicker1").datepicker({
	minDate : sessionStartdateObj,
	maxDate : serverDateObj,
	dateFormat: 'dd-mm-yy', 
	closeText: 'Close', 
	showButtonPanel: true,
	constrainInput : true,
	gotoCurrent: true,
	onSelect :function(attendanceDate, inst) {
		selectedDate= attendanceDate;
		$(gridTable).jqGrid('setGridParam',
				{postData:{
					'attendance_date':attendanceDate
					},
     			 url: urlAttOverviewData,
      			datatype: 'json'
                })
                .trigger('reloadGrid');
		$('#gbox_tblgrid').show();
	    $('#gbox_detailGrid').hide();
	}
});
$(function(){
$(gridTable).jqGrid({
	datatype:'local',
	colNames:['Department','Total Periods','Attendance Marked','Last activity date'],
	colModel:[
		{name:'department_id',
			index:'department_id',
			align: 'center'},
        {name:'total',
			index:'total',
			align: 'center',
			formatter:'number', 
			formatoptions:{decimalPlaces: 0}},
        {name:'marked',
			index:'marked',
			align: 'center',
			formatter:'number', 
			formatoptions:{decimalPlaces: 0}},
        {name:'last_marked',
			index:'last_marked',
			align: 'center',
			formatter:'date'}
    ],
    onSelectRow: fetchAttendanceDetail,
    loadComplete : function() {$('#gbox_detailGrid').hide();},
    altRows: true,
    loadonce : true,
    shrinkToFit : true,
    forceFit : true,
    prmNames: {page: null, rows: null, sort: null, order: null, search: null, nd: null},
    caption: "Department-wise Overview of Attendance"
	}).jqGrid('gridResize');

$(detailGrid).jqGrid({
	datatype:'local',
	colNames:['Faculty ID','Marked Date','Program','Class','Periods','Subject','Mode','Group'],
	colModel:[
		{name:'staff_id',
			index:'staff_id',
			align: 'center'},
        {name:'marked_date',
			index:'marked_date',
			align: 'center',
			formatter:'date'},
        {name:'degree_id',
			index:'degree_id',
			align: 'center'},
        {name:'semester_id',
			index:'semester_id',
			align: 'center',
			formatter:'number', 
			formatoptions:{decimalPlaces: 0}},
		{name:'periods_covered',
			index:'periods_covered',
			align: 'center'},
        {name:'subject_code',
			index:'subject_code',
			align: 'center'},
        {name:'subject_mode_id',
			index:'subject_mode_id',
			align: 'center'},
        {name:'group_id',
			index:'group_id',
			align: 'center'}
    ],
    altRows: true,
    loadonce : true,
    shrinkToFit : true,
    forceFit : true,
    hoverrows : false,
    rowNum: 50,
    prmNames: {page: null, rows: null, sort: null, order: null, search: null, nd: null},
    caption: "Attendance Detail"
	}).jqGrid('gridResize');

$('#gbox_tblgrid').hide();
$('#gbox_detailGrid').hide();
});

function fetchAttendanceDetail(department){

	$(detailGrid).jqGrid('setGridParam',
			{postData:{
				'attendance_date':selectedDate,
				'department_id':department
				},
 			 url: urlAttDetailData,
  			datatype: 'json'
            })
            .trigger('reloadGrid');
    $('#gbox_detailGrid').show();
}
</script>