<style>
.holiday {
	background-color: maroon;
	color: red;
	text-decoration: line-through;
}

.checkGroup {
	font-family: "Courier New", Courier, monospace;
	background-color: #3399FF;
	color: blue;
}

.adjustment {
	color: blue;
}

.adjusted {
	background-color: #CCC;
}

.nonattendanceday {
	background-color: maroon;
}

.aligncenter {
	width: 50%;
	margin-left: auto;
	margin-right: auto;
	text-align: center;
}

#markattendance label {
	padding: 0.1em;
}
</style>
<div id="markattendanceDiv" class="ui-state-highlight ui-corner-all"  style="padding :1em 0 0 0; text-align: center; " >
<form id="markattendance" class="ui-corner-all"  action="javascript:submit(this);"  >

			<label><select id="department_id" name="department_id">
			<option value="-1" >Department</option>
			<option value="APPSC" >Applied Science</option>
			<option value="BT" >Biotech</option>
			<option value="CSE" >Computer</option>
			<option value="ECE" >Electronics</option>
			<option value="ME" >Mechanical</option>
			</select></label>
			<label><select id="programme_id" name="programme_id" disabled="disabled" >
			<option value="-1" >Programme</option>
			</select></label>
			<label><select id="semester_id" name="semester_id" disabled="disabled" >
    			<option value="-1" >Semester</option>
			</select></label>
			
    		<label><input type="text" id="period_date" readonly="readonly" value="<?php
$date = new Zend_Date();
echo $date->get(Zend_Date::DATE_MEDIUM)?>" class="ui-widget-content ui-corner-all" style="text-align: center"></input></label>
    		<label><select id="period_number" name="period_number">
			<option value="-1" >Period Number</option>
    			<option value="1" >1</option>
    			<option value="2" >2</option>
    			<option value="3" >3</option>
    			<option value="4" >4</option>
    			<option value="5" >5</option>
    			<option value="6" >6</option>
    			<option value="7" >7</option>
    			<option value="8" >8</option>
			</select></label>
			<label><select id="duration" name="duration">
    			<option value="-1" >Duration</option>
    			<option value="1" >1</option>
    			<option value="2" >2</option>
    			<option value="3" >3</option>
    			<option value="4" >4</option>
    			<option value="5" >5</option>
    			<option value="6" >6</option>
    			<option value="7" >7</option>
    			<option value="8" >8</option>
    			</select></label>
    			
			
    		<label><select id="subject_code" name="subject_code">
			<option value="-1" >Subject Code</option>
			</select></label>
			<label><select id="subject_mode_id" name="subject_mode_id">
			<option value="-1" >Subject Mode</option>
			</select></label>
			<label><select id="group_id" name="group_id">
			<option value="-1" >Group</option>
			</select></label>
			<label title="Period Type" ><select id="period_type" name="period_type" title="Period Type" >
			<option value="REGULAR" >REGULAR</option>
			<option value="ADJUSTMENT" >ADJUSTMENT</option>
			<option value="EXTRA CLASS" >EXTRA CLASS</option>
			</select></label>
			<div style="padding :0.2em 0 0 0; position: relative; top: 0.8em; " >
			<button type="submit" name="estate_type" value="project">Search</button>
			<button type="reset" value="reset">Reset</button>
			</div>
</form>

</div>

<table id="stulistgrid" class="scroll"
	cellpadding="0" cellspacing="0"></table>

<div id="statusdiv" class="aligncenter">
<form id="finalStatus">
<table style="padding: 0.5em;"  >
	<tr>
		<td><?php echo $this->formLabel('totalStudents', 'Total Students:')?></td>
		<td><input type="text" id="totalstudents"
			class="ui-widget-content  ui-corner-all" size="4" readonly="readonly"
			value="0" style="text-align: center"></input></td>
		<td><?php echo $this->formLabel('totalabsent', 'Total Absent:')?></td>
		<td><input type="text" id="totalabsent"
			class="ui-widget-content  ui-corner-all" size="4" readonly="readonly"
			value="0" style="text-align: center"></input></td>
		<td><?php echo $this->formLabel('iagree', 'I Agree')?></td>
		<td><?php echo $this->formCheckbox('iagree', 'I Agree', array('tabindex' => '150'))?>
		</td>
		<td>&nbsp;<?php echo $this->formButton('btnmark', 'Submit Attendance', array('tabindex' => '151', 'size' => '70%' ))?></td>
	</tr>
</table>
</form>
&nbsp;
</div>

<script type="text/javascript">
$("#statusdiv").hide();
var urlDegree = "<?php echo 'http://' . CORE_SERVER . $this->url(array('controller' => 'semesterdegree', 'action' => 'getslavedegree'))?>";
var urlSemester = "<?php echo 'http://' . CORE_SERVER . $this->url(array('controller' => 'semesterdegree', 'action' => 'getsessionsemester'))?>";
var urlSemesterSubject = "<?php echo $this->url(array('module' => $this->module, 'controller' => 'subjectdepartment', 'action' => 'getsemsubject'))?>";
var urlSubjectMode = "<?php echo $this->url(array('module' => $this->module, 'controller' => 'subjectmode', 'action' => 'getactivesubjectmode'))?>";

//Some global variables:
var semSubjects = {};


$(function(){
	$("#department_id").change(function(){
		var department_id = $(this).val();
		if (-1 != department_id) {
			updateProgramme(department_id, '#programme_id');
		} else {
			//  Should reset degree etc.
		}
	});

	$("#programme_id").change(function(){
		var programme_id = $(this).val();
		
		if (-1 != programme_id) {
			var department_id = $("#department_id").val();
			var selectString = updateSemester(department_id, programme_id, '#semester_id');
            
		} else {
			// Should reset subject, group etc.
		}
	});

	$("#semester_id").change(function(){
		var semester_id = $(this).val();
		
		if (-1 != semester_id) {
			var department_id = $("#department_id").val();
			var programme_id = $("#programme_id").val();
			var selectString = updateSemesterSubject(department_id, programme_id, semester_id, '#subject_code');
            
		} else {
			// Should reset subject, group etc.
		}
	});
	
////////////////////
//	Element updation functions.
////////////////////
	/**
		Not written because its hard coded.
	*/
	function updateDepartment() {
		
	}

	/**
	 Update Programme/Degree of provided Department
	*/
	function updateProgramme(department_id, elementId) {
	    $.ajax({
	        url : urlDegree,
	        dataType : 'jsonp',
	        crossDomain : true,
	        async:true,
	        data : {'masterDepartment': department_id, 'format' : 'jsonp' },
	        success: function(jDegree){
	        	var selectOptionString = '<option value ="-1">Programme</option>';
				$.each(jDegree, function (index, degree) {
					selectOptionString += '<option value ="'+degree.degree_id+'">'+degree.degree_id+'</option>';
				});
				$(elementId).html(selectOptionString).prop('disabled', '');
            },
            error: function(event) {
                console.log(event.responseText);
                }
            });
	}

	/**
		Update Semester in Selected Programme of a department.
	*/
	function updateSemester(department_id, programme_id,  elementId) {
		$.ajax({
			url : urlSemester,
	        dataType : 'jsonp',
			data : {department_id: department_id,
					degree_id : programme_id,
					format : 'jsonp'},
			success: function(jSemesters){
						var selectOptionString = '<option value ="-1">Semester</option>';
	                	$.each(jSemesters, function (index, semester) {
	        				selectOptionString += '<option value ="'+semester.semester_id+'">'+semester.semester_id+'</option>';
	        			});
	        			$(elementId).html(selectOptionString).prop('disabled', '');
	            },
	            error: function(event) {
	                console.log(event.responseText);
	                }
	            });
	}

	function updateSemesterSubject(department_id, programme_id, semester_id, elementId){

        //Update Subject Code
        $.ajax({
            url : urlSemesterSubject,
            dataType : 'json',
            data : {department_id: department_id,
                    degree_id : programme_id,
                    semester_id: semester_id},
            success: function(jSemSubjects){
                semSubjects = jSemSubjects;
					var selectOptionString = '<option value ="-1">Subject Code</option>';
              	$.each(jSemSubjects, function (subjectCode, subjectInfo) {
      				selectOptionString += '<option value ="'+subjectCode+'">'+subjectInfo[0].subject_name+' | '+subjectCode+'</option>';
      			});
                $(elementId).html(selectOptionString);
                },
                error: function(event) {
                    alert(event.responseText);
                    }
                });
	}


	function updateSubjectMode(subject_code, elementId){

        //Update Subject Code
        $.ajax({
            url : urlSemesterSubject,
            dataType : 'json',
            data : {department_id: department_id,
                    degree_id : programme_id,
                    semester_id: semester_id},
            success: function(jSemSubjects){
                semSubjects = jSemSubjects;
					var selectOptionString = '<option value ="-1">Subject Code</option>';
              	$.each(jSemSubjects, function (subjectCode, subjectInfo) {
      				selectOptionString += '<option value ="'+subjectCode+'">'+subjectInfo[0].subject_name+' | '+subjectCode+'</option>';
      			});
                $(elementId).html(selectOptionString);
                },
                error: function(event) {
                    alert(event.responseText);
                    }
                });
	}


	
var session_startdate = '<?php echo $this->session_startdate;?>';
var baseurl="<?php echo $this->url(array('controller' => $this->controller, 'action' => 'fillperiodgrid'), 'default', true)?>";
var adjustmentUrl = "<?php echo $this->url( array('controller' => 'facultyadjustment', 'action' => 'gettodayadjustments'), 'default', true)?>";
var periodStudentsUrl = "<?php echo $this->url(array('controller' => 'periodattendance', 'action' => 'getperiodstudents'), 'default', true)?>";
var periodAttendanceUrl="<?php echo $this->url(array('controller' => 'periodattendance', 'action' => 'markperiodattendance'), 'default', true)?>";
var studentAttendanceUrl="<?php echo $this->url(array('controller' => $this->controller, 'action' => 'markabsent'), 'default', true)?>";
var isPeriodTakenUrl="<?php echo $this->url(array('controller' => 'periodattendance', 'action' => 'getisperiodtaken'), 'default', true)?>";
var adjPeriodStudentUrl="<?php echo $this->url(array('controller' => $this->controller, 'action' => 'filladjustmentgroup'), 'default', true)?>";
var holidayUrl = "<?php echo 'http://' . CORE_SERVER . $this->url(array('controller' => 'holiday', 'action' => 'getholidays'), 'default', true)?>";


    
serverDateObj = $.datepicker.parseDate('dd-mm-yy', $('#datetext').text());
// @FIXME session_startdate is in different format because its date from db server.
sessionStartdateObj= $.datepicker.parseDate('yy-mm-dd', session_startdate);

$("#period_date").datepicker({
	minDate : sessionStartdateObj,
	maxDate : serverDateObj,
	dateFormat: 'dd-mm-yy',
	showButtonPanel: true
});
	
	$('#iagree').attr('disabled', 'disabled');
	jQuery("#btnmark").click( function() {
        if(group_info !=null)
        {
        var cnt=0;
        var timetable_ids = "";
        var msg = "Total Students:" + $("#totalstudents").val() + "\n" + " Absent Students:" +  $("#totalabsent").val() +"\n" +"Submit Attendance?";
        if (confirm(msg))
        {
            
        for(cnt=0;cnt < group_info.length;cnt++)
        {
            timetable_ids = timetable_ids + "timetable_id:" + group_info[cnt]['timetable_id']  + " ";
            if(subject_mode_id == 'LEC')
            {
                break;
            }
        }

        var studentlst = "";
        var tmptimetable_id;
        var roll_no;
        $("#stulistgrid").find("input:checked").each(function(i) {
             roll_no=$(this).attr( "id");
             tmptimetable_id=$(this).parents("span:first").attr("id");
             if(tmptimetable_id){
                 studentlst =  studentlst + "timetable_id:" + tmptimetable_id + "#student_roll_no:" + roll_no +" ";
             }     
           });
         
           
        $.ajax({
            type: "GET",
            url: periodAttendanceUrl ,
            async : false,
            data: {timetable_ids : timetable_ids , period_date : period_date , staff_id : staff_id },
            success: function(request) {

			if(studentlst.length > 0)
			{
           	 $.ajax({
                 type: "GET",
                 url: studentAttendanceUrl ,
                 async : false,
                 data: {studentlst : studentlst , period_date : period_date },
                 success: function(response) {
                     alert(response);
                     group_info=null;
                     dummy_hideColumns();
                     $("#totalstudents").val('0');
                     $("#totalabsent").val('0');
                     $("#statusdiv").hide();
                 },
                 
                 error: function(request,error) {
                     alert(request);
                 }
                 });

			}
			else
			{
					alert("Attendance is marked successfully.");
					group_info=null;
                    dummy_hideColumns();
                    $("#totalstudents").val('0');
                    $("#totalabsent").val('0');
                    $("#statusdiv").hide();
			}
				   
            },
            error: function(request,error) {
                alert("Period Attendance Not Exists");
                group_info=null;
                dummy_hideColumns();
                $("#totalstudents").val('0');
                $("#totalabsent").val('0');
                $("#statusdiv").hide();
                return;
            }
            });
       
        }
        else
        {
            $("#btnmark").hide();
            $('#iagree').attr('checked',0); 
        }
        }
    });
	
	//dummy_hidePeriodColumns();	
		
	$('#iagree').click(function(){
		if($('#iagree').attr('checked'))
		{
			$("#btnmark").show();	
		}
		else
		{
			$("#btnmark").hide();	
		}
		});
	

function selectAll(component)
{
	var checked=component.checked;
	var group_id = component.id;
	if(global_Info != null)
	{
		var studentlist= global_Info[group_id]['students'];
	for(var stucnt=0;stucnt < studentlist.length ; stucnt++ )
	{
			$("#" + studentlist[stucnt]['student_roll_no']).attr("checked",checked);
			if(checked)
			{
				$('label[for='+studentlist[stucnt]['student_roll_no']+']').addClass('checked');
			}
			else
			{
				$('label[for='+studentlist[stucnt]['student_roll_no']+']').removeClass('checked');
							
			}
		
	}
	
	updateStatus();
	}
}


function hideColumns()
{
	
	$("#stulistgrid").jqGrid('hideCol',["group1","group2" , "group3"]);
    
}

function dummy_hideColumns()
{
	
}
function hidePeriodColumns()
{
	$("#prdlst").jqGrid('hideCol',["subject_code","subject_mode_id" , "period_number" , "department_id","degree_id","semester_id"] );

}
function dummy_hidePeriodColumns()
{
	
}
function showPeriodColumns()
{
	$("#prdlst").jqGrid('showCol',["subject_code","subject_mode_id" , "period_number" , "department_id","degree_id","semester_id"] );
}

function updateStatus(component){
	var allcheck=0;
	if(group_info != null){
		for(cnt = 0 ;cnt < group_info.length ;cnt++ ){
			if($("#" + group_info[cnt]['group_id']).attr("checked")){
				allcheck++;
			}		
		}
		
		var cnt=0;
		var tmp= $("#stulistgrid").find("input:checked").length - allcheck;
		$('#totalabsent').val( tmp);
		
		if(component){
			if(component.checked){
				$(component).parent("label:first").addClass("checked");
			} else {
				$(component).parent("label:first").removeClass("checked");
				$(component).parent("label:first").removeClass("focus");
				
			}
		}
	}
}

function setDefault()
{
	$('#totalabsent').val('0');
	$("#btnmark").hide();
	$('#iagree').attr('checked',0);	
	$('#totalstudents').val('0');
}
});
</script>
<?php
$this->headLink()->appendStylesheet(
'http://' . CDN_SERVER . '/plugins/checkbox/filament/filament.css');
$this->headScript()->appendFile(
'http://' . CDN_SERVER . '/plugins/checkbox/filament/customInput.js');
?>